import { useQuery } from "@tanstack/react-query"
import {
  createFileRoute,
  Link as RouterLink,
  redirect,
} from "@tanstack/react-router"
import { useState } from "react"
import { type SubmitHandler, useForm } from "react-hook-form"
import { motion } from "framer-motion"
import { useTheme } from "next-themes"
import type { Body_login_login_access_token as AccessToken } from "@/client"
import { OpenAPI } from "@/client"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { WaveAnimation } from "@/components/ui/wave-animation"
import useAuth, { isLoggedIn } from "@/hooks/useAuth"
import { passwordRules } from "../utils"
import {
  User,
  Lock,
  Eye,
  EyeOff,
  Sparkles,
  BarChart3,
  Zap,
  Sun,
  Moon,
} from "lucide-react"

// Type for quick login users response
interface QuickLoginUser {
  username: string
  email: string | null
}

interface QuickLoginUsers {
  admin: QuickLoginUser[]
  supervisor: QuickLoginUser[]
  publisher: QuickLoginUser[]
  teacher: QuickLoginUser[]
  student: QuickLoginUser[]
}

export const Route = createFileRoute("/login")({
  component: Login,
  beforeLoad: async () => {
    if (isLoggedIn()) {
      throw redirect({
        to: "/",
      })
    }
  },
})

// Feature data
const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Learning",
    description: "Personalized content generated by advanced AI",
  },
  {
    icon: BarChart3,
    title: "Real-time Analytics",
    description: "Track progress with detailed insights",
  },
  {
    icon: Zap,
    title: "Smart Assignments",
    description: "Adaptive assessments that evolve with you",
  },
]

// Animation variants
const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.2,
    },
  },
}

const itemVariants = {
  hidden: { opacity: 0, x: -20 },
  visible: {
    opacity: 1,
    x: 0,
    transition: { duration: 0.5, ease: "easeOut" as const },
  },
}

const cardVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" as const },
  },
}

function Login() {
  const { loginMutation } = useAuth()
  const { theme, setTheme } = useTheme()
  const [loginError, setLoginError] = useState<string | null>(null)
  const [showPassword, setShowPassword] = useState(false)
  const {
    register,
    handleSubmit,
    formState: { isSubmitting, errors },
  } = useForm<AccessToken>({
    mode: "onBlur",
    criteriaMode: "all",
    defaultValues: {
      username: "",
      password: "",
    },
  })

  // Fetch quick login users (development only)
  const { data: quickLoginUsers, isError } = useQuery<QuickLoginUsers>({
    queryKey: ["quick-login-users"],
    queryFn: async () => {
      const response = await fetch(
        `${OpenAPI.BASE}/api/v1/dev/quick-login-users`,
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        },
      )
      if (!response.ok) {
        throw new Error("Failed to fetch quick login users")
      }
      return response.json()
    },
    enabled: import.meta.env.DEV,
    retry: false,
    staleTime: 0,
  })

  const onSubmit: SubmitHandler<AccessToken> = async (data) => {
    if (isSubmitting) return
    setLoginError(null)

    try {
      await loginMutation.mutateAsync(data)
    } catch (err: unknown) {
      const error = err as { body?: { detail?: string } }
      setLoginError(error.body?.detail || "Invalid credentials")
    }
  }

  const instantLogin = async (username: string) => {
    setLoginError(null)
    try {
      const response = await fetch(
        `${OpenAPI.BASE}/api/v1/dev/instant-login/${username}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
        },
      )
      if (!response.ok) {
        const error = await response.json()
        throw new Error(error.detail || "Login failed")
      }
      const data = await response.json()
      localStorage.setItem("access_token", data.access_token)
      window.location.href = "/"
    } catch (err: unknown) {
      const error = err as Error
      setLoginError(error.message || "Login failed")
    }
  }

  const toggleTheme = () => {
    setTheme(theme === "dark" ? "light" : "dark")
  }

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Gradient background - turquoise to white (left to right) */}
      <div className="absolute inset-0 bg-gradient-to-r from-teal-500 via-teal-400 to-white dark:from-neutral-900 dark:via-neutral-800 dark:to-neutral-950" />
      {/* Theme Toggle - Top Right */}
      <button
        onClick={toggleTheme}
        className="fixed top-4 right-4 z-50 p-2.5 rounded-xl bg-white/80 dark:bg-neutral-800 backdrop-blur-sm border border-gray-200 dark:border-neutral-700 hover:bg-white dark:hover:bg-neutral-700 shadow-lg transition-colors"
        aria-label="Toggle theme"
      >
        {theme === "dark" ? (
          <Sun className="w-5 h-5 text-amber-500" />
        ) : (
          <Moon className="w-5 h-5 text-gray-700" />
        )}
      </button>

      {/* Main Content Container */}
      <div className="relative z-10 min-h-screen flex items-center justify-center lg:justify-between px-4 py-8 lg:px-12 xl:px-20 2xl:px-32 pb-[14vh]">

        {/* Left Hero Section - Hidden on mobile */}
        <motion.div
          className="hidden lg:flex flex-col justify-center max-w-xl"
          variants={containerVariants}
          initial="hidden"
          animate="visible"
        >
          {/* Logo */}
          <motion.div variants={itemVariants} className="flex items-center gap-4 mb-6">
            <img
              src="/assets/images/dreamedtech_single.svg"
              alt="Dream EdTech"
              className="h-16 xl:h-20 w-auto"
            />
            <span className="text-3xl xl:text-4xl font-bold text-white tracking-tight">
              Dream <span className="text-teal-100">EdTech</span>
            </span>
          </motion.div>

          {/* Headline */}
          <motion.div variants={itemVariants} className="mb-8">
            <h1 className="text-3xl xl:text-4xl 2xl:text-5xl font-bold text-white leading-tight mb-4">
              Empowering Education
              <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-700 to-teal-800 dark:from-teal-400 dark:to-cyan-400">
                with AI Innovation
              </span>
            </h1>
            <p className="text-base xl:text-lg text-white/80 dark:text-neutral-400 max-w-lg">
              Transform the way you teach and learn with our intelligent learning management system.
            </p>
          </motion.div>

          {/* Features */}
          <motion.div variants={itemVariants} className="space-y-3">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="flex items-center gap-4 p-3 rounded-xl bg-white/10 dark:bg-white/5 border border-white/20 dark:border-white/10 hover:bg-white/20 dark:hover:bg-white/10 transition-colors"
              >
                <div className="p-2 rounded-lg bg-white/20 dark:bg-gradient-to-br dark:from-teal-500/20 dark:to-cyan-500/20">
                  <feature.icon className="w-5 h-5 text-white dark:text-teal-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">{feature.title}</h3>
                  <p className="text-sm text-white/70 dark:text-neutral-400">{feature.description}</p>
                </div>
              </div>
            ))}
          </motion.div>
        </motion.div>

        {/* Right Login Card */}
        <motion.div
          className="w-full max-w-md lg:max-w-sm xl:max-w-md"
          variants={cardVariants}
          initial="hidden"
          animate="visible"
        >
          {/* Outer glow wrapper */}
          <div className="relative">
            {/* Glow effect */}
            <div className="absolute -inset-1 bg-gradient-to-r from-teal-400 via-cyan-400 to-teal-400 dark:from-teal-500 dark:via-cyan-500 dark:to-teal-500 rounded-3xl blur-lg opacity-30 dark:opacity-20" />

            {/* Card */}
            <div className="relative bg-white dark:bg-neutral-900 backdrop-blur-xl rounded-2xl shadow-2xl shadow-black/20 dark:shadow-black/40 p-6 sm:p-8 border border-white/50 dark:border-white/10 overflow-hidden">
              {/* Top shine effect */}
              <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/80 dark:via-white/20 to-transparent" />
              <div className="absolute top-0 left-0 right-0 h-24 bg-gradient-to-b from-white/50 dark:from-white/5 to-transparent pointer-events-none" />

              {/* Header */}
              <div className="relative mb-6">
                <h2 className="text-2xl font-bold text-foreground mb-2">
                  Welcome Back
                </h2>
                <p className="text-muted-foreground">
                  Sign in to continue your learning journey
                </p>
              </div>

              {/* Login Form */}
              <form onSubmit={handleSubmit(onSubmit)} className="relative space-y-4">
              {/* Username */}
              <div>
                <label className="text-sm font-medium text-foreground mb-1.5 block">
                  Username
                </label>
                <div className="relative">
                  <User className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                  <Input
                    {...register("username", {
                      required: "Username or email is required",
                    })}
                    placeholder="Enter username or email"
                    type="text"
                    className="pl-12 h-12 rounded-xl bg-neutral-50 dark:bg-neutral-800/50 border-neutral-200 dark:border-neutral-700 focus:border-teal-500 focus:ring-teal-500/20 transition-all"
                  />
                </div>
              </div>

              {/* Password */}
              <div>
                <label className="text-sm font-medium text-foreground mb-1.5 block">
                  Password
                </label>
                <div className="relative">
                  <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                  <Input
                    {...register("password", passwordRules())}
                    placeholder="Enter password"
                    type={showPassword ? "text" : "password"}
                    className="pl-12 pr-12 h-12 rounded-xl bg-neutral-50 dark:bg-neutral-800/50 border-neutral-200 dark:border-neutral-700 focus:border-teal-500 focus:ring-teal-500/20 transition-all"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                  >
                    {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                  </button>
                </div>
                {errors.password && (
                  <p className="text-sm text-destructive mt-2">{errors.password.message}</p>
                )}
              </div>

              {/* Error */}
              {loginError && (
                <div className="p-3 rounded-xl bg-destructive/10 border border-destructive/20 text-destructive text-sm text-center">
                  {loginError}
                </div>
              )}

              {/* Forgot Password */}
              <div className="text-right">
                <RouterLink
                  to="/recover-password"
                  className="text-sm text-primary hover:text-primary/80 transition-colors"
                >
                  Forgot Password?
                </RouterLink>
              </div>

              {/* Submit */}
              <Button
                type="submit"
                disabled={isSubmitting || loginMutation.isPending}
                className="w-full h-12 rounded-xl bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-400 hover:to-cyan-400 text-white font-semibold shadow-lg shadow-teal-500/30 hover:shadow-teal-500/50 hover:scale-[1.02] active:scale-[0.98] transition-all duration-200"
              >
                {loginMutation.isPending ? (
                  <div className="flex items-center gap-2">
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Signing in...
                  </div>
                ) : (
                  "Sign In"
                )}
              </Button>
            </form>

            {/* Dev Quick Login */}
            {import.meta.env.DEV && (
              <div className="mt-6 pt-4 border-t border-border">
                <p className="text-xs text-center text-muted-foreground mb-3 flex items-center justify-center gap-2">
                  <span className="px-2 py-1 rounded-full bg-amber-500/10 text-amber-600 dark:text-amber-400 text-xs font-medium">
                    DEV
                  </span>
                  Quick Login
                </p>
                {isError && (
                  <p className="text-xs text-center text-destructive mb-2">Unavailable</p>
                )}
                {!isError && quickLoginUsers && (
                  <div className="space-y-2 max-h-[140px] overflow-y-auto">
                    {[
                      { key: "admin" as const, label: "Admin", color: "text-amber-600 dark:text-amber-400" },
                      { key: "teacher" as const, label: "Teacher", color: "text-emerald-600 dark:text-emerald-400" },
                      { key: "student" as const, label: "Student", color: "text-purple-600 dark:text-purple-400" },
                    ].map((role) => {
                      const users = quickLoginUsers[role.key] || []
                      if (users.length === 0) return null
                      return (
                        <div key={role.key} className="flex flex-wrap gap-1.5">
                          <span className={`text-xs ${role.color} w-16`}>{role.label}:</span>
                          {users.slice(0, 3).map((user) => (
                            <Button
                              key={user.username}
                              type="button"
                              variant="outline"
                              size="sm"
                              onClick={() => instantLogin(user.username)}
                              className="text-xs h-6 px-2 rounded"
                            >
                              {user.username}
                            </Button>
                          ))}
                        </div>
                      )
                    })}
                  </div>
                )}
              </div>
            )}

            {/* Footer Links */}
            <div className="mt-6 pt-4 border-t border-border">
              <div className="flex items-center justify-center gap-4 text-xs text-muted-foreground">
                <a href="#" className="hover:text-foreground transition-colors">Documentation</a>
                <span>|</span>
                <a href="#" className="hover:text-foreground transition-colors">Support</a>
                <span>|</span>
                <a href="#" className="hover:text-foreground transition-colors">Privacy</a>
              </div>
            </div>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Wave Animation - Full Width */}
      <WaveAnimation />
    </div>
  )
}
