// This file is auto-generated by @hey-api/openapi-ts

export const Body_admin_bulk_import_publishersSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_admin-bulk_import_publishers'
} as const;

export const Body_admin_bulk_import_studentsSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_admin-bulk_import_students'
} as const;

export const Body_admin_bulk_import_teachersSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_admin-bulk_import_teachers'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_teachers_bulk_import_studentsSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_teachers-bulk_import_students'
} as const;

export const BulkImportErrorDetailSchema = {
    properties: {
        row_number: {
            type: 'integer',
            title: 'Row Number'
        },
        field: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Field'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['row_number', 'message'],
    title: 'BulkImportErrorDetail',
    description: 'Details of a single bulk import validation error'
} as const;

export const BulkImportResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        total_rows: {
            type: 'integer',
            title: 'Total Rows'
        },
        created_count: {
            type: 'integer',
            title: 'Created Count'
        },
        error_count: {
            type: 'integer',
            title: 'Error Count'
        },
        errors: {
            items: {
                '$ref': '#/components/schemas/BulkImportErrorDetail'
            },
            type: 'array',
            title: 'Errors'
        },
        credentials: {
            anyOf: [
                {
                    items: {
                        additionalProperties: {
                            type: 'string'
                        },
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentials'
        }
    },
    type: 'object',
    required: ['success', 'total_rows', 'created_count', 'error_count', 'errors'],
    title: 'BulkImportResponse',
    description: 'Response schema for bulk import endpoints'
} as const;

export const ClassCreateByTeacherSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        academic_year: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Academic Year'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ClassCreateByTeacher',
    description: "Properties to receive via API on Class creation by Teacher (teacher_id and school_id set automatically from teacher's record)"
} as const;

export const ClassPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        academic_year: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Academic Year'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        teacher_id: {
            type: 'string',
            format: 'uuid',
            title: 'Teacher Id'
        },
        school_id: {
            type: 'string',
            format: 'uuid',
            title: 'School Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'teacher_id', 'school_id', 'created_at', 'updated_at'],
    title: 'ClassPublic',
    description: 'Properties to return via API'
} as const;

export const ClassUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        academic_year: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Academic Year'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ClassUpdate',
    description: 'Properties to receive via API on Class update'
} as const;

export const DashboardStatsSchema = {
    properties: {
        total_users: {
            type: 'integer',
            title: 'Total Users'
        },
        total_publishers: {
            type: 'integer',
            title: 'Total Publishers'
        },
        total_teachers: {
            type: 'integer',
            title: 'Total Teachers'
        },
        total_students: {
            type: 'integer',
            title: 'Total Students'
        },
        active_schools: {
            type: 'integer',
            title: 'Active Schools'
        }
    },
    type: 'object',
    required: ['total_users', 'total_publishers', 'total_teachers', 'total_students', 'active_schools'],
    title: 'DashboardStats',
    description: 'Dashboard statistics for admin view'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PublisherCreateAPISchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        contact_email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Contact Email'
        },
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        user_email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'User Email'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['name', 'contact_email', 'username', 'user_email', 'full_name'],
    title: 'PublisherCreateAPI',
    description: 'Properties for API endpoint publisher creation (includes user creation)'
} as const;

export const PublisherPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        user_email: {
            type: 'string',
            title: 'User Email'
        },
        user_username: {
            type: 'string',
            title: 'User Username'
        },
        user_full_name: {
            type: 'string',
            title: 'User Full Name'
        },
        user_initial_password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Initial Password'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'user_id', 'user_email', 'user_username', 'user_full_name', 'created_at', 'updated_at'],
    title: 'PublisherPublic',
    description: 'Properties to return via API'
} as const;

export const PublisherUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        }
    },
    type: 'object',
    title: 'PublisherUpdate',
    description: 'Properties to receive via API on Publisher update'
} as const;

export const SchoolCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        contact_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Info'
        },
        publisher_id: {
            type: 'string',
            format: 'uuid',
            title: 'Publisher Id'
        }
    },
    type: 'object',
    required: ['name', 'publisher_id'],
    title: 'SchoolCreate',
    description: 'Properties to receive via API on School creation'
} as const;

export const SchoolCreateByPublisherSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        contact_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Info'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SchoolCreateByPublisher',
    description: 'Properties to receive via API on School creation by Publisher (publisher_id set automatically)'
} as const;

export const SchoolPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        contact_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Info'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        publisher_id: {
            type: 'string',
            format: 'uuid',
            title: 'Publisher Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'publisher_id', 'created_at', 'updated_at'],
    title: 'SchoolPublic',
    description: 'Properties to return via API'
} as const;

export const SchoolUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        contact_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Info'
        },
        publisher_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Publisher Id'
        }
    },
    type: 'object',
    title: 'SchoolUpdate',
    description: 'Properties to receive via API on School update'
} as const;

export const StudentCreateAPISchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        user_email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'User Email'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        parent_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Email'
        }
    },
    type: 'object',
    required: ['username', 'user_email', 'full_name'],
    title: 'StudentCreateAPI',
    description: 'Properties for API endpoint student creation (includes user creation)'
} as const;

export const StudentPublicSchema = {
    properties: {
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        parent_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Email'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        user_email: {
            type: 'string',
            title: 'User Email'
        },
        user_username: {
            type: 'string',
            title: 'User Username'
        },
        user_full_name: {
            type: 'string',
            title: 'User Full Name'
        },
        user_initial_password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Initial Password'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'user_email', 'user_username', 'user_full_name', 'created_at', 'updated_at'],
    title: 'StudentPublic',
    description: 'Properties to return via API'
} as const;

export const StudentUpdateSchema = {
    properties: {
        user_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Username'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        parent_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Email'
        }
    },
    type: 'object',
    title: 'StudentUpdate',
    description: 'Properties to receive via API on Student update'
} as const;

export const TeacherCreateAPISchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        user_email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'User Email'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        school_id: {
            type: 'string',
            format: 'uuid',
            title: 'School Id'
        },
        subject_specialization: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject Specialization'
        }
    },
    type: 'object',
    required: ['username', 'user_email', 'full_name', 'school_id'],
    title: 'TeacherCreateAPI',
    description: 'Properties for API endpoint teacher creation (includes user creation)'
} as const;

export const TeacherPublicSchema = {
    properties: {
        subject_specialization: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject Specialization'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        user_email: {
            type: 'string',
            title: 'User Email'
        },
        user_username: {
            type: 'string',
            title: 'User Username'
        },
        user_full_name: {
            type: 'string',
            title: 'User Full Name'
        },
        user_initial_password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Initial Password'
        },
        school_id: {
            type: 'string',
            format: 'uuid',
            title: 'School Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'user_email', 'user_username', 'user_full_name', 'school_id', 'created_at', 'updated_at'],
    title: 'TeacherPublic',
    description: 'Properties to return via API'
} as const;

export const TeacherUpdateSchema = {
    properties: {
        school_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'School Id'
        },
        subject_specialization: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject Specialization'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        }
    },
    type: 'object',
    title: 'TeacherUpdate',
    description: 'Properties to receive via API on Teacher update'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'username', 'password'],
    title: 'UserCreate'
} as const;

export const UserCreationResponseSchema = {
    properties: {
        user: {
            '$ref': '#/components/schemas/UserPublic'
        },
        initial_password: {
            type: 'string',
            title: 'Initial Password'
        },
        role_record: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PublisherPublic'
                },
                {
                    '$ref': '#/components/schemas/TeacherPublic'
                },
                {
                    '$ref': '#/components/schemas/StudentPublic'
                }
            ],
            title: 'Role Record'
        }
    },
    type: 'object',
    required: ['user', 'initial_password', 'role_record'],
    title: 'UserCreationResponse',
    description: 'Response schema for role-specific user creation endpoints'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        initial_password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Initial Password'
        }
    },
    type: 'object',
    required: ['email', 'username', 'id'],
    title: 'UserPublic'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'publisher', 'teacher', 'student'],
    title: 'UserRole',
    description: 'User role enumeration for RBAC'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;