// This file is auto-generated by @hey-api/openapi-ts

/**
 * Student achievement/badge.
 */
export type Achievement = {
    id: string;
    type: string;
    title: string;
    description: string;
    earned_at: string;
    icon: string;
};

/**
 * Analytics data for a single activity within a multi-activity assignment.
 */
export type ActivityAnalyticsItem = {
    activity_id: string;
    activity_title: (string | null);
    page_number: number;
    activity_type: string;
    class_average_score: (number | null);
    completion_rate: number;
    completed_count: number;
    total_assigned_count: number;
};

/**
 * Performance breakdown by activity type.
 */
export type ActivityBreakdownItem = {
    activity_type: string;
    avg_score: number;
    count: number;
};

/**
 * Coordinates for an activity marker on a page.
 */
export type ActivityCoords = {
    x: number;
    y: number;
    w: number;
    h: number;
};

/**
 * Minimal activity info for assignment response.
 */
export type ActivityInfo = {
    id: string;
    title: (string | null);
    activity_type: string;
    order_index?: number;
};

/**
 * Activity marker with position and metadata for page viewer.
 */
export type ActivityMarker = {
    id: string;
    title: (string | null);
    activity_type: string;
    section_index: number;
    coords: (ActivityCoords | null);
};

/**
 * Response schema for single activity preview.
 *
 * Returns activity data in student-view format for teacher preview.
 */
export type ActivityPreviewResponse = {
    activity_id: string;
    activity_title: (string | null);
    activity_type: string;
    config_json: {
        [key: string]: unknown;
    };
    book_id: string;
    book_name: string;
    publisher_name: string;
    is_preview?: boolean;
};

/**
 * Per-activity progress info for multi-activity assignments.
 */
export type ActivityProgressInfo = {
    id: string;
    activity_id: string;
    status: string;
    score: (number | null);
    max_score: number;
    response_data: ({
    [key: string]: unknown;
} | null);
    started_at: (string | null);
    completed_at: (string | null);
};

/**
 * Request schema for saving per-activity progress.
 */
export type ActivityProgressSaveRequest = {
    response_data: {
        [key: string]: unknown;
    };
    time_spent_seconds?: number;
    status?: string;
    score?: (number | null);
    max_score?: number;
};

/**
 * Response schema for saving per-activity progress.
 */
export type ActivityProgressSaveResponse = {
    message: string;
    activity_id: string;
    status: string;
    score: (number | null);
    last_saved_at: string;
};

/**
 * Activity response schema for API.
 */
export type ActivityResponse = {
    id: string;
    dcs_book_id: number;
    module_name: string;
    page_number: number;
    activity_type: string;
    title: (string | null);
};

/**
 * Per-activity score item for student result view.
 */
export type ActivityScoreItem = {
    activity_id: string;
    activity_title: (string | null);
    activity_type: string;
    score: (number | null);
    max_score: number;
    status: string;
};

/**
 * Response schema for starting an assignment - returns full activity configuration.
 */
export type ActivityStartResponse = {
    assignment_id: string;
    assignment_name: string;
    instructions: (string | null);
    due_date: (string | null);
    time_limit_minutes: (number | null);
    book_id: string;
    book_title: string;
    book_name: string;
    publisher_name: string;
    book_cover_url: (string | null);
    activity_id: string;
    activity_title: string;
    activity_type: string;
    config_json: {
        [key: string]: unknown;
    };
    current_status: string;
    time_spent_minutes: number;
    progress_json: ({
    [key: string]: unknown;
} | null);
    /**
     * Check if there is saved progress to resume from.
     */
    readonly has_saved_progress: boolean;
};

/**
 * Activity-type specific analysis results.
 */
export type ActivityTypeAnalysis = {
    activity_type: string;
    questions?: (Array<QuestionAnalysis> | null);
    most_missed?: (Array<MostMissedQuestion> | null);
    word_matching_errors?: (Array<WordMatchingError> | null);
    fill_in_blank?: (Array<FillInBlankAnalysis> | null);
    word_search?: (Array<WordSearchAnalysis> | null);
};

/**
 * Performance comparison for a specific activity type.
 *
 * [Source: Story 5.7 AC: 5]
 * Compares class performance against benchmark for each activity type.
 */
export type ActivityTypeBenchmark = {
    activity_type: string;
    activity_label: string;
    class_average: number;
    benchmark_average: number;
    /**
     * Positive = class is above benchmark, negative = below
     */
    difference_percent: number;
};

/**
 * Performance breakdown by activity type.
 */
export type ActivityTypePerformanceItem = {
    activity_type: string;
    avg_score: number;
    count: number;
};

/**
 * Student's average score for an activity type.
 */
export type ActivityTypeScore = {
    activity_type: string;
    avg_score: number;
    total_completed: number;
    label: string;
};

/**
 * System-wide statistics for an activity type.
 *
 * [Source: Story 5.7 AC: 12]
 */
export type ActivityTypeStat = {
    activity_type: string;
    activity_label: string;
    system_average: number;
    total_completions: number;
};

/**
 * Activity info with full config for multi-activity player.
 */
export type ActivityWithConfig = {
    id: string;
    title: (string | null);
    activity_type: string;
    config_json: {
        [key: string]: unknown;
    };
    order_index?: number;
};

/**
 * Schema for additional resources attached to an assignment.
 *
 * Supports video resources and teacher-uploaded materials.
 */
export type AdditionalResources = {
    videos?: Array<VideoResource>;
    teacher_materials?: Array<TeacherMaterialResource>;
};

/**
 * Response schema with enriched material data and availability status.
 */
export type AdditionalResourcesResponse = {
    videos?: Array<VideoResource>;
    teacher_materials?: Array<TeacherMaterialResourceResponse>;
};

/**
 * System-wide benchmark overview for admin dashboard.
 *
 * [Source: Story 5.7 AC: 12]
 */
export type AdminBenchmarkOverview = {
    total_schools: number;
    schools_with_benchmarking: number;
    schools_above_average: number;
    schools_at_average: number;
    schools_below_average: number;
    system_average_score: number;
    activity_type_stats: Array<ActivityTypeStat>;
    school_summaries: Array<SchoolBenchmarkSummary>;
    last_calculated: string;
};

/**
 * Student affected by an insight.
 */
export type AffectedStudent = {
    student_id: string;
    name: string;
    relevant_metric: string;
};

/**
 * Aggregated summary metrics for a student.
 */
export type AnalyticsSummary = {
    avg_score: number;
    total_completed: number;
    completion_rate: number;
    current_streak: number;
};

/**
 * Distribution of answers for a single option.
 */
export type AnswerDistributionItem = {
    option: string;
    count: number;
    percentage: number;
    is_correct: boolean;
};

/**
 * Notification type enumeration
 */
export type app__models__NotificationType = 'assignment_created' | 'deadline_approaching' | 'feedback_received' | 'message_received' | 'student_completed' | 'past_due' | 'material_shared' | 'system_announcement' | 'password_reset';

/**
 * Enum for notification types.
 */
export type app__schemas__notification__NotificationType = 'assignment_created' | 'deadline_approaching' | 'feedback_received' | 'message_received' | 'student_completed' | 'past_due' | 'material_shared' | 'system_announcement' | 'password_reset';

/**
 * Schema for creating a new assignment.
 *
 * Supports both single-activity (backward compatible) and multi-activity assignments.
 * Provide either activity_id (single) OR activity_ids (multi) OR date_groups (Time Planning).
 */
export type AssignmentCreate = {
    book_id: string;
    name: string;
    instructions?: (string | null);
    due_date?: (string | null);
    time_limit_minutes?: (number | null);
    student_ids?: (Array<(string)> | null);
    class_ids?: (Array<(string)> | null);
    activity_id?: (string | null);
    activity_ids?: (Array<(string)> | null);
    scheduled_publish_date?: (string | null);
    date_groups?: (Array<DateGroupCreate> | null);
    video_path?: (string | null);
    resources?: (AdditionalResources | null);
};

/**
 * Complete detailed results for an assignment.
 */
export type AssignmentDetailedResultsResponse = {
    assignment_id: string;
    assignment_name: string;
    activity_type: string;
    due_date: (string | null);
    completion_overview: CompletionOverview;
    score_statistics: (ScoreStatistics | null);
    student_results: Array<StudentResultItem>;
    question_analysis: (ActivityTypeAnalysis | null);
};

/**
 * Assignment list item with enriched data for display.
 */
export type AssignmentListItem = {
    id: string;
    name: string;
    instructions: (string | null);
    due_date: (string | null);
    time_limit_minutes: (number | null);
    created_at: string;
    book_id: string;
    book_title: string;
    activity_id: string;
    activity_title: string;
    activity_type: string;
    total_students: number;
    not_started: number;
    in_progress: number;
    completed: number;
    teacher_name?: (string | null);
    scheduled_publish_date?: (string | null);
    status?: AssignmentPublishStatus;
};

/**
 * Paginated response for assignment lists.
 */
export type AssignmentListResponse = {
    items: Array<AssignmentWithTeacher>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * Performance metrics for a single assignment.
 */
export type AssignmentPerformanceItem = {
    assignment_id: string;
    name: string;
    avg_score: number;
    completion_rate: number;
    avg_time_spent: number;
};

/**
 * Response schema for teacher assignment preview/test mode.
 *
 * Similar to MultiActivityStartResponse but without student-specific data.
 * Used for teachers to preview/test assignments before or after publishing.
 */
export type AssignmentPreviewResponse = {
    assignment_id: string;
    assignment_name: string;
    instructions: (string | null);
    due_date: (string | null);
    time_limit_minutes: (number | null);
    status: AssignmentPublishStatus;
    book_id: string;
    book_title: string;
    book_name: string;
    publisher_name: string;
    book_cover_url: (string | null);
    activities: Array<ActivityWithConfig>;
    total_activities: number;
    is_preview?: boolean;
    video_path?: (string | null);
    resources?: (AdditionalResourcesResponse | null);
};

/**
 * Assignment publishing status
 */
export type AssignmentPublishStatus = 'draft' | 'scheduled' | 'published' | 'archived';

/**
 * Assignment response schema for API.
 */
export type AssignmentResponse = {
    id: string;
    teacher_id: string;
    book_id: string;
    name: string;
    instructions: (string | null);
    due_date: (string | null);
    time_limit_minutes: (number | null);
    created_at: string;
    updated_at: string;
    student_count?: number;
    activity_id?: (string | null);
    activities?: Array<ActivityInfo>;
    activity_count?: number;
    scheduled_publish_date?: (string | null);
    status?: AssignmentPublishStatus;
    video_path?: (string | null);
};

/**
 * Request schema for saving assignment progress.
 */
export type AssignmentSaveProgressRequest = {
    partial_answers_json: {
        [key: string]: unknown;
    };
    time_spent_minutes: number;
};

/**
 * Response schema for saving assignment progress.
 */
export type AssignmentSaveProgressResponse = {
    message: string;
    last_saved_at: string;
    time_spent_minutes: number;
};

/**
 * Response schema for assignment submission.
 */
export type AssignmentSubmissionResponse = {
    success: boolean;
    message: string;
    score: number;
    completed_at: string;
    assignment_id: string;
};

/**
 * Student submission payload for completing an assignment.
 */
export type AssignmentSubmitRequest = {
    answers_json: {
        [key: string]: unknown;
    };
    score: number;
    time_spent_minutes: number;
    completed_at?: (string | null);
};

/**
 * Schema for updating an existing assignment (partial update).
 *
 * Story 9.8: Added activity_ids field to allow editing activities.
 * Story 10.3: Added video_path field to allow attaching/removing video.
 */
export type AssignmentUpdate = {
    name?: (string | null);
    instructions?: (string | null);
    due_date?: (string | null);
    time_limit_minutes?: (number | null);
    scheduled_publish_date?: (string | null);
    status?: (AssignmentPublishStatus | null);
    activity_ids?: (Array<(string)> | null);
    video_path?: (string | null);
    resources?: (AdditionalResources | null);
};

/**
 * Assignment response with teacher information for admin view.
 */
export type AssignmentWithTeacher = {
    id: string;
    title: string;
    teacher_id: string;
    teacher_name: string;
    teacher_email: string;
    recipient_count?: number;
    completed_count?: number;
    due_date: (string | null);
    status: AssignmentPublishStatus;
    created_at: string;
};

/**
 * Avatar type enumeration
 */
export type AvatarType = 'custom' | 'predefined';

/**
 * Response after updating avatar.
 */
export type AvatarUpdateResponse = {
    message: string;
    avatar_url: (string | null);
    avatar_type: (AvatarType | null);
};

/**
 * Type definition for badge information.
 */
export type BadgeInfo = {
    slug: string;
    label: string;
    icon: string;
};

/**
 * Aggregated benchmark data for a level (school or publisher).
 *
 * [Source: Story 5.7 AC: 2, 4, 5, 7]
 */
export type BenchmarkData = {
    level: 'school' | 'publisher';
    /**
     * Average score as percentage
     */
    average_score: number;
    /**
     * Completion rate as percentage
     */
    completion_rate: number;
    /**
     * Number of classes in benchmark
     */
    sample_size: number;
    period: 'weekly' | 'monthly' | 'semester' | 'all';
    /**
     * False if < 5 classes threshold not met
     */
    is_available?: boolean;
};

export type level = 'school' | 'publisher';

export type period = 'weekly' | 'monthly' | 'semester' | 'all';

/**
 * Encouraging or constructive message based on performance.
 *
 * [Source: Story 5.7 AC: 10, 11]
 */
export type BenchmarkMessage = {
    type: 'excelling' | 'above_average' | 'at_average' | 'below_average' | 'needs_focus';
    title: string;
    description: string;
    icon: string;
    focus_area?: (string | null);
};

export type type = 'excelling' | 'above_average' | 'at_average' | 'below_average' | 'needs_focus';

/**
 * Response after updating benchmark settings.
 *
 * [Source: Story 5.7 AC: 9]
 */
export type BenchmarkSettingsResponse = {
    entity_type: 'school' | 'publisher';
    entity_id: string;
    benchmarking_enabled: boolean;
    updated_at: string;
};

export type entity_type = 'school' | 'publisher';

/**
 * Request to update benchmark settings.
 *
 * [Source: Story 5.7 AC: 9]
 */
export type BenchmarkSettingsUpdate = {
    benchmarking_enabled: boolean;
};

/**
 * Single data point in benchmark trend over time.
 *
 * [Source: Story 5.7 AC: 3]
 */
export type BenchmarkTrendPoint = {
    period: string;
    period_label: string;
    class_average: number;
    school_benchmark?: (number | null);
    publisher_benchmark?: (number | null);
};

export type Body_admin_bulk_import_publishers = {
    file: (Blob | File);
};

export type Body_admin_bulk_import_students = {
    file: (Blob | File);
};

export type Body_admin_bulk_import_teachers = {
    file: (Blob | File);
};

export type Body_admin_upload_publisher_logo = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_students_execute_import = {
    /**
     * Excel file (.xlsx or .xls)
     */
    file: (Blob | File);
};

export type Body_students_validate_import_file = {
    /**
     * Excel file (.xlsx or .xls)
     */
    file: (Blob | File);
};

export type Body_teacher_materials_upload_material = {
    file: (Blob | File);
};

export type Body_teachers_bulk_import_students = {
    file: (Blob | File);
};

/**
 * Properties to receive via API on BookAssignment creation
 */
export type BookAssignmentCreate = {
    book_id: number;
    school_id?: (string | null);
    teacher_id?: (string | null);
};

/**
 * Paginated list of book assignments
 */
export type BookAssignmentListResponse = {
    items: Array<BookAssignmentResponse>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * Properties to return via API
 */
export type BookAssignmentPublic = {
    id: string;
    book_id: number;
    school_id: (string | null);
    teacher_id: (string | null);
    assigned_by: string;
    assigned_at: string;
};

/**
 * Full book assignment response with related entity info
 */
export type BookAssignmentResponse = {
    id: string;
    book_id: number;
    book_title: string;
    book_cover_url?: (string | null);
    school_id: (string | null);
    school_name?: (string | null);
    teacher_id: (string | null);
    teacher_name?: (string | null);
    teacher_email?: (string | null);
    assigned_by: string;
    assigned_by_name?: (string | null);
    assigned_at: string;
};

/**
 * List of books response schema.
 */
export type BookListResponse = {
    items: Array<BookResponse>;
    total: number;
    skip?: number;
    limit?: number;
};

/**
 * Enhanced book pages response with activity coordinates for page viewer.
 */
export type BookPagesDetailResponse = {
    book_id: number;
    modules: Array<ModuleInfo>;
    pages: Array<PageDetail>;
    total_pages: number;
    total_activities: number;
};

/**
 * Response for book pages endpoint.
 */
export type BookPagesResponse = {
    book_id: number;
    modules: Array<ModulePages>;
    total_pages: number;
    total_activities: number;
};

/**
 * Book data for API responses - sourced from DCS.
 *
 * This schema represents books fetched from DCS without local sync.
 * The ID is the DCS book ID (integer).
 */
export type BookPublic = {
    id: number;
    name: string;
    title?: (string | null);
    publisher_id: number;
    publisher_name: string;
    cover_url?: (string | null);
    activity_count?: number;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * Book response schema for API.
 *
 * DEPRECATED: Use BookPublic instead. This schema is kept for backwards compatibility
 * but will be removed in a future version.
 */
export type BookResponse = {
    id: number;
    title?: (string | null);
    book_name?: (string | null);
    publisher_name: string;
    language?: (string | null);
    category?: (string | null);
    cover_image_url?: (string | null);
    activity_count?: number;
    dream_storage_id?: (string | null);
};

/**
 * Book structure response with modules and pages for activity selection tabs.
 */
export type BookStructureResponse = {
    book_id: number;
    modules: Array<ModuleWithActivities>;
    total_pages: number;
    total_activities: number;
};

/**
 * Book synchronization response schema.
 */
export type BookSyncResponse = {
    success: boolean;
    books_synced: number;
    books_created: number;
    books_updated: number;
    activities_created: number;
    errors: Array<(string)>;
    message?: string;
};

/**
 * Response for book videos endpoint.
 */
export type BookVideosResponse = {
    book_id: number;
    videos: Array<VideoInfo>;
    total_count: number;
};

/**
 * Individual assignment created in bulk operation.
 */
export type BulkAssignmentCreatedItem = {
    id: string;
    name: string;
    scheduled_publish_date: (string | null);
    due_date: (string | null);
    status: AssignmentPublishStatus;
    activity_count: number;
};

/**
 * Response schema for bulk assignment creation (Time Planning mode).
 */
export type BulkAssignmentCreateResponse = {
    success: boolean;
    message: string;
    total_created: number;
    assignments: Array<BulkAssignmentCreatedItem>;
};

/**
 * Properties for bulk book assignment creation
 */
export type BulkBookAssignmentCreate = {
    book_id: number;
    school_id: string;
    teacher_ids?: (Array<(string)> | null);
    assign_to_all_teachers?: boolean;
};

/**
 * Request body for bulk delete operations.
 */
export type BulkDeleteRequest = {
    ids: Array<(string)>;
};

/**
 * Response for bulk delete operations.
 */
export type BulkDeleteResponse = {
    deleted_count: number;
    failed_count: number;
    errors?: Array<(string)>;
};

/**
 * Details of a single bulk import validation error
 */
export type BulkImportErrorDetail = {
    row_number: number;
    field?: (string | null);
    message: string;
};

/**
 * Response schema for bulk import endpoints
 */
export type BulkImportResponse = {
    success: boolean;
    total_rows: number;
    created_count: number;
    error_count: number;
    errors: Array<BulkImportErrorDetail>;
    credentials?: (Array<{
    [key: string]: (string);
}> | null);
};

/**
 * Assignment item for calendar view.
 */
export type CalendarAssignmentItem = {
    id: string;
    name: string;
    due_date: (string | null);
    scheduled_publish_date: (string | null);
    status: AssignmentPublishStatus;
    activity_count: number;
    class_names?: Array<(string)>;
    book_id: string;
    book_title: string;
};

/**
 * Response schema for calendar assignments endpoint.
 */
export type CalendarAssignmentsResponse = {
    start_date: string;
    end_date: string;
    total_assignments: number;
    assignments_by_date: {
        [key: string]: Array<CalendarAssignmentItem>;
    };
};

/**
 * Request body for changing initial/temporary password
 */
export type ChangeInitialPasswordRequest = {
    current_password: string;
    new_password: string;
};

/**
 * Response for password change
 */
export type ChangePasswordResponse = {
    success: boolean;
    message: string;
};

/**
 * Complete class analytics data response.
 */
export type ClassAnalyticsResponse = {
    class_id: string;
    class_name: string;
    summary: ClassAnalyticsSummary;
    score_distribution: Array<ScoreDistributionBucket>;
    leaderboard: Array<StudentLeaderboardItem>;
    struggling_students: Array<StrugglingStudentItem>;
    assignment_performance: Array<AssignmentPerformanceItem>;
    activity_type_performance: Array<ActivityTypePerformanceItem>;
    trends: Array<TrendData>;
};

/**
 * Aggregated summary metrics for a class.
 */
export type ClassAnalyticsSummary = {
    avg_score: number;
    completion_rate: number;
    total_assignments: number;
    active_students: number;
};

/**
 * Complete benchmark comparison response for a class.
 *
 * [Source: Story 5.7 AC: 2, 3, 5, 7, 10, 11]
 */
export type ClassBenchmarkResponse = {
    class_metrics: ClassMetrics;
    /**
     * None if disabled or threshold not met
     */
    school_benchmark?: (BenchmarkData | null);
    /**
     * None if disabled or threshold not met
     */
    publisher_benchmark?: (BenchmarkData | null);
    activity_benchmarks?: Array<ActivityTypeBenchmark>;
    comparison_over_time?: Array<BenchmarkTrendPoint>;
    message?: (BenchmarkMessage | null);
    benchmarking_enabled?: boolean;
    disabled_reason?: (string | null);
};

/**
 * Properties to receive via API on Class creation by Teacher (teacher_id and school_id set automatically from teacher's record)
 */
export type ClassCreateByTeacher = {
    name: string;
    grade_level?: (string | null);
    subject?: (string | null);
    academic_year?: (string | null);
    is_active?: boolean;
};

/**
 * Class detail response with enrolled students
 */
export type ClassDetailResponse = {
    name: string;
    grade_level?: (string | null);
    subject?: (string | null);
    academic_year?: (string | null);
    is_active?: boolean;
    id: string;
    teacher_id: string;
    school_id: string;
    created_at: string;
    updated_at: string;
    /**
     * Number of enrolled students
     */
    student_count?: number;
    enrolled_students?: Array<StudentInClass>;
};

/**
 * Current class performance metrics.
 *
 * [Source: Story 5.7 AC: 2]
 */
export type ClassMetrics = {
    class_id: string;
    class_name: string;
    average_score: number;
    completion_rate: number;
    total_assignments: number;
    active_students: number;
};

/**
 * Properties to return via API
 */
export type ClassPublic = {
    name: string;
    grade_level?: (string | null);
    subject?: (string | null);
    academic_year?: (string | null);
    is_active?: boolean;
    id: string;
    teacher_id: string;
    school_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Class response with computed student count
 */
export type ClassResponse = {
    name: string;
    grade_level?: (string | null);
    subject?: (string | null);
    academic_year?: (string | null);
    is_active?: boolean;
    id: string;
    teacher_id: string;
    school_id: string;
    created_at: string;
    updated_at: string;
    /**
     * Number of enrolled students
     */
    student_count?: number;
};

/**
 * Schema for adding students to a class
 */
export type ClassStudentAdd = {
    /**
     * List of student UUIDs to add to the class
     */
    student_ids: Array<(string)>;
};

/**
 * Properties to receive via API on Class update
 */
export type ClassUpdate = {
    name?: (string | null);
    grade_level?: (string | null);
    subject?: (string | null);
    academic_year?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Completion status counts for an assignment.
 */
export type CompletionOverview = {
    completed: number;
    in_progress: number;
    not_started: number;
    past_due: number;
    total: number;
};

/**
 * Schema for paginated conversation list response.
 */
export type ConversationListResponse = {
    conversations: Array<ConversationPublic>;
    total: number;
    limit: number;
    offset: number;
    has_more: boolean;
    total_unread: number;
};

/**
 * Schema for a conversation (grouped messages with a participant).
 */
export type ConversationPublic = {
    participant_id: string;
    participant_name: string;
    participant_email: string;
    participant_role: string;
    last_message_preview: string;
    last_message_timestamp: string;
    unread_count: number;
};

/**
 * Request body for credentials download.
 */
export type CredentialsDownloadRequest = {
    /**
     * Credentials to include in download
     */
    credentials: Array<ImportCredential>;
};

/**
 * Dashboard statistics for admin view
 */
export type DashboardStats = {
    total_users: number;
    total_publishers: number;
    total_teachers: number;
    total_students: number;
    active_schools: number;
};

/**
 * Schema for a date group in Time Planning mode.
 *
 * Each date group creates a separate assignment with its own publish date.
 */
export type DateGroupCreate = {
    scheduled_publish_date: string;
    due_date?: (string | null);
    time_limit_minutes?: (number | null);
    activity_ids: Array<(string)>;
};

/**
 * Response model for deadline check tasks.
 */
export type DeadlineCheckResponse = {
    success: boolean;
    deadline_reminders_sent: number;
    deadline_students_notified: number;
    deadline_assignments_processed: number;
    past_due_notifications_sent: number;
    past_due_students_notified: number;
    past_due_assignments_processed: number;
    message: string;
};

/**
 * Type definition for emoji reaction information.
 */
export type EmojiInfo = {
    slug: string;
    emoji: string;
};

/**
 * Schema for creating feedback on a student assignment.
 */
export type FeedbackCreate = {
    feedback_text: string;
    is_draft?: boolean;
    badges?: (Array<(string)> | null);
    emoji_reaction?: (string | null);
};

/**
 * Response schema for available feedback options (badges and emoji).
 */
export type FeedbackOptionsResponse = {
    badges: Array<BadgeInfo>;
    emoji_reactions: Array<EmojiInfo>;
};

/**
 * Schema for feedback API response with related entity names.
 */
export type FeedbackPublic = {
    id: string;
    assignment_student_id: string;
    teacher_id: string;
    feedback_text: (string | null);
    badges: Array<(string)>;
    emoji_reactions: Array<(string)>;
    is_draft: boolean;
    created_at: string;
    updated_at: string;
    assignment_id: string;
    assignment_name: string;
    student_id: string;
    student_name: string;
    student_user_id: string;
    teacher_name: string;
    teacher_user_id: string;
    score: (number | null);
};

/**
 * Schema for feedback as viewed by a student (hides draft status).
 */
export type FeedbackStudentView = {
    id: string;
    feedback_text: (string | null);
    badges: Array<(string)>;
    emoji_reactions: Array<(string)>;
    created_at: string;
    updated_at: string;
    teacher_name: string;
    teacher_user_id: string;
    assignment_name: string;
    assignment_id: string;
};

/**
 * Schema for updating feedback.
 */
export type FeedbackUpdate = {
    feedback_text?: (string | null);
    is_draft?: (boolean | null);
    badges?: (Array<(string)> | null);
    emoji_reaction?: (string | null);
};

/**
 * Analysis for a fill-in-blank item.
 */
export type FillInBlankAnalysis = {
    blank_id: string;
    blank_context: string;
    correct_answer: string;
    correct_rate: number;
    common_wrong_answers: Array<(string)>;
};

/**
 * Request schema for setting global mute.
 */
export type GlobalMuteRequest = {
    /**
     * Number of hours to mute (max 24)
     */
    hours: number;
};

/**
 * Response schema for global mute status.
 */
export type GlobalMuteResponse = {
    muted_until: string;
    /**
     * Hours remaining until mute expires
     */
    remaining_hours: number;
};

/**
 * Response for mute status check.
 */
export type GlobalMuteStatusResponse = {
    is_muted: boolean;
    mute?: (GlobalMuteResponse | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Credentials for a single imported student.
 */
export type ImportCredential = {
    /**
     * Student's full name
     */
    full_name: string;
    /**
     * Generated username
     */
    username: string;
    /**
     * Generated password
     */
    password: string;
    /**
     * Student email if provided
     */
    email?: (string | null);
};

/**
 * Response from import execution endpoint.
 */
export type ImportExecutionResponse = {
    /**
     * Number of students created
     */
    created_count: number;
    /**
     * Number of failed creations
     */
    failed_count: number;
    /**
     * Credentials for created students
     */
    credentials: Array<ImportCredential>;
    /**
     * Errors during creation
     */
    errors?: Array<(string)>;
};

/**
 * Validation result for a single row.
 */
export type ImportRowResult = {
    /**
     * Excel row number (1-indexed, row 1 is header)
     */
    row_number: number;
    /**
     * Full name from the row
     */
    full_name: string;
    /**
     * Generated or provided username
     */
    username: string;
    /**
     * Email if provided
     */
    email?: (string | null);
    /**
     * Grade level if provided
     */
    grade?: (string | null);
    /**
     * Class/section if provided
     */
    class_name?: (string | null);
    /**
     * Validation status
     */
    status: ImportRowStatus;
    /**
     * List of errors
     */
    errors?: Array<(string)>;
    /**
     * List of warnings
     */
    warnings?: Array<(string)>;
};

/**
 * Status of a single import row.
 */
export type ImportRowStatus = 'valid' | 'warning' | 'error';

/**
 * Response from import validation endpoint.
 */
export type ImportValidationResponse = {
    /**
     * Number of valid rows
     */
    valid_count: number;
    /**
     * Number of rows with warnings
     */
    warning_count: number;
    /**
     * Number of rows with errors
     */
    error_count: number;
    /**
     * Total number of data rows
     */
    total_count: number;
    /**
     * Validation result for each row
     */
    rows: Array<ImportRowResult>;
};

/**
 * Trend of student improvement.
 */
export type ImprovementTrend = 'improving' | 'stable' | 'declining';

/**
 * Summary card for a detected insight.
 */
export type InsightCard = {
    id: string;
    type: InsightType;
    severity: InsightSeverity;
    title: string;
    description: string;
    affected_count: number;
    recommended_action: string;
    created_at: string;
};

/**
 * Detailed view of an insight with affected items.
 */
export type InsightDetail = {
    insight: InsightCard;
    affected_students: Array<AffectedStudent>;
    related_assignments: Array<RelatedAssignment>;
    related_questions?: (Array<RelatedQuestion> | null);
};

/**
 * Severity levels for insights.
 */
export type InsightSeverity = 'moderate' | 'critical';

/**
 * Types of teacher insights.
 */
export type InsightType = 'struggling_topic' | 'common_misconception' | 'time_management' | 'review_recommended' | 'struggling_students' | 'activity_type_struggle';

/**
 * Response for logo upload
 */
export type LogoUploadResponse = {
    logo_url: string;
    message?: string;
};

/**
 * Schema for mark all as read response.
 */
export type MarkAllReadResponse = {
    marked_count: number;
};

/**
 * List of materials with quota info.
 */
export type MaterialListResponse = {
    materials: Array<MaterialResponse>;
    total_count: number;
    quota: StorageQuotaResponse;
};

/**
 * Material response schema.
 */
export type MaterialResponse = {
    id: string;
    name: string;
    type: MaterialType;
    file_size?: (number | null);
    mime_type?: (string | null);
    original_filename?: (string | null);
    url?: (string | null);
    text_content?: (string | null);
    created_at: string;
    updated_at: string;
    download_url?: (string | null);
};

/**
 * Types of teacher materials
 */
export type MaterialType = 'document' | 'image' | 'audio' | 'video' | 'url' | 'text_note';

/**
 * Update material metadata (name only).
 */
export type MaterialUpdate = {
    name: string;
};

export type Message = {
    message: string;
};

/**
 * Schema for creating a new message.
 */
export type MessageCreate = {
    recipient_id: string;
    subject?: (string | null);
    body: string;
    parent_message_id?: (string | null);
};

/**
 * Schema for message API response with sender/recipient names.
 */
export type MessagePublic = {
    id: string;
    sender_id: string;
    sender_name: string;
    sender_email: string;
    recipient_id: string;
    recipient_name: string;
    recipient_email: string;
    subject: (string | null);
    body: string;
    parent_message_id: (string | null);
    is_read: boolean;
    sent_at: string;
};

/**
 * Schema for message read status update response.
 */
export type MessageReadResponse = {
    id: string;
    is_read: boolean;
};

/**
 * Schema for message thread response.
 */
export type MessageThreadResponse = {
    participant_id: string;
    participant_name: string;
    participant_email: string;
    participant_role: string;
    messages: Array<MessagePublic>;
    total_messages: number;
};

/**
 * Module metadata for navigation shortcuts.
 */
export type ModuleInfo = {
    name: string;
    first_page_index: number;
    page_count: number;
};

/**
 * A module with its pages containing activities.
 */
export type ModulePages = {
    name: string;
    pages: Array<PageInfo>;
};

/**
 * Module information with pages and activity IDs for bulk selection.
 */
export type ModuleWithActivities = {
    name: string;
    page_start: number;
    page_end: number;
    activity_count: number;
    activity_ids: Array<(string)>;
    pages: Array<PageWithActivities>;
};

/**
 * A question that was frequently missed.
 */
export type MostMissedQuestion = {
    question_id: string;
    question_text: string;
    correct_percentage: number;
    common_wrong_answer: (string | null);
};

/**
 * Response schema for multi-activity assignment analytics (teacher view).
 */
export type MultiActivityAnalyticsResponse = {
    assignment_id: string;
    assignment_name: string;
    total_students: number;
    submitted_count: number;
    activities: Array<ActivityAnalyticsItem>;
    expanded_students?: (Array<StudentActivityScore> | null);
};

/**
 * Response schema for starting a multi-activity assignment.
 */
export type MultiActivityStartResponse = {
    assignment_id: string;
    assignment_name: string;
    instructions: (string | null);
    due_date: (string | null);
    time_limit_minutes: (number | null);
    book_id: string;
    book_title: string;
    book_name: string;
    publisher_name: string;
    book_cover_url: (string | null);
    activities: Array<ActivityWithConfig>;
    activity_progress: Array<ActivityProgressInfo>;
    total_activities: number;
    current_status: string;
    time_spent_minutes: number;
    started_at: (string | null);
    video_path?: (string | null);
    resources?: (AdditionalResourcesResponse | null);
    /**
     * Count of completed activities.
     */
    readonly completed_activities_count: number;
    /**
     * Check if all activities are completed.
     */
    readonly all_activities_completed: boolean;
};

/**
 * Request schema for submitting a multi-activity assignment.
 */
export type MultiActivitySubmitRequest = {
    force_submit?: boolean;
    total_time_spent_minutes?: number;
};

/**
 * Response schema for multi-activity assignment submission.
 */
export type MultiActivitySubmitResponse = {
    success: boolean;
    message: string;
    assignment_id: string;
    combined_score: number;
    per_activity_scores: Array<PerActivityScore>;
    completed_at: string;
    total_activities: number;
    completed_activities: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Schema for paginated notification list response.
 */
export type NotificationListResponse = {
    notifications: Array<NotificationResponse>;
    total: number;
    limit: number;
    offset: number;
    has_more: boolean;
};

/**
 * Response schema for a single notification preference.
 */
export type NotificationPreferenceResponse = {
    notification_type: app__models__NotificationType;
    enabled: boolean;
    email_enabled: boolean;
    label: string;
    description: string;
};

/**
 * Schema for bulk updating preferences.
 *
 * Keys are notification type names, values are enabled status.
 * Example: {"assignment_created": true, "deadline_approaching": false}
 */
export type NotificationPreferencesBulkUpdate = {
    /**
     * Map of notification type to enabled status
     */
    preferences: {
        [key: string]: (boolean);
    };
};

/**
 * Response for bulk preference update.
 */
export type NotificationPreferencesBulkUpdateResponse = {
    updated: Array<(string)>;
    preferences: Array<NotificationPreferenceResponse>;
};

/**
 * Response schema for all user notification preferences.
 */
export type NotificationPreferencesListResponse = {
    preferences: Array<NotificationPreferenceResponse>;
    global_mute?: (GlobalMuteResponse | null);
};

/**
 * Schema for updating a single preference.
 */
export type NotificationPreferenceUpdate = {
    enabled: boolean;
};

/**
 * Schema for notification API response.
 */
export type NotificationResponse = {
    id: string;
    user_id: string;
    type: app__schemas__notification__NotificationType;
    title: string;
    message: string;
    link: (string | null);
    is_read: boolean;
    created_at: string;
};

/**
 * Notification type enumeration
 */
export type NotificationType_Input = 'assignment_created' | 'deadline_approaching' | 'feedback_received' | 'message_received' | 'student_completed' | 'past_due' | 'material_shared' | 'system_announcement' | 'password_reset';

/**
 * Activity response for page-based selection.
 */
export type PageActivityResponse = {
    id: string;
    title: (string | null);
    activity_type: string;
    section_index: number;
    order_index: number;
};

/**
 * Detailed page information including image and activity markers.
 */
export type PageDetail = {
    page_number: number;
    image_url: string;
    module_name: string;
    activities: Array<ActivityMarker>;
};

/**
 * Information about a single page in a book module.
 */
export type PageInfo = {
    page_number: number;
    activity_count: number;
    thumbnail_url: string;
};

/**
 * Page information with activity IDs for bulk selection.
 */
export type PageWithActivities = {
    page_number: number;
    thumbnail_url: string;
    activity_count: number;
    activity_ids: Array<(string)>;
};

/**
 * Response schema for password reset endpoint - secure version (Story 11.2)
 *
 * Never contains the actual password unless user has no email address.
 */
export type PasswordResetResponse = {
    success: boolean;
    message: string;
    password_emailed: boolean;
    temporary_password?: (string | null);
};

/**
 * Per-activity score info for submission response.
 */
export type PerActivityScore = {
    activity_id: string;
    activity_title: (string | null);
    score: (number | null);
    max_score: number;
    status: string;
};

/**
 * Single data point in performance trend chart.
 */
export type PerformanceTrendPoint = {
    date: string;
    score: number;
};

/**
 * Predefined avatar response model.
 */
export type PredefinedAvatar = {
    id: string;
    name: string;
    url: string;
};

/**
 * Response containing all predefined avatars.
 */
export type PredefinedAvatarsResponse = {
    avatars: Array<PredefinedAvatar>;
};

/**
 * Presigned URL for direct file access.
 */
export type PresignedUrlResponse = {
    url: string;
    expires_in_seconds: number;
    content_type?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Recent assignment for student progress view.
 */
export type ProgressRecentAssignment = {
    id: string;
    name: string;
    score: number;
    completed_at: string;
    has_feedback: boolean;
    activity_type: string;
    book_title: string;
};

/**
 * Response model for publish scheduled assignments task.
 */
export type PublishAssignmentsResponse = {
    success: boolean;
    assignments_published: number;
    notifications_sent: number;
    students_notified: number;
    message: string;
};

/**
 * Create a publisher user account linked to a DCS publisher.
 */
export type PublisherAccountCreate = {
    /**
     * DCS Publisher ID to link
     */
    dcs_publisher_id: number;
    /**
     * Username (auto-generated from full_name if not provided)
     */
    username?: (string | null);
    email: string;
    full_name: string;
};

/**
 * Response for creating a publisher user account.
 *
 * Different from UserCreationResponse because publishers don't have a role_record.
 */
export type PublisherAccountCreationResponse = {
    user: UserPublic;
    temporary_password?: (string | null);
    password_emailed?: boolean;
    message?: string;
};

/**
 * Response for listing publisher accounts.
 */
export type PublisherAccountListResponse = {
    data: Array<PublisherAccountPublic>;
    count: number;
};

/**
 * Publisher account response with DCS enrichment.
 */
export type PublisherAccountPublic = {
    id: string;
    username: string;
    email: (string | null);
    full_name: (string | null);
    dcs_publisher_id: (number | null);
    dcs_publisher_name?: (string | null);
    is_active: boolean;
    created_at?: (string | null);
};

/**
 * Update a publisher user account.
 */
export type PublisherAccountUpdate = {
    dcs_publisher_id?: (number | null);
    username?: (string | null);
    email?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Publisher profile combining DCS and LMS data.
 */
export type PublisherProfile = {
    id: number;
    name: string;
    contact_email?: (string | null);
    logo_url?: (string | null);
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
};

/**
 * Publisher data for API responses - sourced from DCS.
 */
export type PublisherPublic = {
    id: number;
    name: string;
    contact_email?: (string | null);
    logo_url?: (string | null);
};

/**
 * Publisher organization statistics.
 */
export type PublisherStats = {
    schools_count: number;
    teachers_count: number;
    books_count: number;
};

/**
 * Analysis of a single question/item.
 */
export type QuestionAnalysis = {
    question_id: string;
    question_text: string;
    correct_percentage: number;
    total_responses: number;
    answer_distribution: Array<AnswerDistributionItem>;
};

/**
 * Single recent assignment completion.
 */
export type RecentActivityItem = {
    assignment_id: string;
    assignment_name: string;
    score: number;
    completed_at: string;
    time_spent_minutes: number;
};

/**
 * Schema for list of allowed recipients.
 */
export type RecipientListResponse = {
    recipients: Array<RecipientPublic>;
    total: number;
};

/**
 * Schema for an allowed recipient.
 */
export type RecipientPublic = {
    user_id: string;
    name: string;
    email: string;
    role: string;
};

/**
 * Assignment related to an insight.
 */
export type RelatedAssignment = {
    assignment_id: string;
    name: string;
    avg_score: number;
    completion_rate: number;
};

/**
 * Question related to an insight (for misconceptions).
 */
export type RelatedQuestion = {
    question_id: string;
    question_text: string;
    incorrect_percentage: number;
    common_wrong_answer: (string | null);
};

/**
 * Output format for generated reports.
 */
export type ReportFormat = 'pdf' | 'excel';

/**
 * Request to generate a new report.
 */
export type ReportGenerateRequest = {
    report_type: ReportType;
    period: ReportPeriod;
    /**
     * ISO date for custom period start (YYYY-MM-DD)
     */
    start_date?: (string | null);
    /**
     * ISO date for custom period end (YYYY-MM-DD)
     */
    end_date?: (string | null);
    /**
     * UUID of target (student, class, or None for assignment)
     */
    target_id: string;
    format: ReportFormat;
    /**
     * Optional predefined template to use
     */
    template_type?: (ReportTemplateType | null);
};

/**
 * A previously generated report in history.
 */
export type ReportHistoryItem = {
    id: string;
    job_id: string;
    report_type: ReportType;
    template_type: (ReportTemplateType | null);
    format: ReportFormat;
    target_name: string;
    created_at: string;
    expires_at: string;
    download_url?: (string | null);
    is_expired?: boolean;
};

/**
 * Response containing report history list.
 */
export type ReportHistoryResponse = {
    reports: Array<ReportHistoryItem>;
};

/**
 * Response after initiating report generation.
 */
export type ReportJobResponse = {
    job_id: string;
    status: ReportJobStatus;
    created_at: string;
    estimated_completion?: (string | null);
};

/**
 * Status of a report generation job.
 */
export type ReportJobStatus = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * Time period for report data.
 */
export type ReportPeriod = 'week' | 'month' | 'semester' | 'custom';

/**
 * Response for checking report job status.
 */
export type ReportStatusResponse = {
    job_id: string;
    status: ReportJobStatus;
    progress_percentage: number;
    download_url?: (string | null);
    error_message?: (string | null);
};

/**
 * Predefined report template types.
 */
export type ReportTemplateType = 'weekly_class_summary' | 'student_progress_report' | 'monthly_assignment_overview' | 'parent_teacher_conference';

/**
 * Type of report to generate.
 */
export type ReportType = 'student' | 'class' | 'assignment';

/**
 * A saved report configuration template.
 */
export type SavedReportTemplate = {
    id: string;
    name: string;
    config: ReportGenerateRequest;
    created_at: string;
};

/**
 * Request to save a report configuration as a template.
 */
export type SavedReportTemplateCreate = {
    name: string;
    config: ReportGenerateRequest;
};

/**
 * Summary of a school's benchmark status for admin view.
 *
 * [Source: Story 5.7 AC: 12]
 */
export type SchoolBenchmarkSummary = {
    school_id: string;
    school_name: string;
    benchmarking_enabled: boolean;
    class_count: number;
    average_score?: (number | null);
    performance_status?: ('above_average' | 'average' | 'below_average' | null);
};

/**
 * Properties to receive via API on School creation
 */
export type SchoolCreate = {
    name: string;
    address?: (string | null);
    contact_info?: (string | null);
    /**
     * Enable performance benchmarking for this school
     */
    benchmarking_enabled?: boolean;
    dcs_publisher_id: number;
};

/**
 * Properties to receive via API on School creation by Publisher (publisher_id set automatically)
 */
export type SchoolCreateByPublisher = {
    name: string;
    address?: (string | null);
    contact_info?: (string | null);
    /**
     * Enable performance benchmarking for this school
     */
    benchmarking_enabled?: boolean;
};

/**
 * Properties to return via API
 */
export type SchoolPublic = {
    name: string;
    address?: (string | null);
    contact_info?: (string | null);
    /**
     * Enable performance benchmarking for this school
     */
    benchmarking_enabled?: boolean;
    id: string;
    dcs_publisher_id: number;
    created_at: string;
    updated_at: string;
};

/**
 * Properties to receive via API on School update
 */
export type SchoolUpdate = {
    name?: (string | null);
    address?: (string | null);
    contact_info?: (string | null);
    dcs_publisher_id?: (number | null);
    benchmarking_enabled?: (boolean | null);
};

/**
 * School response with aggregated counts for publisher views.
 */
export type SchoolWithCounts = {
    id: string;
    name: string;
    address?: (string | null);
    contact_info?: (string | null);
    benchmarking_enabled?: boolean;
    dcs_publisher_id: number;
    created_at: string;
    updated_at: string;
    teacher_count?: number;
    student_count?: number;
    book_count?: number;
};

/**
 * Single bucket in score distribution histogram.
 */
export type ScoreDistributionBucket = {
    range_label: string;
    min_score: number;
    max_score: number;
    count: number;
};

/**
 * Score statistics for an assignment.
 */
export type ScoreStatistics = {
    avg_score: number;
    median_score: number;
    highest_score: number;
    lowest_score: number;
};

/**
 * Data point for score trend chart.
 */
export type ScoreTrendPoint = {
    date: string;
    score: number;
    assignment_name: string;
};

/**
 * Request to select a predefined avatar.
 */
export type SelectAvatarRequest = {
    avatar_id: string;
};

/**
 * Counts of assignments by status.
 */
export type StatusSummary = {
    not_started: number;
    in_progress: number;
    completed: number;
    past_due: number;
};

/**
 * Storage quota information.
 */
export type StorageQuotaResponse = {
    used_bytes: number;
    quota_bytes: number;
    used_percentage: number;
    is_warning: boolean;
    is_full: boolean;
};

/**
 * Student flagged as struggling.
 */
export type StrugglingStudentItem = {
    student_id: string;
    name: string;
    avg_score: number;
    past_due_count: number;
    alert_reason: string;
};

/**
 * Per-student score for a specific activity (used in expanded analytics view).
 */
export type StudentActivityScore = {
    student_id: string;
    student_name: string;
    status: string;
    score: (number | null);
    max_score: number;
    time_spent_seconds: number;
    completed_at: (string | null);
};

/**
 * Complete student analytics data response.
 */
export type StudentAnalyticsResponse = {
    student: StudentInfo;
    summary: AnalyticsSummary;
    recent_activity: Array<RecentActivityItem>;
    performance_trend: Array<PerformanceTrendPoint>;
    activity_breakdown: Array<ActivityBreakdownItem>;
    status_summary: StatusSummary;
    time_analytics: TimeAnalytics;
};

/**
 * Individual student's full answers for an assignment.
 */
export type StudentAnswersResponse = {
    student_id: string;
    name: string;
    status: string;
    score: (number | null);
    time_spent_minutes: number;
    started_at: (string | null);
    completed_at: (string | null);
    answers_json: ({
    [key: string]: unknown;
} | null);
};

/**
 * Student-facing assignment response with enriched data.
 */
export type StudentAssignmentResponse = {
    assignment_id: string;
    assignment_name: string;
    instructions: (string | null);
    due_date: (string | null);
    time_limit_minutes: (number | null);
    created_at: string;
    book_id: string;
    book_title: string;
    book_cover_url: (string | null);
    activity_id: string;
    activity_title: string;
    activity_type: string;
    status: string;
    score: (number | null);
    started_at: (string | null);
    completed_at: (string | null);
    time_spent_minutes: number;
    activity_count?: number;
    /**
     * Calculate if assignment is past due.
     */
    readonly is_past_due: boolean;
    /**
     * Calculate days until due date.
     */
    readonly days_until_due: (number | null);
};

/**
 * Response schema for student viewing their completed assignment results.
 */
export type StudentAssignmentResultResponse = {
    assignment_id: string;
    assignment_name: string;
    total_score: (number | null);
    completed_at: (string | null);
    activity_scores: Array<ActivityScoreItem>;
    total_activities: number;
    completed_activities: number;
};

/**
 * Response schema for student badge counts (Story 6.5, AC: 9, 14).
 */
export type StudentBadgeCountsResponse = {
    badge_counts: {
        [key: string]: (number);
    };
    total: number;
    this_month: {
        [key: string]: (number);
    };
    this_month_total: number;
};

/**
 * Assignment item for student calendar view.
 */
export type StudentCalendarAssignmentItem = {
    id: string;
    name: string;
    due_date: (string | null);
    book_id: string;
    book_title: string;
    book_cover_url: (string | null);
    activity_count: number;
    status: string;
};

/**
 * Response schema for student calendar assignments endpoint.
 */
export type StudentCalendarAssignmentsResponse = {
    start_date: string;
    end_date: string;
    total_assignments: number;
    assignments_by_date: {
        [key: string]: Array<StudentCalendarAssignmentItem>;
    };
};

/**
 * Properties for API endpoint student creation (includes user creation)
 */
export type StudentCreateAPI = {
    username: string;
    user_email?: (string | null);
    full_name: string;
    grade_level?: (string | null);
    parent_email?: (string | null);
};

/**
 * Student info for class detail response
 */
export type StudentInClass = {
    id: string;
    email: string;
    full_name: string;
    grade?: (string | null);
};

/**
 * Basic student information for analytics display.
 */
export type StudentInfo = {
    id: string;
    name: string;
    photo_url?: (string | null);
};

/**
 * Student entry in leaderboard.
 */
export type StudentLeaderboardItem = {
    student_id: string;
    name: string;
    avg_score: number;
    rank: number;
};

/**
 * Complete student progress response.
 */
export type StudentProgressResponse = {
    stats: StudentProgressStats;
    score_trend: Array<ScoreTrendPoint>;
    activity_breakdown: Array<ActivityTypeScore>;
    recent_assignments: Array<ProgressRecentAssignment>;
    achievements: Array<Achievement>;
    study_time: StudyTimeStats;
    improvement_tips: Array<(string)>;
};

/**
 * Overall student progress statistics.
 */
export type StudentProgressStats = {
    total_completed: number;
    avg_score: number;
    current_streak: number;
    streak_start_date: (string | null);
    improvement_trend: ImprovementTrend;
};

/**
 * Properties to return via API
 */
export type StudentPublic = {
    grade_level?: (string | null);
    parent_email?: (string | null);
    id: string;
    user_id: string;
    user_email?: (string | null);
    user_username: string;
    user_full_name: string;
    created_by_teacher_id?: (string | null);
    created_by_teacher_name?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Individual student's result for an assignment.
 */
export type StudentResultItem = {
    student_id: string;
    name: string;
    status: string;
    score: (number | null);
    time_spent_minutes: number;
    completed_at: (string | null);
    has_feedback?: boolean;
};

/**
 * Properties to receive via API on Student update
 */
export type StudentUpdate = {
    user_email?: (string | null);
    user_username?: (string | null);
    user_full_name?: (string | null);
    grade_level?: (string | null);
    parent_email?: (string | null);
};

/**
 * Study time statistics.
 */
export type StudyTimeStats = {
    this_week_minutes: number;
    this_month_minutes: number;
    avg_per_assignment: number;
};

/**
 * Properties for API endpoint supervisor creation
 */
export type SupervisorCreateAPI = {
    username: string;
    user_email?: (string | null);
    full_name: string;
};

/**
 * Response schema for supervisor creation
 */
export type SupervisorCreateResponse = {
    user: UserPublic;
    temporary_password?: (string | null);
    password_emailed?: boolean;
    message?: string;
};

/**
 * Public supervisor response schema
 */
export type SupervisorPublic = {
    id: string;
    full_name: (string | null);
    email: (string | null);
    username: string;
    is_active: boolean;
    created_at: (string | null);
    must_change_password: boolean;
};

/**
 * Properties for updating a supervisor
 */
export type SupervisorUpdate = {
    full_name?: (string | null);
    email?: (string | null);
    username?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Properties for API endpoint teacher creation (includes user creation)
 */
export type TeacherCreateAPI = {
    username: string;
    user_email: string;
    full_name: string;
    school_id: string;
    subject_specialization?: (string | null);
};

/**
 * Response containing all teacher insights.
 */
export type TeacherInsightsResponse = {
    insights: Array<InsightCard>;
    last_refreshed: string;
};

/**
 * Schema for a teacher-uploaded material attached to an assignment.
 *
 * Story 13.3: Teacher Materials Assignment Integration.
 * Stores denormalized name/type for display even if material is deleted.
 */
export type TeacherMaterialResource = {
    type?: "teacher_material";
    material_id: string;
    name: string;
    material_type: string;
};

/**
 * Response schema with availability status and enriched data.
 *
 * Used when returning assignment resources to include current material state.
 */
export type TeacherMaterialResourceResponse = {
    type?: "teacher_material";
    material_id: string;
    name: string;
    material_type: string;
    is_available?: boolean;
    file_size?: (number | null);
    mime_type?: (string | null);
    url?: (string | null);
    text_content?: (string | null);
    download_url?: (string | null);
};

/**
 * Properties to return via API
 */
export type TeacherPublic = {
    subject_specialization?: (string | null);
    id: string;
    user_id: string;
    user_email: string;
    user_username: string;
    user_full_name: string;
    school_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Properties to receive via API on Teacher update
 */
export type TeacherUpdate = {
    school_id?: (string | null);
    subject_specialization?: (string | null);
    user_email?: (string | null);
    user_username?: (string | null);
    user_full_name?: (string | null);
};

/**
 * Teacher response with aggregated counts and school name for publisher views.
 */
export type TeacherWithCounts = {
    id: string;
    user_id: string;
    user_email: string;
    user_username: string;
    user_full_name: string;
    school_id: string;
    school_name?: (string | null);
    subject_specialization?: (string | null);
    created_at: string;
    updated_at: string;
    books_assigned?: number;
    classroom_count?: number;
};

/**
 * Create a text note.
 */
export type TextNoteCreate = {
    name: string;
    content: string;
};

/**
 * Update a text note.
 */
export type TextNoteUpdate = {
    name?: (string | null);
    content?: (string | null);
};

/**
 * Time-based performance metrics.
 */
export type TimeAnalytics = {
    avg_time_per_assignment: number;
    total_time_this_week: number;
    total_time_this_month: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
    must_change_password?: boolean;
    has_completed_tour?: boolean;
};

/**
 * Trend analysis for a metric.
 */
export type TrendData = {
    metric_name: string;
    current_value: number;
    previous_value: number;
    change_percent: number;
    trend: 'up' | 'down' | 'stable';
};

export type trend = 'up' | 'down' | 'stable';

/**
 * Schema for unread notification count response.
 */
export type UnreadCountResponse = {
    count: number;
};

/**
 * Schema for unread messages count response.
 */
export type UnreadMessagesCountResponse = {
    count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Response after file upload.
 */
export type UploadResponse = {
    material: MaterialResponse;
    quota: StorageQuotaResponse;
};

/**
 * Create a URL link.
 */
export type UrlLinkCreate = {
    name: string;
    url: string;
};

export type UserCreate = {
    email?: (string | null);
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    /**
     * DCS Publisher ID - only set for publisher role users
     */
    dcs_publisher_id?: (number | null);
    password: string;
};

/**
 * Response schema for role-specific user creation endpoints.
 *
 * Security: temporary_password is only included when user has no email.
 * When user has email, password_emailed=True and temporary_password is None.
 */
export type UserCreationResponse = {
    user: UserPublic;
    role_record: (TeacherPublic | StudentPublic);
    temporary_password?: (string | null);
    password_emailed?: boolean;
    message?: string;
};

export type UserPublic = {
    email?: (string | null);
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    /**
     * DCS Publisher ID - only set for publisher role users
     */
    dcs_publisher_id?: (number | null);
    id: string;
    must_change_password?: boolean;
    has_completed_tour?: boolean;
    avatar_url?: (string | null);
    avatar_type?: (AvatarType | null);
};

/**
 * User role enumeration for RBAC
 */
export type UserRole = 'admin' | 'supervisor' | 'publisher' | 'teacher' | 'student';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    dcs_publisher_id?: (number | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    username?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Video file information from Dream Central Storage.
 */
export type VideoInfo = {
    path: string;
    name: string;
    size_bytes: number;
    has_subtitles: boolean;
};

/**
 * Schema for a video resource attached to an assignment.
 *
 * Story 10.3+: Video with subtitle control for students.
 */
export type VideoResource = {
    type?: "video";
    path: string;
    name: string;
    subtitles_enabled?: boolean;
    has_subtitles?: boolean;
};

/**
 * Webhook event type enumeration
 */
export type WebhookEventType = 'book.created' | 'book.updated' | 'book.deleted' | 'publisher.created' | 'publisher.updated' | 'publisher.deleted';

/**
 * Webhook payload schema from Dream Central Storage.
 *
 * Supports both book and publisher events. The data field structure
 * depends on the event type:
 * - book.* events: data contains WebhookBookData fields
 * - publisher.* events: data contains WebhookPublisherData fields
 */
export type WebhookPayload = {
    event: WebhookEventType;
    timestamp: string;
    data: {
        [key: string]: unknown;
    };
};

/**
 * Common incorrect word pair mappings.
 */
export type WordMatchingError = {
    word: string;
    correct_match: string;
    common_incorrect_match: string;
    error_count: number;
};

/**
 * Analysis for word search activity.
 */
export type WordSearchAnalysis = {
    word: string;
    find_rate: number;
    found_count: number;
    total_attempts: number;
};

export type AdminListPublishersResponse = (Array<PublisherPublic>);

export type AdminCreateSchoolData = {
    requestBody: SchoolCreate;
};

export type AdminCreateSchoolResponse = (SchoolPublic);

export type AdminListSchoolsData = {
    limit?: number;
    publisherId?: (string | null);
    skip?: number;
};

export type AdminListSchoolsResponse = (Array<SchoolPublic>);

export type AdminUpdatePublisherData = {
    publisherId: number;
};

export type AdminDeletePublisherData = {
    publisherId: number;
};

export type AdminUploadPublisherLogoData = {
    formData: Body_admin_upload_publisher_logo;
    publisherId: string;
};

export type AdminUploadPublisherLogoResponse = (LogoUploadResponse);

export type AdminDeletePublisherLogoData = {
    publisherId: string;
};

export type AdminDeletePublisherLogoResponse = (void);

export type AdminUpdateSchoolData = {
    requestBody: SchoolUpdate;
    schoolId: string;
};

export type AdminUpdateSchoolResponse = (SchoolPublic);

export type AdminDeleteSchoolData = {
    schoolId: string;
};

export type AdminDeleteSchoolResponse = (void);

export type AdminCreateTeacherData = {
    requestBody: TeacherCreateAPI;
};

export type AdminCreateTeacherResponse = (UserCreationResponse);

export type AdminListTeachersData = {
    limit?: number;
    schoolId?: (string | null);
    skip?: number;
};

export type AdminListTeachersResponse = (Array<TeacherPublic>);

export type AdminUpdateTeacherData = {
    requestBody: TeacherUpdate;
    teacherId: string;
};

export type AdminUpdateTeacherResponse = (TeacherPublic);

export type AdminDeleteTeacherData = {
    teacherId: string;
};

export type AdminDeleteTeacherResponse = (void);

export type AdminCreateStudentData = {
    requestBody: StudentCreateAPI;
};

export type AdminCreateStudentResponse = (UserCreationResponse);

export type AdminListStudentsData = {
    limit?: number;
    skip?: number;
};

export type AdminListStudentsResponse = (Array<StudentPublic>);

export type AdminUpdateStudentData = {
    requestBody: StudentUpdate;
    studentId: string;
};

export type AdminUpdateStudentResponse = (StudentPublic);

export type AdminDeleteStudentData = {
    studentId: string;
};

export type AdminDeleteStudentResponse = (void);

export type AdminBulkDeleteStudentsData = {
    requestBody: BulkDeleteRequest;
};

export type AdminBulkDeleteStudentsResponse = (BulkDeleteResponse);

export type AdminBulkImportPublishersData = {
    formData: Body_admin_bulk_import_publishers;
};

export type AdminBulkImportPublishersResponse = (BulkImportResponse);

export type AdminBulkImportTeachersData = {
    formData: Body_admin_bulk_import_teachers;
};

export type AdminBulkImportTeachersResponse = (BulkImportResponse);

export type AdminBulkImportStudentsData = {
    formData: Body_admin_bulk_import_students;
};

export type AdminBulkImportStudentsResponse = (BulkImportResponse);

export type AdminGetStatsResponse = (DashboardStats);

export type AdminAdminUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type AdminAdminUpdateUserResponse = (UserPublic);

export type AdminResetUserPasswordData = {
    userId: string;
};

export type AdminResetUserPasswordResponse = (PasswordResetResponse);

export type AdminGetCacheStatsResponse = ({
    [key: string]: unknown;
});

export type AdminClearCacheResponse = (void);

export type AdminTestDreamStorageConnectionResponse = ({
    [key: string]: unknown;
});

export type AdminRegisterWebhooksManuallyData = {
    forceRecreate?: boolean;
};

export type AdminRegisterWebhooksManuallyResponse = ({
    [key: string]: unknown;
});

export type AdminGetBenchmarkOverviewEndpointResponse = (AdminBenchmarkOverview);

export type AdminUpdateSchoolBenchmarkSettingsData = {
    requestBody: BenchmarkSettingsUpdate;
    schoolId: string;
};

export type AdminUpdateSchoolBenchmarkSettingsResponse = (BenchmarkSettingsResponse);

export type AdminUpdatePublisherBenchmarkSettingsData = {
    publisherId: string;
    requestBody: BenchmarkSettingsUpdate;
};

export type AdminUpdatePublisherBenchmarkSettingsResponse = (BenchmarkSettingsResponse);

export type AdminCreatePublisherAccountData = {
    requestBody: PublisherAccountCreate;
};

export type AdminCreatePublisherAccountResponse = (PublisherAccountCreationResponse);

export type AdminListPublisherAccountsData = {
    limit?: number;
    skip?: number;
};

export type AdminListPublisherAccountsResponse = (PublisherAccountListResponse);

export type AdminGetPublisherAccountData = {
    userId: string;
};

export type AdminGetPublisherAccountResponse = (PublisherAccountPublic);

export type AdminUpdatePublisherAccountData = {
    requestBody: PublisherAccountUpdate;
    userId: string;
};

export type AdminUpdatePublisherAccountResponse = (PublisherAccountPublic);

export type AdminDeletePublisherAccountData = {
    userId: string;
};

export type AdminDeletePublisherAccountResponse = (void);

export type AdminListAllAssignmentsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    status?: (string | null);
    teacherId?: (string | null);
};

export type AdminListAllAssignmentsResponse = (AssignmentListResponse);

export type AdminDeleteAssignmentData = {
    assignmentId: string;
};

export type AdminDeleteAssignmentResponse = (void);

export type AssignmentsListAssignmentsResponse = (Array<AssignmentListItem>);

export type AssignmentsCreateAssignmentData = {
    requestBody: AssignmentCreate;
};

export type AssignmentsCreateAssignmentResponse = (AssignmentResponse);

export type AssignmentsListAllAssignmentsAdminResponse = (Array<AssignmentListItem>);

export type AssignmentsGetCalendarAssignmentsData = {
    /**
     * Filter by book ID (DCS book ID)
     */
    bookId?: (number | null);
    /**
     * Filter by class ID
     */
    classId?: (string | null);
    /**
     * End date for range (inclusive)
     */
    endDate: string;
    /**
     * Start date for range (inclusive)
     */
    startDate: string;
    /**
     * Filter by status
     */
    status?: (AssignmentPublishStatus | null);
};

export type AssignmentsGetCalendarAssignmentsResponse = (CalendarAssignmentsResponse);

export type AssignmentsCreateBulkAssignmentsData = {
    requestBody: AssignmentCreate;
};

export type AssignmentsCreateBulkAssignmentsResponse = (BulkAssignmentCreateResponse);

export type AssignmentsUpdateAssignmentData = {
    assignmentId: string;
    requestBody: AssignmentUpdate;
};

export type AssignmentsUpdateAssignmentResponse = (AssignmentResponse);

export type AssignmentsDeleteAssignmentData = {
    assignmentId: string;
};

export type AssignmentsDeleteAssignmentResponse = (void);

export type AssignmentsStartAssignmentData = {
    assignmentId: string;
};

export type AssignmentsStartAssignmentResponse = (ActivityStartResponse);

export type AssignmentsStartMultiActivityAssignmentData = {
    assignmentId: string;
};

export type AssignmentsStartMultiActivityAssignmentResponse = (MultiActivityStartResponse);

export type AssignmentsDownloadAssignmentMaterialData = {
    assignmentId: string;
    materialId: string;
    range?: (string | null);
    token?: (string | null);
};

export type AssignmentsDownloadAssignmentMaterialResponse = (unknown);

export type AssignmentsSaveActivityProgressData = {
    activityId: string;
    assignmentId: string;
    requestBody: ActivityProgressSaveRequest;
};

export type AssignmentsSaveActivityProgressResponse = (ActivityProgressSaveResponse);

export type AssignmentsSubmitMultiActivityAssignmentData = {
    assignmentId: string;
    requestBody: MultiActivitySubmitRequest;
};

export type AssignmentsSubmitMultiActivityAssignmentResponse = (MultiActivitySubmitResponse);

export type AssignmentsSaveProgressData = {
    assignmentId: string;
    requestBody: AssignmentSaveProgressRequest;
};

export type AssignmentsSaveProgressResponse = (AssignmentSaveProgressResponse);

export type AssignmentsSubmitAssignmentData = {
    assignmentId: string;
    requestBody: AssignmentSubmitRequest;
};

export type AssignmentsSubmitAssignmentResponse = (AssignmentSubmissionResponse);

export type AssignmentsGetDetailedResultsData = {
    assignmentId: string;
};

export type AssignmentsGetDetailedResultsResponse = (AssignmentDetailedResultsResponse);

export type AssignmentsGetStudentAnswersData = {
    assignmentId: string;
    studentId: string;
};

export type AssignmentsGetStudentAnswersResponse = (StudentAnswersResponse);

export type AssignmentsGetMultiActivityAnalyticsData = {
    assignmentId: string;
    expandActivityId?: (string | null);
};

export type AssignmentsGetMultiActivityAnalyticsResponse = (MultiActivityAnalyticsResponse);

export type AssignmentsGetStudentAssignmentResultData = {
    assignmentId: string;
};

export type AssignmentsGetStudentAssignmentResultResponse = (StudentAssignmentResultResponse);

export type AssignmentsCreateOrUpdateFeedbackData = {
    assignmentId: string;
    requestBody: FeedbackCreate;
    studentId: string;
};

export type AssignmentsCreateOrUpdateFeedbackResponse = (FeedbackPublic);

export type AssignmentsGetFeedbackData = {
    assignmentId: string;
    studentId: string;
};

export type AssignmentsGetFeedbackResponse = ((FeedbackPublic | FeedbackStudentView | null));

export type AssignmentsGetMyFeedbackData = {
    assignmentId: string;
};

export type AssignmentsGetMyFeedbackResponse = ((FeedbackStudentView | null));

export type AssignmentsUpdateFeedbackData = {
    feedbackId: string;
    requestBody: FeedbackUpdate;
};

export type AssignmentsUpdateFeedbackResponse = (FeedbackPublic);

export type AssignmentsPreviewAssignmentData = {
    assignmentId: string;
};

export type AssignmentsPreviewAssignmentResponse = (AssignmentPreviewResponse);

export type AssignmentsPreviewActivityData = {
    activityId: string;
};

export type AssignmentsPreviewActivityResponse = (ActivityPreviewResponse);

export type AvatarsGetPredefinedAvatarsResponse = (PredefinedAvatarsResponse);

export type AvatarsRemoveAvatarResponse = (AvatarUpdateResponse);

export type AvatarsSelectPredefinedAvatarData = {
    requestBody: SelectAvatarRequest;
};

export type AvatarsSelectPredefinedAvatarResponse = (UserPublic);

export type BookAssetsServeBookAssetData = {
    /**
     * Relative path to asset (e.g., 'images/M1/p7m5.jpg', 'audio/6a.mp3')
     */
    assetPath: string;
    /**
     * Book ID
     */
    bookId: number;
};

export type BookAssetsServeBookAssetResponse = (unknown);

export type BookAssetsServePageImageData = {
    /**
     * Book ID
     */
    bookId: number;
    /**
     * Page number
     */
    pageNumber: number;
};

export type BookAssetsServePageImageResponse = (unknown);

export type BookAssignmentsCreateBookAssignmentData = {
    requestBody: BookAssignmentCreate;
};

export type BookAssignmentsCreateBookAssignmentResponse = (BookAssignmentPublic);

export type BookAssignmentsListBookAssignmentsData = {
    bookId?: (string | null);
    limit?: number;
    schoolId?: (string | null);
    skip?: number;
};

export type BookAssignmentsListBookAssignmentsResponse = (BookAssignmentListResponse);

export type BookAssignmentsCreateBulkBookAssignmentsData = {
    requestBody: BulkBookAssignmentCreate;
};

export type BookAssignmentsCreateBulkBookAssignmentsResponse = (Array<BookAssignmentPublic>);

export type BookAssignmentsDeleteBookAssignmentData = {
    assignmentId: string;
};

export type BookAssignmentsDeleteBookAssignmentResponse = (void);

export type BookAssignmentsGetBookAssignmentsData = {
    bookId: number;
};

export type BookAssignmentsGetBookAssignmentsResponse = (Array<BookAssignmentResponse>);

export type BookMediaStreamMediaData = {
    /**
     * Relative path to media (e.g., 'audio/08.mp3', 'videos/intro.mp4')
     */
    assetPath: string;
    /**
     * Book ID
     */
    bookId: string;
    range?: (string | null);
    token?: (string | null);
};

export type BookMediaStreamMediaResponse = (unknown);

export type BooksGetBookCoverData = {
    bookId: number;
};

export type BooksGetBookCoverResponse = (unknown);

export type BooksListBooksData = {
    activityType?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type BooksListBooksResponse = (BookListResponse);

export type BooksGetBookActivitiesData = {
    bookId: number;
};

export type BooksGetBookActivitiesResponse = (Array<ActivityResponse>);

export type BooksGetBookPagesData = {
    bookId: number;
};

export type BooksGetBookPagesResponse = (BookPagesResponse);

export type BooksGetPageActivitiesData = {
    bookId: number;
    moduleName?: (string | null);
    pageNumber: number;
};

export type BooksGetPageActivitiesResponse = (Array<PageActivityResponse>);

export type BooksGetBookPagesDetailData = {
    bookId: number;
};

export type BooksGetBookPagesDetailResponse = (BookPagesDetailResponse);

export type BooksGetBookStructureData = {
    bookId: number;
};

export type BooksGetBookStructureResponse = (BookStructureResponse);

export type BooksListBookVideosData = {
    bookId: number;
};

export type BooksListBookVideosResponse = (BookVideosResponse);

export type ClassesCreateClassData = {
    requestBody: ClassCreateByTeacher;
};

export type ClassesCreateClassResponse = (ClassResponse);

export type ClassesListClassesData = {
    limit?: number;
    skip?: number;
};

export type ClassesListClassesResponse = (Array<ClassResponse>);

export type ClassesGetClassDetailData = {
    classId: string;
};

export type ClassesGetClassDetailResponse = (ClassDetailResponse);

export type ClassesUpdateClassData = {
    classId: string;
    requestBody: ClassUpdate;
};

export type ClassesUpdateClassResponse = (ClassResponse);

export type ClassesArchiveClassData = {
    classId: string;
};

export type ClassesArchiveClassResponse = (void);

export type ClassesAddStudentsToClassData = {
    classId: string;
    requestBody: ClassStudentAdd;
};

export type ClassesAddStudentsToClassResponse = (unknown);

export type ClassesRemoveStudentFromClassData = {
    classId: string;
    studentId: string;
};

export type ClassesRemoveStudentFromClassResponse = (void);

export type ClassesGetClassAnalyticsEndpointData = {
    classId: string;
    period?: 'weekly' | 'monthly' | 'semester' | 'ytd';
};

export type ClassesGetClassAnalyticsEndpointResponse = (ClassAnalyticsResponse);

export type ClassesGetClassBenchmarksEndpointData = {
    classId: string;
    period?: 'weekly' | 'monthly' | 'semester' | 'all';
};

export type ClassesGetClassBenchmarksEndpointResponse = (ClassBenchmarkResponse);

export type DevGetQuickLoginUsersResponse = ({
    [key: string]: Array<{
        [key: string]: (string | null);
    }>;
});

export type DevResetQuickLoginPasswordsResponse = ({
    [key: string]: (string | number);
});

export type DevInstantLoginData = {
    username: string;
};

export type DevInstantLoginResponse = ({
    [key: string]: (string);
});

export type FeedbackGetFeedbackOptionsResponse = (FeedbackOptionsResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MessagesSendMessageData = {
    requestBody: MessageCreate;
};

export type MessagesSendMessageResponse = (MessagePublic);

export type MessagesGetConversationsData = {
    /**
     * Number of conversations to return
     */
    limit?: number;
    /**
     * Number of conversations to skip
     */
    offset?: number;
};

export type MessagesGetConversationsResponse = (ConversationListResponse);

export type MessagesGetMessageThreadData = {
    partnerId: string;
};

export type MessagesGetMessageThreadResponse = (MessageThreadResponse);

export type MessagesMarkMessageAsReadData = {
    messageId: string;
};

export type MessagesMarkMessageAsReadResponse = (MessageReadResponse);

export type MessagesGetAllowedRecipientsResponse = (RecipientListResponse);

export type MessagesGetUnreadMessagesCountResponse = (UnreadMessagesCountResponse);

export type NotificationsGetNotificationsData = {
    /**
     * Number of notifications to return
     */
    limit?: number;
    /**
     * Number of notifications to skip
     */
    offset?: number;
    /**
     * Filter by notification type
     */
    type?: (NotificationType_Input | null);
    /**
     * Filter to only unread notifications
     */
    unreadOnly?: boolean;
};

export type NotificationsGetNotificationsResponse = (NotificationListResponse);

export type NotificationsGetUnreadCountResponse = (UnreadCountResponse);

export type NotificationsMarkNotificationAsReadData = {
    notificationId: string;
};

export type NotificationsMarkNotificationAsReadResponse = (NotificationResponse);

export type NotificationsMarkAllNotificationsAsReadResponse = (MarkAllReadResponse);

export type NotificationsGetNotificationPreferencesResponse = (NotificationPreferencesListResponse);

export type NotificationsUpdateNotificationPreferencesData = {
    requestBody: NotificationPreferencesBulkUpdate;
};

export type NotificationsUpdateNotificationPreferencesResponse = (NotificationPreferencesBulkUpdateResponse);

export type NotificationsUpdateSinglePreferenceData = {
    notificationType: NotificationType_Input;
    requestBody: NotificationPreferenceUpdate;
};

export type NotificationsUpdateSinglePreferenceResponse = (NotificationPreferenceResponse);

export type NotificationsGetMuteStatusResponse = (GlobalMuteStatusResponse);

export type NotificationsSetGlobalMuteData = {
    requestBody: GlobalMuteRequest;
};

export type NotificationsSetGlobalMuteResponse = (GlobalMuteResponse);

export type NotificationsCancelGlobalMuteResponse = (void);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PublishersGetPublisherLogoData = {
    publisherId: number;
};

export type PublishersGetPublisherLogoResponse = (unknown);

export type PublishersGetMyProfileResponse = (PublisherProfile);

export type PublishersGetMyStatsResponse = (PublisherStats);

export type PublishersListMySchoolsResponse = (Array<SchoolWithCounts>);

export type PublishersCreateMySchoolData = {
    requestBody: SchoolCreateByPublisher;
};

export type PublishersCreateMySchoolResponse = (SchoolPublic);

export type PublishersListMyTeachersResponse = (Array<TeacherWithCounts>);

export type PublishersCreateMyTeacherData = {
    requestBody: TeacherCreateAPI;
};

export type PublishersCreateMyTeacherResponse = (UserCreationResponse);

export type PublishersListMyBooksResponse = (Array<BookPublic>);

export type ReportsGenerateReportData = {
    requestBody: ReportGenerateRequest;
};

export type ReportsGenerateReportResponse = (ReportJobResponse);

export type ReportsCheckReportStatusData = {
    jobId: string;
};

export type ReportsCheckReportStatusResponse = (ReportStatusResponse);

export type ReportsDownloadReportData = {
    jobId: string;
};

export type ReportsDownloadReportResponse = (unknown);

export type ReportsListReportHistoryResponse = (ReportHistoryResponse);

export type ReportsListReportTemplatesResponse = (Array<SavedReportTemplate>);

export type ReportsCreateReportTemplateData = {
    requestBody: SavedReportTemplateCreate;
};

export type ReportsCreateReportTemplateResponse = (SavedReportTemplate);

export type ReportsRemoveReportTemplateData = {
    templateId: string;
};

export type ReportsRemoveReportTemplateResponse = (void);

export type ScheduledTasksRunDeadlineRemindersData = {
    xSchedulerKey?: (string | null);
};

export type ScheduledTasksRunDeadlineRemindersResponse = (DeadlineCheckResponse);

export type ScheduledTasksRunApproachingDeadlinesOnlyData = {
    xSchedulerKey?: (string | null);
};

export type ScheduledTasksRunApproachingDeadlinesOnlyResponse = (DeadlineCheckResponse);

export type ScheduledTasksRunPastDueOnlyData = {
    xSchedulerKey?: (string | null);
};

export type ScheduledTasksRunPastDueOnlyResponse = (DeadlineCheckResponse);

export type ScheduledTasksRunPublishScheduledAssignmentsData = {
    xSchedulerKey?: (string | null);
};

export type ScheduledTasksRunPublishScheduledAssignmentsResponse = (PublishAssignmentsResponse);

export type StudentsGetStudentAssignmentsData = {
    status?: (string | null);
};

export type StudentsGetStudentAssignmentsResponse = (Array<StudentAssignmentResponse>);

export type StudentsGetStudentProgressData = {
    /**
     * Time period for progress data
     */
    period?: 'this_week' | 'this_month' | 'all_time';
};

export type StudentsGetStudentProgressResponse = (StudentProgressResponse);

export type StudentsGetStudentAnalyticsData = {
    /**
     * Time period for analytics
     */
    period?: '7d' | '30d' | '3m' | 'all';
    studentId: string;
};

export type StudentsGetStudentAnalyticsResponse = (StudentAnalyticsResponse);

export type StudentsGetMyBadgesResponse = (StudentBadgeCountsResponse);

export type StudentsGetStudentBadgesData = {
    studentId: string;
};

export type StudentsGetStudentBadgesResponse = (StudentBadgeCountsResponse);

export type StudentsGetStudentCalendarAssignmentsData = {
    /**
     * End date for range (inclusive)
     */
    endDate: string;
    /**
     * Start date for range (inclusive)
     */
    startDate: string;
};

export type StudentsGetStudentCalendarAssignmentsResponse = (StudentCalendarAssignmentsResponse);

export type StudentsGetImportTemplateResponse = (unknown);

export type StudentsValidateImportFileData = {
    formData: Body_students_validate_import_file;
};

export type StudentsValidateImportFileResponse = (ImportValidationResponse);

export type StudentsExecuteImportData = {
    formData: Body_students_execute_import;
    /**
     * School ID (required for Admin)
     */
    schoolId?: (string | null);
    /**
     * Teacher ID (optional for Admin, to assign classrooms)
     */
    teacherId?: (string | null);
};

export type StudentsExecuteImportResponse = (ImportExecutionResponse);

export type StudentsDownloadCredentialsData = {
    requestBody: CredentialsDownloadRequest;
};

export type StudentsDownloadCredentialsResponse = (unknown);

export type SupervisorsListSupervisorsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type SupervisorsListSupervisorsResponse = (Array<SupervisorPublic>);

export type SupervisorsCreateSupervisorData = {
    requestBody: SupervisorCreateAPI;
};

export type SupervisorsCreateSupervisorResponse = (SupervisorCreateResponse);

export type SupervisorsGetSupervisorData = {
    supervisorId: string;
};

export type SupervisorsGetSupervisorResponse = (SupervisorPublic);

export type SupervisorsUpdateSupervisorData = {
    requestBody: SupervisorUpdate;
    supervisorId: string;
};

export type SupervisorsUpdateSupervisorResponse = (SupervisorPublic);

export type SupervisorsDeleteSupervisorData = {
    supervisorId: string;
};

export type SupervisorsDeleteSupervisorResponse = (void);

export type SupervisorsResetSupervisorPasswordData = {
    supervisorId: string;
};

export type SupervisorsResetSupervisorPasswordResponse = (PasswordResetResponse);

export type TeacherMaterialsUploadMaterialData = {
    formData: Body_teacher_materials_upload_material;
};

export type TeacherMaterialsUploadMaterialResponse = (UploadResponse);

export type TeacherMaterialsCreateTextNoteData = {
    requestBody: TextNoteCreate;
};

export type TeacherMaterialsCreateTextNoteResponse = (MaterialResponse);

export type TeacherMaterialsUpdateTextNoteData = {
    materialId: string;
    requestBody: TextNoteUpdate;
};

export type TeacherMaterialsUpdateTextNoteResponse = (MaterialResponse);

export type TeacherMaterialsCreateUrlLinkData = {
    requestBody: UrlLinkCreate;
};

export type TeacherMaterialsCreateUrlLinkResponse = (MaterialResponse);

export type TeacherMaterialsListMaterialsData = {
    type?: (MaterialType | null);
};

export type TeacherMaterialsListMaterialsResponse = (MaterialListResponse);

export type TeacherMaterialsGetQuotaResponse = (StorageQuotaResponse);

export type TeacherMaterialsGetMaterialData = {
    materialId: string;
};

export type TeacherMaterialsGetMaterialResponse = (MaterialResponse);

export type TeacherMaterialsUpdateMaterialData = {
    materialId: string;
    requestBody: MaterialUpdate;
};

export type TeacherMaterialsUpdateMaterialResponse = (MaterialResponse);

export type TeacherMaterialsDeleteMaterialData = {
    materialId: string;
};

export type TeacherMaterialsDeleteMaterialResponse = (void);

export type TeacherMaterialsGetPresignedUrlData = {
    expiresMinutes?: number;
    materialId: string;
};

export type TeacherMaterialsGetPresignedUrlResponse = (PresignedUrlResponse);

export type TeacherMaterialsDownloadMaterialData = {
    materialId: string;
};

export type TeacherMaterialsDownloadMaterialResponse = (unknown);

export type TeacherMaterialsStreamMaterialData = {
    materialId: string;
};

export type TeacherMaterialsStreamMaterialResponse = (unknown);

export type TeachersListMyStudentsResponse = (Array<StudentPublic>);

export type TeachersCreateStudentData = {
    requestBody: StudentCreateAPI;
};

export type TeachersCreateStudentResponse = (UserCreationResponse);

export type TeachersBulkImportStudentsData = {
    formData: Body_teachers_bulk_import_students;
};

export type TeachersBulkImportStudentsResponse = (BulkImportResponse);

export type TeachersUpdateStudentData = {
    requestBody: StudentUpdate;
    studentId: string;
};

export type TeachersUpdateStudentResponse = (StudentPublic);

export type TeachersDeleteStudentData = {
    studentId: string;
};

export type TeachersDeleteStudentResponse = (unknown);

export type TeachersBulkDeleteStudentsData = {
    requestBody: BulkDeleteRequest;
};

export type TeachersBulkDeleteStudentsResponse = (BulkDeleteResponse);

export type TeachersListMyClassesResponse = (Array<ClassPublic>);

export type TeachersCreateClassData = {
    requestBody: ClassCreateByTeacher;
};

export type TeachersCreateClassResponse = (ClassPublic);

export type TeachersGetClassDetailsData = {
    classId: string;
};

export type TeachersGetClassDetailsResponse = (ClassPublic);

export type TeachersUpdateClassData = {
    classId: string;
    requestBody: ClassUpdate;
};

export type TeachersUpdateClassResponse = (ClassPublic);

export type TeachersAddStudentsToClassData = {
    classId: string;
    requestBody: Array<(string)>;
};

export type TeachersAddStudentsToClassResponse = (unknown);

export type TeachersGetClassStudentsData = {
    classId: string;
};

export type TeachersGetClassStudentsResponse = (Array<StudentPublic>);

export type TeachersRemoveStudentFromClassData = {
    classId: string;
    studentId: string;
};

export type TeachersRemoveStudentFromClassResponse = (unknown);

export type TeachersGetMyInsightsResponse = (TeacherInsightsResponse);

export type TeachersGetInsightDetailsData = {
    insightId: string;
};

export type TeachersGetInsightDetailsResponse = (InsightDetail);

export type TeachersDismissInsightEndpointData = {
    insightId: string;
};

export type TeachersDismissInsightEndpointResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersChangeInitialPasswordData = {
    requestBody: ChangeInitialPasswordRequest;
};

export type UsersChangeInitialPasswordResponse = (ChangePasswordResponse);

export type UsersCompleteTourResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = ({
    [key: string]: unknown;
});

export type WebhooksReceiveDreamStorageWebhookResponse = ({
    [key: string]: unknown;
});

export type WebhooksTestDreamStorageWebhookData = {
    requestBody: WebhookPayload;
};

export type WebhooksTestDreamStorageWebhookResponse = ({
    [key: string]: unknown;
});