"""add_lms_user_tables

Revision ID: 0550ee3485d1
Revises: 2c0159a5ffb6
Create Date: 2025-10-27 00:53:24.692947

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0550ee3485d1'
down_revision = '2c0159a5ffb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_user_id'), 'publishers', ['user_id'], unique=True)
    op.create_table('students',
    sa.Column('grade_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('parent_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('schools',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('publisher_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_publisher_id'), 'schools', ['publisher_id'], unique=False)
    op.create_table('teachers',
    sa.Column('subject_specialization', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.drop_index(op.f('idx_user_role'), table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_role'), 'user', ['role'], unique=False)
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_schools_publisher_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_publishers_user_id'), table_name='publishers')
    op.drop_table('publishers')
    # ### end Alembic commands ###
