"""add dcs activity count and details to books

Revision ID: 31457c3673aa
Revises: 219e0abc2883
Create Date: 2025-11-17 00:07:47.971778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31457c3673aa'
down_revision = '219e0abc2883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('dcs_activity_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('dcs_activity_details', sa.JSON(), nullable=True))
    op.alter_column('webhook_event_logs', 'payload_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('webhook_event_logs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('webhook_event_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('webhook_event_logs', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_webhook_event_logs_book_id', table_name='webhook_event_logs')
    op.drop_index('idx_webhook_event_logs_created_at', table_name='webhook_event_logs')
    op.drop_index('idx_webhook_event_logs_event_type', table_name='webhook_event_logs')
    op.drop_index('idx_webhook_event_logs_status', table_name='webhook_event_logs')
    op.create_index(op.f('ix_webhook_event_logs_book_id'), 'webhook_event_logs', ['book_id'], unique=False)
    op.create_index(op.f('ix_webhook_event_logs_created_at'), 'webhook_event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_event_logs_event_type'), 'webhook_event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_event_logs_status'), 'webhook_event_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_logs_status'), table_name='webhook_event_logs')
    op.drop_index(op.f('ix_webhook_event_logs_event_type'), table_name='webhook_event_logs')
    op.drop_index(op.f('ix_webhook_event_logs_created_at'), table_name='webhook_event_logs')
    op.drop_index(op.f('ix_webhook_event_logs_book_id'), table_name='webhook_event_logs')
    op.create_index('idx_webhook_event_logs_status', 'webhook_event_logs', ['status'], unique=False)
    op.create_index('idx_webhook_event_logs_event_type', 'webhook_event_logs', ['event_type'], unique=False)
    op.create_index('idx_webhook_event_logs_created_at', 'webhook_event_logs', ['created_at'], unique=False)
    op.create_index('idx_webhook_event_logs_book_id', 'webhook_event_logs', ['book_id'], unique=False)
    op.alter_column('webhook_event_logs', 'processed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('webhook_event_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('webhook_event_logs', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('webhook_event_logs', 'payload_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('books', 'dcs_activity_details')
    op.drop_column('books', 'dcs_activity_count')
    # ### end Alembic commands ###
