"""add_username_to_user

Revision ID: 3c04a1c1d4b4
Revises: 868e90ceeda1
Create Date: 2025-11-10 00:17:15.647270

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3c04a1c1d4b4'
down_revision = '868e90ceeda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))

    # Step 2: Populate existing users with unique usernames
    connection = op.get_bind()

    # Generate unique usernames by appending row number for duplicates
    connection.execute(sa.text("""
        WITH ranked_users AS (
            SELECT
                id,
                LOWER(SPLIT_PART(email, '@', 1)) as base_username,
                ROW_NUMBER() OVER (PARTITION BY LOWER(SPLIT_PART(email, '@', 1)) ORDER BY id) as rn
            FROM "user"
            WHERE username IS NULL
        )
        UPDATE "user" u
        SET username = CASE
            WHEN r.rn = 1 THEN r.base_username
            ELSE r.base_username || r.rn::text
        END
        FROM ranked_users r
        WHERE u.id = r.id
    """))

    # Step 3: Make column NOT NULL
    op.alter_column('user', 'username', nullable=False)

    # Step 4: Create unique index
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
