"""add_books_activities_tables

Revision ID: 9cf939fae9cd
Revises: c1ef839a2e4a
Create Date: 2025-11-15 03:36:54.414453

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9cf939fae9cd'
down_revision = 'c1ef839a2e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create BookStatus enum type
    op.execute("CREATE TYPE bookstatus AS ENUM ('published', 'draft', 'archived')")

    op.create_table('book_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('publisher_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'publisher_id', name='uq_book_access_book_publisher')
    )
    op.create_index(op.f('ix_book_access_book_id'), 'book_access', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_access_publisher_id'), 'book_access', ['publisher_id'], unique=False)
    # Composite index for permission queries (publisher_id, book_id)
    op.create_index('idx_book_access_publisher_book', 'book_access', ['publisher_id', 'book_id'], unique=False)

    op.add_column('activities', sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('activities', sa.Column('page_number', sa.Integer(), nullable=False))
    op.add_column('activities', sa.Column('section_index', sa.Integer(), nullable=False))
    op.drop_index('ix_activities_activity_type', table_name='activities')
    # Add indexes for activities
    op.create_index('idx_activities_book_order', 'activities', ['book_id', 'order_index'], unique=False)
    op.create_index('idx_activities_book_type', 'activities', ['book_id', 'activity_type'], unique=False)
    op.drop_index('ix_assignment_students_completed_at', table_name='assignment_students')
    op.drop_index('ix_assignment_students_status', table_name='assignment_students')
    op.drop_index('ix_assignments_due_date', table_name='assignments')
    op.add_column('books', sa.Column('book_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('books', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('books', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('books', sa.Column('status', sa.Enum('published', 'draft', 'archived', name='bookstatus'), nullable=False))
    op.add_column('books', sa.Column('config_json', sa.JSON(), nullable=True))
    op.add_column('books', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.drop_constraint('books_dream_storage_id_key', 'books', type_='unique')
    op.create_index(op.f('ix_books_dream_storage_id'), 'books', ['dream_storage_id'], unique=True)
    # Add composite index for books (publisher_id, status)
    op.create_index('idx_books_publisher_status', 'books', ['publisher_id', 'status'], unique=False)

    op.drop_index('ix_classes_is_active', table_name='classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_classes_is_active', 'classes', ['is_active'], unique=False)
    # Drop books indexes
    op.drop_index('idx_books_publisher_status', table_name='books')
    op.drop_index(op.f('ix_books_dream_storage_id'), table_name='books')
    op.create_unique_constraint('books_dream_storage_id_key', 'books', ['dream_storage_id'])
    op.drop_column('books', 'synced_at')
    op.drop_column('books', 'config_json')
    op.drop_column('books', 'status')
    op.drop_column('books', 'category')
    op.drop_column('books', 'language')
    op.drop_column('books', 'book_name')
    op.create_index('ix_assignments_due_date', 'assignments', ['due_date'], unique=False)
    op.create_index('ix_assignment_students_status', 'assignment_students', ['status'], unique=False)
    op.create_index('ix_assignment_students_completed_at', 'assignment_students', ['completed_at'], unique=False)
    # Drop activities indexes
    op.drop_index('idx_activities_book_type', table_name='activities')
    op.drop_index('idx_activities_book_order', table_name='activities')
    op.create_index('ix_activities_activity_type', 'activities', ['activity_type'], unique=False)
    op.drop_column('activities', 'section_index')
    op.drop_column('activities', 'page_number')
    op.drop_column('activities', 'module_name')
    # Drop book_access indexes
    op.drop_index('idx_book_access_publisher_book', table_name='book_access')
    op.drop_index(op.f('ix_book_access_publisher_id'), table_name='book_access')
    op.drop_index(op.f('ix_book_access_book_id'), table_name='book_access')
    op.drop_table('book_access')

    # Drop BookStatus enum type
    op.execute("DROP TYPE IF EXISTS bookstatus")
    # ### end Alembic commands ###
