"""add_dismissed_insights_table

Revision ID: adbf3a221238
Revises: eff927c3727c
Create Date: 2025-11-28 22:31:24.081581

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'adbf3a221238'
down_revision = 'eff927c3727c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('insight_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'insight_key', name='uq_dismissed_insight_teacher_key')
    )
    op.create_index(op.f('ix_dismissed_insights_teacher_id'), 'dismissed_insights', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dismissed_insights_teacher_id'), table_name='dismissed_insights')
    op.drop_table('dismissed_insights')
    # ### end Alembic commands ###
