"""rename_publisher_to_publisher_name

Revision ID: de763a3332c6
Revises: 9cf939fae9cd
Create Date: 2025-11-15 03:51:28.565863

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'de763a3332c6'
down_revision = '9cf939fae9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activities_book_order', table_name='activities')
    op.drop_index('idx_activities_book_type', table_name='activities')
    op.drop_index('idx_book_access_publisher_book', table_name='book_access')
    op.add_column('books', sa.Column('publisher_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_index('idx_books_publisher_status', table_name='books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_books_publisher_status', 'books', ['publisher_id', 'status'], unique=False)
    op.drop_column('books', 'publisher_name')
    op.create_index('idx_book_access_publisher_book', 'book_access', ['publisher_id', 'book_id'], unique=False)
    op.create_index('idx_activities_book_type', 'activities', ['book_id', 'activity_type'], unique=False)
    op.create_index('idx_activities_book_order', 'activities', ['book_id', 'order_index'], unique=False)
    # ### end Alembic commands ###
