/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ViewerBookIdRouteImport } from './routes/viewer.$bookId'
import { Route as LayoutTeacherRouteImport } from './routes/_layout.teacher'
import { Route as LayoutStudentRouteImport } from './routes/_layout.student'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPublisherRouteImport } from './routes/_layout.publisher'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutAdminRouteImport } from './routes/_layout.admin'
import { Route as LayoutMessagingIndexRouteImport } from './routes/_layout/messaging/index'
import { Route as LayoutDreamaiIndexRouteImport } from './routes/_layout/dreamai/index'
import { Route as LayoutTeacherStudentsRouteImport } from './routes/_layout/teacher/students'
import { Route as LayoutTeacherReportsRouteImport } from './routes/_layout/teacher/reports'
import { Route as LayoutTeacherLibraryViewerRouteImport } from './routes/_layout/teacher/library-viewer'
import { Route as LayoutTeacherInsightsRouteImport } from './routes/_layout/teacher/insights'
import { Route as LayoutTeacherDashboardRouteImport } from './routes/_layout/teacher/dashboard'
import { Route as LayoutTeacherClassroomsRouteImport } from './routes/_layout/teacher/classrooms'
import { Route as LayoutTeacherCalendarRouteImport } from './routes/_layout/teacher/calendar'
import { Route as LayoutTeacherAssignmentsRouteImport } from './routes/_layout/teacher/assignments'
import { Route as LayoutTeacherAnnouncementsRouteImport } from './routes/_layout/teacher/announcements'
import { Route as LayoutTeacherAiMaterialsRouteImport } from './routes/_layout/teacher/ai-materials'
import { Route as LayoutStudentReportsRouteImport } from './routes/_layout/student/reports'
import { Route as LayoutStudentProgressRouteImport } from './routes/_layout/student/progress'
import { Route as LayoutStudentDashboardRouteImport } from './routes/_layout/student/dashboard'
import { Route as LayoutStudentCalendarRouteImport } from './routes/_layout/student/calendar'
import { Route as LayoutStudentAssignmentsRouteImport } from './routes/_layout/student/assignments'
import { Route as LayoutStudentAnnouncementsRouteImport } from './routes/_layout/student/announcements'
import { Route as LayoutPublisherTeachersRouteImport } from './routes/_layout/publisher/teachers'
import { Route as LayoutPublisherSchoolsRouteImport } from './routes/_layout/publisher/schools'
import { Route as LayoutPublisherLibraryViewerRouteImport } from './routes/_layout/publisher/library-viewer'
import { Route as LayoutPublisherLibraryRouteImport } from './routes/_layout/publisher/library'
import { Route as LayoutPublisherDashboardRouteImport } from './routes/_layout/publisher/dashboard'
import { Route as LayoutPublisherBookAssignmentsRouteImport } from './routes/_layout/publisher/book-assignments'
import { Route as LayoutMessagingConversationIdRouteImport } from './routes/_layout/messaging/$conversationId'
import { Route as LayoutDreamaiVocabularyRouteImport } from './routes/_layout/dreamai/vocabulary'
import { Route as LayoutDreamaiMaterialsRouteImport } from './routes/_layout/dreamai/materials'
import { Route as LayoutDreamaiLibraryRouteImport } from './routes/_layout/dreamai/library'
import { Route as LayoutDreamaiGeneratorRouteImport } from './routes/_layout/dreamai/generator'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin.users'
import { Route as LayoutAdminTeachersRouteImport } from './routes/_layout/admin/teachers'
import { Route as LayoutAdminSupervisorsRouteImport } from './routes/_layout/admin/supervisors'
import { Route as LayoutAdminStudentsRouteImport } from './routes/_layout/admin/students'
import { Route as LayoutAdminSchoolsRouteImport } from './routes/_layout/admin/schools'
import { Route as LayoutAdminPublishersRouteImport } from './routes/_layout/admin/publishers'
import { Route as LayoutAdminLibraryViewerRouteImport } from './routes/_layout/admin/library-viewer'
import { Route as LayoutAdminDashboardRouteImport } from './routes/_layout/admin/dashboard'
import { Route as LayoutAdminBooksRouteImport } from './routes/_layout/admin/books'
import { Route as LayoutAdminBenchmarksRouteImport } from './routes/_layout/admin/benchmarks'
import { Route as LayoutAdminAssignmentsRouteImport } from './routes/_layout/admin/assignments'
import { Route as LayoutAdminAiUsageRouteImport } from './routes/_layout/admin/ai-usage'
import { Route as LayoutTeacherMaterialsIndexRouteImport } from './routes/_layout/teacher/materials/index'
import { Route as LayoutTeacherBooksIndexRouteImport } from './routes/_layout/teacher/books/index'
import { Route as LayoutTeacherAssignmentsIndexRouteImport } from './routes/_layout/teacher/assignments/index'
import { Route as LayoutTeacherAnalyticsIndexRouteImport } from './routes/_layout/teacher/analytics/index'
import { Route as LayoutStudentAssignmentsIndexRouteImport } from './routes/_layout/student/assignments/index'
import { Route as LayoutTeacherClassroomsClassIdRouteImport } from './routes/_layout/teacher/classrooms_.$classId'
import { Route as LayoutTeacherBooksBookIdRouteImport } from './routes/_layout/teacher/books/$bookId'
import { Route as LayoutTeacherAssignmentsPreviewRouteImport } from './routes/_layout/teacher/assignments/preview'
import { Route as LayoutTeacherAssignmentsAssignmentIdRouteImport } from './routes/_layout/teacher/assignments/$assignmentId'
import { Route as LayoutTeacherAnalyticsSkillsRouteImport } from './routes/_layout/teacher/analytics/skills'
import { Route as LayoutTeacherAnalyticsStudentIdRouteImport } from './routes/_layout/teacher/analytics/$studentId'
import { Route as LayoutStudentAssignmentsAssignmentIdRouteImport } from './routes/_layout/student/assignments/$assignmentId'
import { Route as LayoutStudentAssignmentsAssignmentIdIndexRouteImport } from './routes/_layout/student/assignments/$assignmentId/index'
import { Route as LayoutStudentAssignmentsAssignmentIdSuccessRouteImport } from './routes/_layout/student/assignments/$assignmentId/success'
import { Route as LayoutStudentAssignmentsAssignmentIdResultRouteImport } from './routes/_layout/student/assignments/$assignmentId/result'
import { Route as LayoutStudentAssignmentsAssignmentIdPlayMultiRouteImport } from './routes/_layout/student/assignments/$assignmentId/play-multi'
import { Route as LayoutStudentAssignmentsAssignmentIdPlayRouteImport } from './routes/_layout/student/assignments/$assignmentId/play'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ViewerBookIdRoute = ViewerBookIdRouteImport.update({
  id: '/viewer/$bookId',
  path: '/viewer/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeacherRoute = LayoutTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentRoute = LayoutStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPublisherRoute = LayoutPublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMessagingIndexRoute = LayoutMessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDreamaiIndexRoute = LayoutDreamaiIndexRouteImport.update({
  id: '/dreamai/',
  path: '/dreamai/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeacherStudentsRoute = LayoutTeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherReportsRoute = LayoutTeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherLibraryViewerRoute =
  LayoutTeacherLibraryViewerRouteImport.update({
    id: '/library-viewer',
    path: '/library-viewer',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherInsightsRoute = LayoutTeacherInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherDashboardRoute = LayoutTeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherClassroomsRoute = LayoutTeacherClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherCalendarRoute = LayoutTeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherAssignmentsRoute =
  LayoutTeacherAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherAnnouncementsRoute =
  LayoutTeacherAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherAiMaterialsRoute =
  LayoutTeacherAiMaterialsRouteImport.update({
    id: '/ai-materials',
    path: '/ai-materials',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutStudentReportsRoute = LayoutStudentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutStudentRoute,
} as any)
const LayoutStudentProgressRoute = LayoutStudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => LayoutStudentRoute,
} as any)
const LayoutStudentDashboardRoute = LayoutStudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutStudentRoute,
} as any)
const LayoutStudentCalendarRoute = LayoutStudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutStudentRoute,
} as any)
const LayoutStudentAssignmentsRoute =
  LayoutStudentAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => LayoutStudentRoute,
  } as any)
const LayoutStudentAnnouncementsRoute =
  LayoutStudentAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => LayoutStudentRoute,
  } as any)
const LayoutPublisherTeachersRoute = LayoutPublisherTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => LayoutPublisherRoute,
} as any)
const LayoutPublisherSchoolsRoute = LayoutPublisherSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => LayoutPublisherRoute,
} as any)
const LayoutPublisherLibraryViewerRoute =
  LayoutPublisherLibraryViewerRouteImport.update({
    id: '/library-viewer',
    path: '/library-viewer',
    getParentRoute: () => LayoutPublisherRoute,
  } as any)
const LayoutPublisherLibraryRoute = LayoutPublisherLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => LayoutPublisherRoute,
} as any)
const LayoutPublisherDashboardRoute =
  LayoutPublisherDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutPublisherRoute,
  } as any)
const LayoutPublisherBookAssignmentsRoute =
  LayoutPublisherBookAssignmentsRouteImport.update({
    id: '/book-assignments',
    path: '/book-assignments',
    getParentRoute: () => LayoutPublisherRoute,
  } as any)
const LayoutMessagingConversationIdRoute =
  LayoutMessagingConversationIdRouteImport.update({
    id: '/messaging/$conversationId',
    path: '/messaging/$conversationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDreamaiVocabularyRoute = LayoutDreamaiVocabularyRouteImport.update({
  id: '/dreamai/vocabulary',
  path: '/dreamai/vocabulary',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDreamaiMaterialsRoute = LayoutDreamaiMaterialsRouteImport.update({
  id: '/dreamai/materials',
  path: '/dreamai/materials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDreamaiLibraryRoute = LayoutDreamaiLibraryRouteImport.update({
  id: '/dreamai/library',
  path: '/dreamai/library',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDreamaiGeneratorRoute = LayoutDreamaiGeneratorRouteImport.update({
  id: '/dreamai/generator',
  path: '/dreamai/generator',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminTeachersRoute = LayoutAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSupervisorsRoute = LayoutAdminSupervisorsRouteImport.update({
  id: '/supervisors',
  path: '/supervisors',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminStudentsRoute = LayoutAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSchoolsRoute = LayoutAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPublishersRoute = LayoutAdminPublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminLibraryViewerRoute =
  LayoutAdminLibraryViewerRouteImport.update({
    id: '/library-viewer',
    path: '/library-viewer',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminDashboardRoute = LayoutAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminBooksRoute = LayoutAdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminBenchmarksRoute = LayoutAdminBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAssignmentsRoute = LayoutAdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAiUsageRoute = LayoutAdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutTeacherMaterialsIndexRoute =
  LayoutTeacherMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherBooksIndexRoute = LayoutTeacherBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherAssignmentsIndexRoute =
  LayoutTeacherAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutTeacherAssignmentsRoute,
  } as any)
const LayoutTeacherAnalyticsIndexRoute =
  LayoutTeacherAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutStudentAssignmentsIndexRoute =
  LayoutStudentAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutStudentAssignmentsRoute,
  } as any)
const LayoutTeacherClassroomsClassIdRoute =
  LayoutTeacherClassroomsClassIdRouteImport.update({
    id: '/classrooms_/$classId',
    path: '/classrooms/$classId',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherBooksBookIdRoute =
  LayoutTeacherBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherAssignmentsPreviewRoute =
  LayoutTeacherAssignmentsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => LayoutTeacherAssignmentsRoute,
  } as any)
const LayoutTeacherAssignmentsAssignmentIdRoute =
  LayoutTeacherAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => LayoutTeacherAssignmentsRoute,
  } as any)
const LayoutTeacherAnalyticsSkillsRoute =
  LayoutTeacherAnalyticsSkillsRouteImport.update({
    id: '/analytics/skills',
    path: '/analytics/skills',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherAnalyticsStudentIdRoute =
  LayoutTeacherAnalyticsStudentIdRouteImport.update({
    id: '/analytics/$studentId',
    path: '/analytics/$studentId',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutStudentAssignmentsAssignmentIdRoute =
  LayoutStudentAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => LayoutStudentAssignmentsRoute,
  } as any)
const LayoutStudentAssignmentsAssignmentIdIndexRoute =
  LayoutStudentAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutStudentAssignmentsAssignmentIdRoute,
  } as any)
const LayoutStudentAssignmentsAssignmentIdSuccessRoute =
  LayoutStudentAssignmentsAssignmentIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => LayoutStudentAssignmentsAssignmentIdRoute,
  } as any)
const LayoutStudentAssignmentsAssignmentIdResultRoute =
  LayoutStudentAssignmentsAssignmentIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => LayoutStudentAssignmentsAssignmentIdRoute,
  } as any)
const LayoutStudentAssignmentsAssignmentIdPlayMultiRoute =
  LayoutStudentAssignmentsAssignmentIdPlayMultiRouteImport.update({
    id: '/play-multi',
    path: '/play-multi',
    getParentRoute: () => LayoutStudentAssignmentsAssignmentIdRoute,
  } as any)
const LayoutStudentAssignmentsAssignmentIdPlayRoute =
  LayoutStudentAssignmentsAssignmentIdPlayRouteImport.update({
    id: '/play',
    path: '/play',
    getParentRoute: () => LayoutStudentAssignmentsAssignmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/publisher': typeof LayoutPublisherRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/student': typeof LayoutStudentRouteWithChildren
  '/teacher': typeof LayoutTeacherRouteWithChildren
  '/viewer/$bookId': typeof ViewerBookIdRoute
  '/': typeof LayoutIndexRoute
  '/admin/ai-usage': typeof LayoutAdminAiUsageRoute
  '/admin/assignments': typeof LayoutAdminAssignmentsRoute
  '/admin/benchmarks': typeof LayoutAdminBenchmarksRoute
  '/admin/books': typeof LayoutAdminBooksRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/admin/library-viewer': typeof LayoutAdminLibraryViewerRoute
  '/admin/publishers': typeof LayoutAdminPublishersRoute
  '/admin/schools': typeof LayoutAdminSchoolsRoute
  '/admin/students': typeof LayoutAdminStudentsRoute
  '/admin/supervisors': typeof LayoutAdminSupervisorsRoute
  '/admin/teachers': typeof LayoutAdminTeachersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/dreamai/generator': typeof LayoutDreamaiGeneratorRoute
  '/dreamai/library': typeof LayoutDreamaiLibraryRoute
  '/dreamai/materials': typeof LayoutDreamaiMaterialsRoute
  '/dreamai/vocabulary': typeof LayoutDreamaiVocabularyRoute
  '/messaging/$conversationId': typeof LayoutMessagingConversationIdRoute
  '/publisher/book-assignments': typeof LayoutPublisherBookAssignmentsRoute
  '/publisher/dashboard': typeof LayoutPublisherDashboardRoute
  '/publisher/library': typeof LayoutPublisherLibraryRoute
  '/publisher/library-viewer': typeof LayoutPublisherLibraryViewerRoute
  '/publisher/schools': typeof LayoutPublisherSchoolsRoute
  '/publisher/teachers': typeof LayoutPublisherTeachersRoute
  '/student/announcements': typeof LayoutStudentAnnouncementsRoute
  '/student/assignments': typeof LayoutStudentAssignmentsRouteWithChildren
  '/student/calendar': typeof LayoutStudentCalendarRoute
  '/student/dashboard': typeof LayoutStudentDashboardRoute
  '/student/progress': typeof LayoutStudentProgressRoute
  '/student/reports': typeof LayoutStudentReportsRoute
  '/teacher/ai-materials': typeof LayoutTeacherAiMaterialsRoute
  '/teacher/announcements': typeof LayoutTeacherAnnouncementsRoute
  '/teacher/assignments': typeof LayoutTeacherAssignmentsRouteWithChildren
  '/teacher/calendar': typeof LayoutTeacherCalendarRoute
  '/teacher/classrooms': typeof LayoutTeacherClassroomsRoute
  '/teacher/dashboard': typeof LayoutTeacherDashboardRoute
  '/teacher/insights': typeof LayoutTeacherInsightsRoute
  '/teacher/library-viewer': typeof LayoutTeacherLibraryViewerRoute
  '/teacher/reports': typeof LayoutTeacherReportsRoute
  '/teacher/students': typeof LayoutTeacherStudentsRoute
  '/dreamai': typeof LayoutDreamaiIndexRoute
  '/messaging': typeof LayoutMessagingIndexRoute
  '/student/assignments/$assignmentId': typeof LayoutStudentAssignmentsAssignmentIdRouteWithChildren
  '/teacher/analytics/$studentId': typeof LayoutTeacherAnalyticsStudentIdRoute
  '/teacher/analytics/skills': typeof LayoutTeacherAnalyticsSkillsRoute
  '/teacher/assignments/$assignmentId': typeof LayoutTeacherAssignmentsAssignmentIdRoute
  '/teacher/assignments/preview': typeof LayoutTeacherAssignmentsPreviewRoute
  '/teacher/books/$bookId': typeof LayoutTeacherBooksBookIdRoute
  '/teacher/classrooms/$classId': typeof LayoutTeacherClassroomsClassIdRoute
  '/student/assignments/': typeof LayoutStudentAssignmentsIndexRoute
  '/teacher/analytics': typeof LayoutTeacherAnalyticsIndexRoute
  '/teacher/assignments/': typeof LayoutTeacherAssignmentsIndexRoute
  '/teacher/books': typeof LayoutTeacherBooksIndexRoute
  '/teacher/materials': typeof LayoutTeacherMaterialsIndexRoute
  '/student/assignments/$assignmentId/play': typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
  '/student/assignments/$assignmentId/play-multi': typeof LayoutStudentAssignmentsAssignmentIdPlayMultiRoute
  '/student/assignments/$assignmentId/result': typeof LayoutStudentAssignmentsAssignmentIdResultRoute
  '/student/assignments/$assignmentId/success': typeof LayoutStudentAssignmentsAssignmentIdSuccessRoute
  '/student/assignments/$assignmentId/': typeof LayoutStudentAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/publisher': typeof LayoutPublisherRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/student': typeof LayoutStudentRouteWithChildren
  '/teacher': typeof LayoutTeacherRouteWithChildren
  '/viewer/$bookId': typeof ViewerBookIdRoute
  '/': typeof LayoutIndexRoute
  '/admin/ai-usage': typeof LayoutAdminAiUsageRoute
  '/admin/assignments': typeof LayoutAdminAssignmentsRoute
  '/admin/benchmarks': typeof LayoutAdminBenchmarksRoute
  '/admin/books': typeof LayoutAdminBooksRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/admin/library-viewer': typeof LayoutAdminLibraryViewerRoute
  '/admin/publishers': typeof LayoutAdminPublishersRoute
  '/admin/schools': typeof LayoutAdminSchoolsRoute
  '/admin/students': typeof LayoutAdminStudentsRoute
  '/admin/supervisors': typeof LayoutAdminSupervisorsRoute
  '/admin/teachers': typeof LayoutAdminTeachersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/dreamai/generator': typeof LayoutDreamaiGeneratorRoute
  '/dreamai/library': typeof LayoutDreamaiLibraryRoute
  '/dreamai/materials': typeof LayoutDreamaiMaterialsRoute
  '/dreamai/vocabulary': typeof LayoutDreamaiVocabularyRoute
  '/messaging/$conversationId': typeof LayoutMessagingConversationIdRoute
  '/publisher/book-assignments': typeof LayoutPublisherBookAssignmentsRoute
  '/publisher/dashboard': typeof LayoutPublisherDashboardRoute
  '/publisher/library': typeof LayoutPublisherLibraryRoute
  '/publisher/library-viewer': typeof LayoutPublisherLibraryViewerRoute
  '/publisher/schools': typeof LayoutPublisherSchoolsRoute
  '/publisher/teachers': typeof LayoutPublisherTeachersRoute
  '/student/announcements': typeof LayoutStudentAnnouncementsRoute
  '/student/calendar': typeof LayoutStudentCalendarRoute
  '/student/dashboard': typeof LayoutStudentDashboardRoute
  '/student/progress': typeof LayoutStudentProgressRoute
  '/student/reports': typeof LayoutStudentReportsRoute
  '/teacher/ai-materials': typeof LayoutTeacherAiMaterialsRoute
  '/teacher/announcements': typeof LayoutTeacherAnnouncementsRoute
  '/teacher/calendar': typeof LayoutTeacherCalendarRoute
  '/teacher/classrooms': typeof LayoutTeacherClassroomsRoute
  '/teacher/dashboard': typeof LayoutTeacherDashboardRoute
  '/teacher/insights': typeof LayoutTeacherInsightsRoute
  '/teacher/library-viewer': typeof LayoutTeacherLibraryViewerRoute
  '/teacher/reports': typeof LayoutTeacherReportsRoute
  '/teacher/students': typeof LayoutTeacherStudentsRoute
  '/dreamai': typeof LayoutDreamaiIndexRoute
  '/messaging': typeof LayoutMessagingIndexRoute
  '/teacher/analytics/$studentId': typeof LayoutTeacherAnalyticsStudentIdRoute
  '/teacher/analytics/skills': typeof LayoutTeacherAnalyticsSkillsRoute
  '/teacher/assignments/$assignmentId': typeof LayoutTeacherAssignmentsAssignmentIdRoute
  '/teacher/assignments/preview': typeof LayoutTeacherAssignmentsPreviewRoute
  '/teacher/books/$bookId': typeof LayoutTeacherBooksBookIdRoute
  '/teacher/classrooms/$classId': typeof LayoutTeacherClassroomsClassIdRoute
  '/student/assignments': typeof LayoutStudentAssignmentsIndexRoute
  '/teacher/analytics': typeof LayoutTeacherAnalyticsIndexRoute
  '/teacher/assignments': typeof LayoutTeacherAssignmentsIndexRoute
  '/teacher/books': typeof LayoutTeacherBooksIndexRoute
  '/teacher/materials': typeof LayoutTeacherMaterialsIndexRoute
  '/student/assignments/$assignmentId/play': typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
  '/student/assignments/$assignmentId/play-multi': typeof LayoutStudentAssignmentsAssignmentIdPlayMultiRoute
  '/student/assignments/$assignmentId/result': typeof LayoutStudentAssignmentsAssignmentIdResultRoute
  '/student/assignments/$assignmentId/success': typeof LayoutStudentAssignmentsAssignmentIdSuccessRoute
  '/student/assignments/$assignmentId': typeof LayoutStudentAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/publisher': typeof LayoutPublisherRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/student': typeof LayoutStudentRouteWithChildren
  '/_layout/teacher': typeof LayoutTeacherRouteWithChildren
  '/viewer/$bookId': typeof ViewerBookIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/ai-usage': typeof LayoutAdminAiUsageRoute
  '/_layout/admin/assignments': typeof LayoutAdminAssignmentsRoute
  '/_layout/admin/benchmarks': typeof LayoutAdminBenchmarksRoute
  '/_layout/admin/books': typeof LayoutAdminBooksRoute
  '/_layout/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/_layout/admin/library-viewer': typeof LayoutAdminLibraryViewerRoute
  '/_layout/admin/publishers': typeof LayoutAdminPublishersRoute
  '/_layout/admin/schools': typeof LayoutAdminSchoolsRoute
  '/_layout/admin/students': typeof LayoutAdminStudentsRoute
  '/_layout/admin/supervisors': typeof LayoutAdminSupervisorsRoute
  '/_layout/admin/teachers': typeof LayoutAdminTeachersRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/dreamai/generator': typeof LayoutDreamaiGeneratorRoute
  '/_layout/dreamai/library': typeof LayoutDreamaiLibraryRoute
  '/_layout/dreamai/materials': typeof LayoutDreamaiMaterialsRoute
  '/_layout/dreamai/vocabulary': typeof LayoutDreamaiVocabularyRoute
  '/_layout/messaging/$conversationId': typeof LayoutMessagingConversationIdRoute
  '/_layout/publisher/book-assignments': typeof LayoutPublisherBookAssignmentsRoute
  '/_layout/publisher/dashboard': typeof LayoutPublisherDashboardRoute
  '/_layout/publisher/library': typeof LayoutPublisherLibraryRoute
  '/_layout/publisher/library-viewer': typeof LayoutPublisherLibraryViewerRoute
  '/_layout/publisher/schools': typeof LayoutPublisherSchoolsRoute
  '/_layout/publisher/teachers': typeof LayoutPublisherTeachersRoute
  '/_layout/student/announcements': typeof LayoutStudentAnnouncementsRoute
  '/_layout/student/assignments': typeof LayoutStudentAssignmentsRouteWithChildren
  '/_layout/student/calendar': typeof LayoutStudentCalendarRoute
  '/_layout/student/dashboard': typeof LayoutStudentDashboardRoute
  '/_layout/student/progress': typeof LayoutStudentProgressRoute
  '/_layout/student/reports': typeof LayoutStudentReportsRoute
  '/_layout/teacher/ai-materials': typeof LayoutTeacherAiMaterialsRoute
  '/_layout/teacher/announcements': typeof LayoutTeacherAnnouncementsRoute
  '/_layout/teacher/assignments': typeof LayoutTeacherAssignmentsRouteWithChildren
  '/_layout/teacher/calendar': typeof LayoutTeacherCalendarRoute
  '/_layout/teacher/classrooms': typeof LayoutTeacherClassroomsRoute
  '/_layout/teacher/dashboard': typeof LayoutTeacherDashboardRoute
  '/_layout/teacher/insights': typeof LayoutTeacherInsightsRoute
  '/_layout/teacher/library-viewer': typeof LayoutTeacherLibraryViewerRoute
  '/_layout/teacher/reports': typeof LayoutTeacherReportsRoute
  '/_layout/teacher/students': typeof LayoutTeacherStudentsRoute
  '/_layout/dreamai/': typeof LayoutDreamaiIndexRoute
  '/_layout/messaging/': typeof LayoutMessagingIndexRoute
  '/_layout/student/assignments/$assignmentId': typeof LayoutStudentAssignmentsAssignmentIdRouteWithChildren
  '/_layout/teacher/analytics/$studentId': typeof LayoutTeacherAnalyticsStudentIdRoute
  '/_layout/teacher/analytics/skills': typeof LayoutTeacherAnalyticsSkillsRoute
  '/_layout/teacher/assignments/$assignmentId': typeof LayoutTeacherAssignmentsAssignmentIdRoute
  '/_layout/teacher/assignments/preview': typeof LayoutTeacherAssignmentsPreviewRoute
  '/_layout/teacher/books/$bookId': typeof LayoutTeacherBooksBookIdRoute
  '/_layout/teacher/classrooms_/$classId': typeof LayoutTeacherClassroomsClassIdRoute
  '/_layout/student/assignments/': typeof LayoutStudentAssignmentsIndexRoute
  '/_layout/teacher/analytics/': typeof LayoutTeacherAnalyticsIndexRoute
  '/_layout/teacher/assignments/': typeof LayoutTeacherAssignmentsIndexRoute
  '/_layout/teacher/books/': typeof LayoutTeacherBooksIndexRoute
  '/_layout/teacher/materials/': typeof LayoutTeacherMaterialsIndexRoute
  '/_layout/student/assignments/$assignmentId/play': typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
  '/_layout/student/assignments/$assignmentId/play-multi': typeof LayoutStudentAssignmentsAssignmentIdPlayMultiRoute
  '/_layout/student/assignments/$assignmentId/result': typeof LayoutStudentAssignmentsAssignmentIdResultRoute
  '/_layout/student/assignments/$assignmentId/success': typeof LayoutStudentAssignmentsAssignmentIdSuccessRoute
  '/_layout/student/assignments/$assignmentId/': typeof LayoutStudentAssignmentsAssignmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/change-password'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/notifications'
    | '/publisher'
    | '/settings'
    | '/student'
    | '/teacher'
    | '/viewer/$bookId'
    | '/'
    | '/admin/ai-usage'
    | '/admin/assignments'
    | '/admin/benchmarks'
    | '/admin/books'
    | '/admin/dashboard'
    | '/admin/library-viewer'
    | '/admin/publishers'
    | '/admin/schools'
    | '/admin/students'
    | '/admin/supervisors'
    | '/admin/teachers'
    | '/admin/users'
    | '/dreamai/generator'
    | '/dreamai/library'
    | '/dreamai/materials'
    | '/dreamai/vocabulary'
    | '/messaging/$conversationId'
    | '/publisher/book-assignments'
    | '/publisher/dashboard'
    | '/publisher/library'
    | '/publisher/library-viewer'
    | '/publisher/schools'
    | '/publisher/teachers'
    | '/student/announcements'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/dashboard'
    | '/student/progress'
    | '/student/reports'
    | '/teacher/ai-materials'
    | '/teacher/announcements'
    | '/teacher/assignments'
    | '/teacher/calendar'
    | '/teacher/classrooms'
    | '/teacher/dashboard'
    | '/teacher/insights'
    | '/teacher/library-viewer'
    | '/teacher/reports'
    | '/teacher/students'
    | '/dreamai'
    | '/messaging'
    | '/student/assignments/$assignmentId'
    | '/teacher/analytics/$studentId'
    | '/teacher/analytics/skills'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/assignments/preview'
    | '/teacher/books/$bookId'
    | '/teacher/classrooms/$classId'
    | '/student/assignments/'
    | '/teacher/analytics'
    | '/teacher/assignments/'
    | '/teacher/books'
    | '/teacher/materials'
    | '/student/assignments/$assignmentId/play'
    | '/student/assignments/$assignmentId/play-multi'
    | '/student/assignments/$assignmentId/result'
    | '/student/assignments/$assignmentId/success'
    | '/student/assignments/$assignmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/notifications'
    | '/publisher'
    | '/settings'
    | '/student'
    | '/teacher'
    | '/viewer/$bookId'
    | '/'
    | '/admin/ai-usage'
    | '/admin/assignments'
    | '/admin/benchmarks'
    | '/admin/books'
    | '/admin/dashboard'
    | '/admin/library-viewer'
    | '/admin/publishers'
    | '/admin/schools'
    | '/admin/students'
    | '/admin/supervisors'
    | '/admin/teachers'
    | '/admin/users'
    | '/dreamai/generator'
    | '/dreamai/library'
    | '/dreamai/materials'
    | '/dreamai/vocabulary'
    | '/messaging/$conversationId'
    | '/publisher/book-assignments'
    | '/publisher/dashboard'
    | '/publisher/library'
    | '/publisher/library-viewer'
    | '/publisher/schools'
    | '/publisher/teachers'
    | '/student/announcements'
    | '/student/calendar'
    | '/student/dashboard'
    | '/student/progress'
    | '/student/reports'
    | '/teacher/ai-materials'
    | '/teacher/announcements'
    | '/teacher/calendar'
    | '/teacher/classrooms'
    | '/teacher/dashboard'
    | '/teacher/insights'
    | '/teacher/library-viewer'
    | '/teacher/reports'
    | '/teacher/students'
    | '/dreamai'
    | '/messaging'
    | '/teacher/analytics/$studentId'
    | '/teacher/analytics/skills'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/assignments/preview'
    | '/teacher/books/$bookId'
    | '/teacher/classrooms/$classId'
    | '/student/assignments'
    | '/teacher/analytics'
    | '/teacher/assignments'
    | '/teacher/books'
    | '/teacher/materials'
    | '/student/assignments/$assignmentId/play'
    | '/student/assignments/$assignmentId/play-multi'
    | '/student/assignments/$assignmentId/result'
    | '/student/assignments/$assignmentId/success'
    | '/student/assignments/$assignmentId'
  id:
    | '__root__'
    | '/_layout'
    | '/change-password'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/notifications'
    | '/_layout/publisher'
    | '/_layout/settings'
    | '/_layout/student'
    | '/_layout/teacher'
    | '/viewer/$bookId'
    | '/_layout/'
    | '/_layout/admin/ai-usage'
    | '/_layout/admin/assignments'
    | '/_layout/admin/benchmarks'
    | '/_layout/admin/books'
    | '/_layout/admin/dashboard'
    | '/_layout/admin/library-viewer'
    | '/_layout/admin/publishers'
    | '/_layout/admin/schools'
    | '/_layout/admin/students'
    | '/_layout/admin/supervisors'
    | '/_layout/admin/teachers'
    | '/_layout/admin/users'
    | '/_layout/dreamai/generator'
    | '/_layout/dreamai/library'
    | '/_layout/dreamai/materials'
    | '/_layout/dreamai/vocabulary'
    | '/_layout/messaging/$conversationId'
    | '/_layout/publisher/book-assignments'
    | '/_layout/publisher/dashboard'
    | '/_layout/publisher/library'
    | '/_layout/publisher/library-viewer'
    | '/_layout/publisher/schools'
    | '/_layout/publisher/teachers'
    | '/_layout/student/announcements'
    | '/_layout/student/assignments'
    | '/_layout/student/calendar'
    | '/_layout/student/dashboard'
    | '/_layout/student/progress'
    | '/_layout/student/reports'
    | '/_layout/teacher/ai-materials'
    | '/_layout/teacher/announcements'
    | '/_layout/teacher/assignments'
    | '/_layout/teacher/calendar'
    | '/_layout/teacher/classrooms'
    | '/_layout/teacher/dashboard'
    | '/_layout/teacher/insights'
    | '/_layout/teacher/library-viewer'
    | '/_layout/teacher/reports'
    | '/_layout/teacher/students'
    | '/_layout/dreamai/'
    | '/_layout/messaging/'
    | '/_layout/student/assignments/$assignmentId'
    | '/_layout/teacher/analytics/$studentId'
    | '/_layout/teacher/analytics/skills'
    | '/_layout/teacher/assignments/$assignmentId'
    | '/_layout/teacher/assignments/preview'
    | '/_layout/teacher/books/$bookId'
    | '/_layout/teacher/classrooms_/$classId'
    | '/_layout/student/assignments/'
    | '/_layout/teacher/analytics/'
    | '/_layout/teacher/assignments/'
    | '/_layout/teacher/books/'
    | '/_layout/teacher/materials/'
    | '/_layout/student/assignments/$assignmentId/play'
    | '/_layout/student/assignments/$assignmentId/play-multi'
    | '/_layout/student/assignments/$assignmentId/result'
    | '/_layout/student/assignments/$assignmentId/success'
    | '/_layout/student/assignments/$assignmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ViewerBookIdRoute: typeof ViewerBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/viewer/$bookId': {
      id: '/viewer/$bookId'
      path: '/viewer/$bookId'
      fullPath: '/viewer/$bookId'
      preLoaderRoute: typeof ViewerBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/teacher': {
      id: '/_layout/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof LayoutTeacherRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/student': {
      id: '/_layout/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof LayoutStudentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/publisher': {
      id: '/_layout/publisher'
      path: '/publisher'
      fullPath: '/publisher'
      preLoaderRoute: typeof LayoutPublisherRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/messaging/': {
      id: '/_layout/messaging/'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof LayoutMessagingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dreamai/': {
      id: '/_layout/dreamai/'
      path: '/dreamai'
      fullPath: '/dreamai'
      preLoaderRoute: typeof LayoutDreamaiIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teacher/students': {
      id: '/_layout/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof LayoutTeacherStudentsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/reports': {
      id: '/_layout/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof LayoutTeacherReportsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/library-viewer': {
      id: '/_layout/teacher/library-viewer'
      path: '/library-viewer'
      fullPath: '/teacher/library-viewer'
      preLoaderRoute: typeof LayoutTeacherLibraryViewerRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/insights': {
      id: '/_layout/teacher/insights'
      path: '/insights'
      fullPath: '/teacher/insights'
      preLoaderRoute: typeof LayoutTeacherInsightsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/dashboard': {
      id: '/_layout/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof LayoutTeacherDashboardRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/classrooms': {
      id: '/_layout/teacher/classrooms'
      path: '/classrooms'
      fullPath: '/teacher/classrooms'
      preLoaderRoute: typeof LayoutTeacherClassroomsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/calendar': {
      id: '/_layout/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof LayoutTeacherCalendarRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/assignments': {
      id: '/_layout/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof LayoutTeacherAssignmentsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/announcements': {
      id: '/_layout/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof LayoutTeacherAnnouncementsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/ai-materials': {
      id: '/_layout/teacher/ai-materials'
      path: '/ai-materials'
      fullPath: '/teacher/ai-materials'
      preLoaderRoute: typeof LayoutTeacherAiMaterialsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/student/reports': {
      id: '/_layout/student/reports'
      path: '/reports'
      fullPath: '/student/reports'
      preLoaderRoute: typeof LayoutStudentReportsRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/progress': {
      id: '/_layout/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof LayoutStudentProgressRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/dashboard': {
      id: '/_layout/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof LayoutStudentDashboardRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/calendar': {
      id: '/_layout/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof LayoutStudentCalendarRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/assignments': {
      id: '/_layout/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof LayoutStudentAssignmentsRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/announcements': {
      id: '/_layout/student/announcements'
      path: '/announcements'
      fullPath: '/student/announcements'
      preLoaderRoute: typeof LayoutStudentAnnouncementsRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/publisher/teachers': {
      id: '/_layout/publisher/teachers'
      path: '/teachers'
      fullPath: '/publisher/teachers'
      preLoaderRoute: typeof LayoutPublisherTeachersRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/schools': {
      id: '/_layout/publisher/schools'
      path: '/schools'
      fullPath: '/publisher/schools'
      preLoaderRoute: typeof LayoutPublisherSchoolsRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/library-viewer': {
      id: '/_layout/publisher/library-viewer'
      path: '/library-viewer'
      fullPath: '/publisher/library-viewer'
      preLoaderRoute: typeof LayoutPublisherLibraryViewerRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/library': {
      id: '/_layout/publisher/library'
      path: '/library'
      fullPath: '/publisher/library'
      preLoaderRoute: typeof LayoutPublisherLibraryRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/dashboard': {
      id: '/_layout/publisher/dashboard'
      path: '/dashboard'
      fullPath: '/publisher/dashboard'
      preLoaderRoute: typeof LayoutPublisherDashboardRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/book-assignments': {
      id: '/_layout/publisher/book-assignments'
      path: '/book-assignments'
      fullPath: '/publisher/book-assignments'
      preLoaderRoute: typeof LayoutPublisherBookAssignmentsRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/messaging/$conversationId': {
      id: '/_layout/messaging/$conversationId'
      path: '/messaging/$conversationId'
      fullPath: '/messaging/$conversationId'
      preLoaderRoute: typeof LayoutMessagingConversationIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dreamai/vocabulary': {
      id: '/_layout/dreamai/vocabulary'
      path: '/dreamai/vocabulary'
      fullPath: '/dreamai/vocabulary'
      preLoaderRoute: typeof LayoutDreamaiVocabularyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dreamai/materials': {
      id: '/_layout/dreamai/materials'
      path: '/dreamai/materials'
      fullPath: '/dreamai/materials'
      preLoaderRoute: typeof LayoutDreamaiMaterialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dreamai/library': {
      id: '/_layout/dreamai/library'
      path: '/dreamai/library'
      fullPath: '/dreamai/library'
      preLoaderRoute: typeof LayoutDreamaiLibraryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dreamai/generator': {
      id: '/_layout/dreamai/generator'
      path: '/dreamai/generator'
      fullPath: '/dreamai/generator'
      preLoaderRoute: typeof LayoutDreamaiGeneratorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/teachers': {
      id: '/_layout/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof LayoutAdminTeachersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/supervisors': {
      id: '/_layout/admin/supervisors'
      path: '/supervisors'
      fullPath: '/admin/supervisors'
      preLoaderRoute: typeof LayoutAdminSupervisorsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/students': {
      id: '/_layout/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof LayoutAdminStudentsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/schools': {
      id: '/_layout/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof LayoutAdminSchoolsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/publishers': {
      id: '/_layout/admin/publishers'
      path: '/publishers'
      fullPath: '/admin/publishers'
      preLoaderRoute: typeof LayoutAdminPublishersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/library-viewer': {
      id: '/_layout/admin/library-viewer'
      path: '/library-viewer'
      fullPath: '/admin/library-viewer'
      preLoaderRoute: typeof LayoutAdminLibraryViewerRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/dashboard': {
      id: '/_layout/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof LayoutAdminDashboardRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/books': {
      id: '/_layout/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof LayoutAdminBooksRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/benchmarks': {
      id: '/_layout/admin/benchmarks'
      path: '/benchmarks'
      fullPath: '/admin/benchmarks'
      preLoaderRoute: typeof LayoutAdminBenchmarksRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/assignments': {
      id: '/_layout/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof LayoutAdminAssignmentsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/ai-usage': {
      id: '/_layout/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof LayoutAdminAiUsageRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/teacher/materials/': {
      id: '/_layout/teacher/materials/'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof LayoutTeacherMaterialsIndexRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/books/': {
      id: '/_layout/teacher/books/'
      path: '/books'
      fullPath: '/teacher/books'
      preLoaderRoute: typeof LayoutTeacherBooksIndexRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/assignments/': {
      id: '/_layout/teacher/assignments/'
      path: '/'
      fullPath: '/teacher/assignments/'
      preLoaderRoute: typeof LayoutTeacherAssignmentsIndexRouteImport
      parentRoute: typeof LayoutTeacherAssignmentsRoute
    }
    '/_layout/teacher/analytics/': {
      id: '/_layout/teacher/analytics/'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof LayoutTeacherAnalyticsIndexRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/student/assignments/': {
      id: '/_layout/student/assignments/'
      path: '/'
      fullPath: '/student/assignments/'
      preLoaderRoute: typeof LayoutStudentAssignmentsIndexRouteImport
      parentRoute: typeof LayoutStudentAssignmentsRoute
    }
    '/_layout/teacher/classrooms_/$classId': {
      id: '/_layout/teacher/classrooms_/$classId'
      path: '/classrooms/$classId'
      fullPath: '/teacher/classrooms/$classId'
      preLoaderRoute: typeof LayoutTeacherClassroomsClassIdRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/books/$bookId': {
      id: '/_layout/teacher/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/teacher/books/$bookId'
      preLoaderRoute: typeof LayoutTeacherBooksBookIdRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/assignments/preview': {
      id: '/_layout/teacher/assignments/preview'
      path: '/preview'
      fullPath: '/teacher/assignments/preview'
      preLoaderRoute: typeof LayoutTeacherAssignmentsPreviewRouteImport
      parentRoute: typeof LayoutTeacherAssignmentsRoute
    }
    '/_layout/teacher/assignments/$assignmentId': {
      id: '/_layout/teacher/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/teacher/assignments/$assignmentId'
      preLoaderRoute: typeof LayoutTeacherAssignmentsAssignmentIdRouteImport
      parentRoute: typeof LayoutTeacherAssignmentsRoute
    }
    '/_layout/teacher/analytics/skills': {
      id: '/_layout/teacher/analytics/skills'
      path: '/analytics/skills'
      fullPath: '/teacher/analytics/skills'
      preLoaderRoute: typeof LayoutTeacherAnalyticsSkillsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/analytics/$studentId': {
      id: '/_layout/teacher/analytics/$studentId'
      path: '/analytics/$studentId'
      fullPath: '/teacher/analytics/$studentId'
      preLoaderRoute: typeof LayoutTeacherAnalyticsStudentIdRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/student/assignments/$assignmentId': {
      id: '/_layout/student/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/student/assignments/$assignmentId'
      preLoaderRoute: typeof LayoutStudentAssignmentsAssignmentIdRouteImport
      parentRoute: typeof LayoutStudentAssignmentsRoute
    }
    '/_layout/student/assignments/$assignmentId/': {
      id: '/_layout/student/assignments/$assignmentId/'
      path: '/'
      fullPath: '/student/assignments/$assignmentId/'
      preLoaderRoute: typeof LayoutStudentAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof LayoutStudentAssignmentsAssignmentIdRoute
    }
    '/_layout/student/assignments/$assignmentId/success': {
      id: '/_layout/student/assignments/$assignmentId/success'
      path: '/success'
      fullPath: '/student/assignments/$assignmentId/success'
      preLoaderRoute: typeof LayoutStudentAssignmentsAssignmentIdSuccessRouteImport
      parentRoute: typeof LayoutStudentAssignmentsAssignmentIdRoute
    }
    '/_layout/student/assignments/$assignmentId/result': {
      id: '/_layout/student/assignments/$assignmentId/result'
      path: '/result'
      fullPath: '/student/assignments/$assignmentId/result'
      preLoaderRoute: typeof LayoutStudentAssignmentsAssignmentIdResultRouteImport
      parentRoute: typeof LayoutStudentAssignmentsAssignmentIdRoute
    }
    '/_layout/student/assignments/$assignmentId/play-multi': {
      id: '/_layout/student/assignments/$assignmentId/play-multi'
      path: '/play-multi'
      fullPath: '/student/assignments/$assignmentId/play-multi'
      preLoaderRoute: typeof LayoutStudentAssignmentsAssignmentIdPlayMultiRouteImport
      parentRoute: typeof LayoutStudentAssignmentsAssignmentIdRoute
    }
    '/_layout/student/assignments/$assignmentId/play': {
      id: '/_layout/student/assignments/$assignmentId/play'
      path: '/play'
      fullPath: '/student/assignments/$assignmentId/play'
      preLoaderRoute: typeof LayoutStudentAssignmentsAssignmentIdPlayRouteImport
      parentRoute: typeof LayoutStudentAssignmentsAssignmentIdRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAiUsageRoute: typeof LayoutAdminAiUsageRoute
  LayoutAdminAssignmentsRoute: typeof LayoutAdminAssignmentsRoute
  LayoutAdminBenchmarksRoute: typeof LayoutAdminBenchmarksRoute
  LayoutAdminBooksRoute: typeof LayoutAdminBooksRoute
  LayoutAdminDashboardRoute: typeof LayoutAdminDashboardRoute
  LayoutAdminLibraryViewerRoute: typeof LayoutAdminLibraryViewerRoute
  LayoutAdminPublishersRoute: typeof LayoutAdminPublishersRoute
  LayoutAdminSchoolsRoute: typeof LayoutAdminSchoolsRoute
  LayoutAdminStudentsRoute: typeof LayoutAdminStudentsRoute
  LayoutAdminSupervisorsRoute: typeof LayoutAdminSupervisorsRoute
  LayoutAdminTeachersRoute: typeof LayoutAdminTeachersRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAiUsageRoute: LayoutAdminAiUsageRoute,
  LayoutAdminAssignmentsRoute: LayoutAdminAssignmentsRoute,
  LayoutAdminBenchmarksRoute: LayoutAdminBenchmarksRoute,
  LayoutAdminBooksRoute: LayoutAdminBooksRoute,
  LayoutAdminDashboardRoute: LayoutAdminDashboardRoute,
  LayoutAdminLibraryViewerRoute: LayoutAdminLibraryViewerRoute,
  LayoutAdminPublishersRoute: LayoutAdminPublishersRoute,
  LayoutAdminSchoolsRoute: LayoutAdminSchoolsRoute,
  LayoutAdminStudentsRoute: LayoutAdminStudentsRoute,
  LayoutAdminSupervisorsRoute: LayoutAdminSupervisorsRoute,
  LayoutAdminTeachersRoute: LayoutAdminTeachersRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutPublisherRouteChildren {
  LayoutPublisherBookAssignmentsRoute: typeof LayoutPublisherBookAssignmentsRoute
  LayoutPublisherDashboardRoute: typeof LayoutPublisherDashboardRoute
  LayoutPublisherLibraryRoute: typeof LayoutPublisherLibraryRoute
  LayoutPublisherLibraryViewerRoute: typeof LayoutPublisherLibraryViewerRoute
  LayoutPublisherSchoolsRoute: typeof LayoutPublisherSchoolsRoute
  LayoutPublisherTeachersRoute: typeof LayoutPublisherTeachersRoute
}

const LayoutPublisherRouteChildren: LayoutPublisherRouteChildren = {
  LayoutPublisherBookAssignmentsRoute: LayoutPublisherBookAssignmentsRoute,
  LayoutPublisherDashboardRoute: LayoutPublisherDashboardRoute,
  LayoutPublisherLibraryRoute: LayoutPublisherLibraryRoute,
  LayoutPublisherLibraryViewerRoute: LayoutPublisherLibraryViewerRoute,
  LayoutPublisherSchoolsRoute: LayoutPublisherSchoolsRoute,
  LayoutPublisherTeachersRoute: LayoutPublisherTeachersRoute,
}

const LayoutPublisherRouteWithChildren = LayoutPublisherRoute._addFileChildren(
  LayoutPublisherRouteChildren,
)

interface LayoutStudentAssignmentsAssignmentIdRouteChildren {
  LayoutStudentAssignmentsAssignmentIdPlayRoute: typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
  LayoutStudentAssignmentsAssignmentIdPlayMultiRoute: typeof LayoutStudentAssignmentsAssignmentIdPlayMultiRoute
  LayoutStudentAssignmentsAssignmentIdResultRoute: typeof LayoutStudentAssignmentsAssignmentIdResultRoute
  LayoutStudentAssignmentsAssignmentIdSuccessRoute: typeof LayoutStudentAssignmentsAssignmentIdSuccessRoute
  LayoutStudentAssignmentsAssignmentIdIndexRoute: typeof LayoutStudentAssignmentsAssignmentIdIndexRoute
}

const LayoutStudentAssignmentsAssignmentIdRouteChildren: LayoutStudentAssignmentsAssignmentIdRouteChildren =
  {
    LayoutStudentAssignmentsAssignmentIdPlayRoute:
      LayoutStudentAssignmentsAssignmentIdPlayRoute,
    LayoutStudentAssignmentsAssignmentIdPlayMultiRoute:
      LayoutStudentAssignmentsAssignmentIdPlayMultiRoute,
    LayoutStudentAssignmentsAssignmentIdResultRoute:
      LayoutStudentAssignmentsAssignmentIdResultRoute,
    LayoutStudentAssignmentsAssignmentIdSuccessRoute:
      LayoutStudentAssignmentsAssignmentIdSuccessRoute,
    LayoutStudentAssignmentsAssignmentIdIndexRoute:
      LayoutStudentAssignmentsAssignmentIdIndexRoute,
  }

const LayoutStudentAssignmentsAssignmentIdRouteWithChildren =
  LayoutStudentAssignmentsAssignmentIdRoute._addFileChildren(
    LayoutStudentAssignmentsAssignmentIdRouteChildren,
  )

interface LayoutStudentAssignmentsRouteChildren {
  LayoutStudentAssignmentsAssignmentIdRoute: typeof LayoutStudentAssignmentsAssignmentIdRouteWithChildren
  LayoutStudentAssignmentsIndexRoute: typeof LayoutStudentAssignmentsIndexRoute
}

const LayoutStudentAssignmentsRouteChildren: LayoutStudentAssignmentsRouteChildren =
  {
    LayoutStudentAssignmentsAssignmentIdRoute:
      LayoutStudentAssignmentsAssignmentIdRouteWithChildren,
    LayoutStudentAssignmentsIndexRoute: LayoutStudentAssignmentsIndexRoute,
  }

const LayoutStudentAssignmentsRouteWithChildren =
  LayoutStudentAssignmentsRoute._addFileChildren(
    LayoutStudentAssignmentsRouteChildren,
  )

interface LayoutStudentRouteChildren {
  LayoutStudentAnnouncementsRoute: typeof LayoutStudentAnnouncementsRoute
  LayoutStudentAssignmentsRoute: typeof LayoutStudentAssignmentsRouteWithChildren
  LayoutStudentCalendarRoute: typeof LayoutStudentCalendarRoute
  LayoutStudentDashboardRoute: typeof LayoutStudentDashboardRoute
  LayoutStudentProgressRoute: typeof LayoutStudentProgressRoute
  LayoutStudentReportsRoute: typeof LayoutStudentReportsRoute
}

const LayoutStudentRouteChildren: LayoutStudentRouteChildren = {
  LayoutStudentAnnouncementsRoute: LayoutStudentAnnouncementsRoute,
  LayoutStudentAssignmentsRoute: LayoutStudentAssignmentsRouteWithChildren,
  LayoutStudentCalendarRoute: LayoutStudentCalendarRoute,
  LayoutStudentDashboardRoute: LayoutStudentDashboardRoute,
  LayoutStudentProgressRoute: LayoutStudentProgressRoute,
  LayoutStudentReportsRoute: LayoutStudentReportsRoute,
}

const LayoutStudentRouteWithChildren = LayoutStudentRoute._addFileChildren(
  LayoutStudentRouteChildren,
)

interface LayoutTeacherAssignmentsRouteChildren {
  LayoutTeacherAssignmentsAssignmentIdRoute: typeof LayoutTeacherAssignmentsAssignmentIdRoute
  LayoutTeacherAssignmentsPreviewRoute: typeof LayoutTeacherAssignmentsPreviewRoute
  LayoutTeacherAssignmentsIndexRoute: typeof LayoutTeacherAssignmentsIndexRoute
}

const LayoutTeacherAssignmentsRouteChildren: LayoutTeacherAssignmentsRouteChildren =
  {
    LayoutTeacherAssignmentsAssignmentIdRoute:
      LayoutTeacherAssignmentsAssignmentIdRoute,
    LayoutTeacherAssignmentsPreviewRoute: LayoutTeacherAssignmentsPreviewRoute,
    LayoutTeacherAssignmentsIndexRoute: LayoutTeacherAssignmentsIndexRoute,
  }

const LayoutTeacherAssignmentsRouteWithChildren =
  LayoutTeacherAssignmentsRoute._addFileChildren(
    LayoutTeacherAssignmentsRouteChildren,
  )

interface LayoutTeacherRouteChildren {
  LayoutTeacherAiMaterialsRoute: typeof LayoutTeacherAiMaterialsRoute
  LayoutTeacherAnnouncementsRoute: typeof LayoutTeacherAnnouncementsRoute
  LayoutTeacherAssignmentsRoute: typeof LayoutTeacherAssignmentsRouteWithChildren
  LayoutTeacherCalendarRoute: typeof LayoutTeacherCalendarRoute
  LayoutTeacherClassroomsRoute: typeof LayoutTeacherClassroomsRoute
  LayoutTeacherDashboardRoute: typeof LayoutTeacherDashboardRoute
  LayoutTeacherInsightsRoute: typeof LayoutTeacherInsightsRoute
  LayoutTeacherLibraryViewerRoute: typeof LayoutTeacherLibraryViewerRoute
  LayoutTeacherReportsRoute: typeof LayoutTeacherReportsRoute
  LayoutTeacherStudentsRoute: typeof LayoutTeacherStudentsRoute
  LayoutTeacherAnalyticsStudentIdRoute: typeof LayoutTeacherAnalyticsStudentIdRoute
  LayoutTeacherAnalyticsSkillsRoute: typeof LayoutTeacherAnalyticsSkillsRoute
  LayoutTeacherBooksBookIdRoute: typeof LayoutTeacherBooksBookIdRoute
  LayoutTeacherClassroomsClassIdRoute: typeof LayoutTeacherClassroomsClassIdRoute
  LayoutTeacherAnalyticsIndexRoute: typeof LayoutTeacherAnalyticsIndexRoute
  LayoutTeacherBooksIndexRoute: typeof LayoutTeacherBooksIndexRoute
  LayoutTeacherMaterialsIndexRoute: typeof LayoutTeacherMaterialsIndexRoute
}

const LayoutTeacherRouteChildren: LayoutTeacherRouteChildren = {
  LayoutTeacherAiMaterialsRoute: LayoutTeacherAiMaterialsRoute,
  LayoutTeacherAnnouncementsRoute: LayoutTeacherAnnouncementsRoute,
  LayoutTeacherAssignmentsRoute: LayoutTeacherAssignmentsRouteWithChildren,
  LayoutTeacherCalendarRoute: LayoutTeacherCalendarRoute,
  LayoutTeacherClassroomsRoute: LayoutTeacherClassroomsRoute,
  LayoutTeacherDashboardRoute: LayoutTeacherDashboardRoute,
  LayoutTeacherInsightsRoute: LayoutTeacherInsightsRoute,
  LayoutTeacherLibraryViewerRoute: LayoutTeacherLibraryViewerRoute,
  LayoutTeacherReportsRoute: LayoutTeacherReportsRoute,
  LayoutTeacherStudentsRoute: LayoutTeacherStudentsRoute,
  LayoutTeacherAnalyticsStudentIdRoute: LayoutTeacherAnalyticsStudentIdRoute,
  LayoutTeacherAnalyticsSkillsRoute: LayoutTeacherAnalyticsSkillsRoute,
  LayoutTeacherBooksBookIdRoute: LayoutTeacherBooksBookIdRoute,
  LayoutTeacherClassroomsClassIdRoute: LayoutTeacherClassroomsClassIdRoute,
  LayoutTeacherAnalyticsIndexRoute: LayoutTeacherAnalyticsIndexRoute,
  LayoutTeacherBooksIndexRoute: LayoutTeacherBooksIndexRoute,
  LayoutTeacherMaterialsIndexRoute: LayoutTeacherMaterialsIndexRoute,
}

const LayoutTeacherRouteWithChildren = LayoutTeacherRoute._addFileChildren(
  LayoutTeacherRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutPublisherRoute: typeof LayoutPublisherRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStudentRoute: typeof LayoutStudentRouteWithChildren
  LayoutTeacherRoute: typeof LayoutTeacherRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDreamaiGeneratorRoute: typeof LayoutDreamaiGeneratorRoute
  LayoutDreamaiLibraryRoute: typeof LayoutDreamaiLibraryRoute
  LayoutDreamaiMaterialsRoute: typeof LayoutDreamaiMaterialsRoute
  LayoutDreamaiVocabularyRoute: typeof LayoutDreamaiVocabularyRoute
  LayoutMessagingConversationIdRoute: typeof LayoutMessagingConversationIdRoute
  LayoutDreamaiIndexRoute: typeof LayoutDreamaiIndexRoute
  LayoutMessagingIndexRoute: typeof LayoutMessagingIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutPublisherRoute: LayoutPublisherRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStudentRoute: LayoutStudentRouteWithChildren,
  LayoutTeacherRoute: LayoutTeacherRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDreamaiGeneratorRoute: LayoutDreamaiGeneratorRoute,
  LayoutDreamaiLibraryRoute: LayoutDreamaiLibraryRoute,
  LayoutDreamaiMaterialsRoute: LayoutDreamaiMaterialsRoute,
  LayoutDreamaiVocabularyRoute: LayoutDreamaiVocabularyRoute,
  LayoutMessagingConversationIdRoute: LayoutMessagingConversationIdRoute,
  LayoutDreamaiIndexRoute: LayoutDreamaiIndexRoute,
  LayoutMessagingIndexRoute: LayoutMessagingIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ViewerBookIdRoute: ViewerBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
