/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTeacherRouteImport } from './routes/_layout.teacher'
import { Route as LayoutStudentRouteImport } from './routes/_layout.student'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPublisherRouteImport } from './routes/_layout.publisher'
import { Route as LayoutAdminRouteImport } from './routes/_layout.admin'
import { Route as LayoutMessagingIndexRouteImport } from './routes/_layout/messaging/index'
import { Route as LayoutTeacherStudentsRouteImport } from './routes/_layout/teacher/students'
import { Route as LayoutTeacherReportsRouteImport } from './routes/_layout/teacher/reports'
import { Route as LayoutTeacherDashboardRouteImport } from './routes/_layout/teacher/dashboard'
import { Route as LayoutTeacherClassroomsRouteImport } from './routes/_layout/teacher/classrooms'
import { Route as LayoutTeacherCalendarRouteImport } from './routes/_layout/teacher/calendar'
import { Route as LayoutTeacherBooksRouteImport } from './routes/_layout/teacher/books'
import { Route as LayoutTeacherAssignmentsRouteImport } from './routes/_layout/teacher/assignments'
import { Route as LayoutStudentReportsRouteImport } from './routes/_layout/student/reports'
import { Route as LayoutStudentDashboardRouteImport } from './routes/_layout/student/dashboard'
import { Route as LayoutStudentCalendarRouteImport } from './routes/_layout/student/calendar'
import { Route as LayoutStudentAssignmentsRouteImport } from './routes/_layout/student/assignments'
import { Route as LayoutPublisherTeachersRouteImport } from './routes/_layout/publisher/teachers'
import { Route as LayoutPublisherSchoolsRouteImport } from './routes/_layout/publisher/schools'
import { Route as LayoutPublisherLibraryRouteImport } from './routes/_layout/publisher/library'
import { Route as LayoutPublisherDashboardRouteImport } from './routes/_layout/publisher/dashboard'
import { Route as LayoutMessagingConversationIdRouteImport } from './routes/_layout/messaging/$conversationId'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin.users'
import { Route as LayoutAdminTeachersRouteImport } from './routes/_layout/admin/teachers'
import { Route as LayoutAdminStudentsRouteImport } from './routes/_layout/admin/students'
import { Route as LayoutAdminSchoolsRouteImport } from './routes/_layout/admin/schools'
import { Route as LayoutAdminPublishersRouteImport } from './routes/_layout/admin/publishers'
import { Route as LayoutAdminDashboardRouteImport } from './routes/_layout/admin/dashboard'
import { Route as LayoutAdminBooksRouteImport } from './routes/_layout/admin/books'
import { Route as LayoutAdminAssignmentsRouteImport } from './routes/_layout/admin/assignments'
import { Route as LayoutTeacherMaterialsIndexRouteImport } from './routes/_layout/teacher/materials/index'
import { Route as LayoutTeacherBooksIndexRouteImport } from './routes/_layout/teacher/books/index'
import { Route as LayoutTeacherAssignmentsIndexRouteImport } from './routes/_layout/teacher/assignments/index'
import { Route as LayoutTeacherAnalyticsIndexRouteImport } from './routes/_layout/teacher/analytics/index'
import { Route as LayoutStudentAssignmentsIndexRouteImport } from './routes/_layout/student/assignments/index'
import { Route as LayoutTeacherBooksBookIdRouteImport } from './routes/_layout/teacher/books/$bookId'
import { Route as LayoutTeacherAssignmentsAssignmentIdRouteImport } from './routes/_layout/teacher/assignments/$assignmentId'
import { Route as LayoutTeacherAnalyticsStudentIdRouteImport } from './routes/_layout/teacher/analytics/$studentId'
import { Route as LayoutStudentAssignmentsAssignmentIdPlayRouteImport } from './routes/_layout/student/assignments/$assignmentId/play'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeacherRoute = LayoutTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentRoute = LayoutStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPublisherRoute = LayoutPublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMessagingIndexRoute = LayoutMessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeacherStudentsRoute = LayoutTeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherReportsRoute = LayoutTeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherDashboardRoute = LayoutTeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherClassroomsRoute = LayoutTeacherClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherCalendarRoute = LayoutTeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherBooksRoute = LayoutTeacherBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LayoutTeacherRoute,
} as any)
const LayoutTeacherAssignmentsRoute =
  LayoutTeacherAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutStudentReportsRoute = LayoutStudentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutStudentRoute,
} as any)
const LayoutStudentDashboardRoute = LayoutStudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutStudentRoute,
} as any)
const LayoutStudentCalendarRoute = LayoutStudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutStudentRoute,
} as any)
const LayoutStudentAssignmentsRoute =
  LayoutStudentAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => LayoutStudentRoute,
  } as any)
const LayoutPublisherTeachersRoute = LayoutPublisherTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => LayoutPublisherRoute,
} as any)
const LayoutPublisherSchoolsRoute = LayoutPublisherSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => LayoutPublisherRoute,
} as any)
const LayoutPublisherLibraryRoute = LayoutPublisherLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => LayoutPublisherRoute,
} as any)
const LayoutPublisherDashboardRoute =
  LayoutPublisherDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutPublisherRoute,
  } as any)
const LayoutMessagingConversationIdRoute =
  LayoutMessagingConversationIdRouteImport.update({
    id: '/messaging/$conversationId',
    path: '/messaging/$conversationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminTeachersRoute = LayoutAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminStudentsRoute = LayoutAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSchoolsRoute = LayoutAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPublishersRoute = LayoutAdminPublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminDashboardRoute = LayoutAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminBooksRoute = LayoutAdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAssignmentsRoute = LayoutAdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutTeacherMaterialsIndexRoute =
  LayoutTeacherMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutTeacherBooksIndexRoute = LayoutTeacherBooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTeacherBooksRoute,
} as any)
const LayoutTeacherAssignmentsIndexRoute =
  LayoutTeacherAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutTeacherAssignmentsRoute,
  } as any)
const LayoutTeacherAnalyticsIndexRoute =
  LayoutTeacherAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutStudentAssignmentsIndexRoute =
  LayoutStudentAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutStudentAssignmentsRoute,
  } as any)
const LayoutTeacherBooksBookIdRoute =
  LayoutTeacherBooksBookIdRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => LayoutTeacherBooksRoute,
  } as any)
const LayoutTeacherAssignmentsAssignmentIdRoute =
  LayoutTeacherAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => LayoutTeacherAssignmentsRoute,
  } as any)
const LayoutTeacherAnalyticsStudentIdRoute =
  LayoutTeacherAnalyticsStudentIdRouteImport.update({
    id: '/analytics/$studentId',
    path: '/analytics/$studentId',
    getParentRoute: () => LayoutTeacherRoute,
  } as any)
const LayoutStudentAssignmentsAssignmentIdPlayRoute =
  LayoutStudentAssignmentsAssignmentIdPlayRouteImport.update({
    id: '/$assignmentId/play',
    path: '/$assignmentId/play',
    getParentRoute: () => LayoutStudentAssignmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/publisher': typeof LayoutPublisherRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/student': typeof LayoutStudentRouteWithChildren
  '/teacher': typeof LayoutTeacherRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/admin/assignments': typeof LayoutAdminAssignmentsRoute
  '/admin/books': typeof LayoutAdminBooksRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/admin/publishers': typeof LayoutAdminPublishersRoute
  '/admin/schools': typeof LayoutAdminSchoolsRoute
  '/admin/students': typeof LayoutAdminStudentsRoute
  '/admin/teachers': typeof LayoutAdminTeachersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/messaging/$conversationId': typeof LayoutMessagingConversationIdRoute
  '/publisher/dashboard': typeof LayoutPublisherDashboardRoute
  '/publisher/library': typeof LayoutPublisherLibraryRoute
  '/publisher/schools': typeof LayoutPublisherSchoolsRoute
  '/publisher/teachers': typeof LayoutPublisherTeachersRoute
  '/student/assignments': typeof LayoutStudentAssignmentsRouteWithChildren
  '/student/calendar': typeof LayoutStudentCalendarRoute
  '/student/dashboard': typeof LayoutStudentDashboardRoute
  '/student/reports': typeof LayoutStudentReportsRoute
  '/teacher/assignments': typeof LayoutTeacherAssignmentsRouteWithChildren
  '/teacher/books': typeof LayoutTeacherBooksRouteWithChildren
  '/teacher/calendar': typeof LayoutTeacherCalendarRoute
  '/teacher/classrooms': typeof LayoutTeacherClassroomsRoute
  '/teacher/dashboard': typeof LayoutTeacherDashboardRoute
  '/teacher/reports': typeof LayoutTeacherReportsRoute
  '/teacher/students': typeof LayoutTeacherStudentsRoute
  '/messaging': typeof LayoutMessagingIndexRoute
  '/teacher/analytics/$studentId': typeof LayoutTeacherAnalyticsStudentIdRoute
  '/teacher/assignments/$assignmentId': typeof LayoutTeacherAssignmentsAssignmentIdRoute
  '/teacher/books/$bookId': typeof LayoutTeacherBooksBookIdRoute
  '/student/assignments/': typeof LayoutStudentAssignmentsIndexRoute
  '/teacher/analytics': typeof LayoutTeacherAnalyticsIndexRoute
  '/teacher/assignments/': typeof LayoutTeacherAssignmentsIndexRoute
  '/teacher/books/': typeof LayoutTeacherBooksIndexRoute
  '/teacher/materials': typeof LayoutTeacherMaterialsIndexRoute
  '/student/assignments/$assignmentId/play': typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/publisher': typeof LayoutPublisherRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/student': typeof LayoutStudentRouteWithChildren
  '/teacher': typeof LayoutTeacherRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/admin/assignments': typeof LayoutAdminAssignmentsRoute
  '/admin/books': typeof LayoutAdminBooksRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/admin/publishers': typeof LayoutAdminPublishersRoute
  '/admin/schools': typeof LayoutAdminSchoolsRoute
  '/admin/students': typeof LayoutAdminStudentsRoute
  '/admin/teachers': typeof LayoutAdminTeachersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/messaging/$conversationId': typeof LayoutMessagingConversationIdRoute
  '/publisher/dashboard': typeof LayoutPublisherDashboardRoute
  '/publisher/library': typeof LayoutPublisherLibraryRoute
  '/publisher/schools': typeof LayoutPublisherSchoolsRoute
  '/publisher/teachers': typeof LayoutPublisherTeachersRoute
  '/student/calendar': typeof LayoutStudentCalendarRoute
  '/student/dashboard': typeof LayoutStudentDashboardRoute
  '/student/reports': typeof LayoutStudentReportsRoute
  '/teacher/calendar': typeof LayoutTeacherCalendarRoute
  '/teacher/classrooms': typeof LayoutTeacherClassroomsRoute
  '/teacher/dashboard': typeof LayoutTeacherDashboardRoute
  '/teacher/reports': typeof LayoutTeacherReportsRoute
  '/teacher/students': typeof LayoutTeacherStudentsRoute
  '/messaging': typeof LayoutMessagingIndexRoute
  '/teacher/analytics/$studentId': typeof LayoutTeacherAnalyticsStudentIdRoute
  '/teacher/assignments/$assignmentId': typeof LayoutTeacherAssignmentsAssignmentIdRoute
  '/teacher/books/$bookId': typeof LayoutTeacherBooksBookIdRoute
  '/student/assignments': typeof LayoutStudentAssignmentsIndexRoute
  '/teacher/analytics': typeof LayoutTeacherAnalyticsIndexRoute
  '/teacher/assignments': typeof LayoutTeacherAssignmentsIndexRoute
  '/teacher/books': typeof LayoutTeacherBooksIndexRoute
  '/teacher/materials': typeof LayoutTeacherMaterialsIndexRoute
  '/student/assignments/$assignmentId/play': typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/publisher': typeof LayoutPublisherRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/student': typeof LayoutStudentRouteWithChildren
  '/_layout/teacher': typeof LayoutTeacherRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/assignments': typeof LayoutAdminAssignmentsRoute
  '/_layout/admin/books': typeof LayoutAdminBooksRoute
  '/_layout/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/_layout/admin/publishers': typeof LayoutAdminPublishersRoute
  '/_layout/admin/schools': typeof LayoutAdminSchoolsRoute
  '/_layout/admin/students': typeof LayoutAdminStudentsRoute
  '/_layout/admin/teachers': typeof LayoutAdminTeachersRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/messaging/$conversationId': typeof LayoutMessagingConversationIdRoute
  '/_layout/publisher/dashboard': typeof LayoutPublisherDashboardRoute
  '/_layout/publisher/library': typeof LayoutPublisherLibraryRoute
  '/_layout/publisher/schools': typeof LayoutPublisherSchoolsRoute
  '/_layout/publisher/teachers': typeof LayoutPublisherTeachersRoute
  '/_layout/student/assignments': typeof LayoutStudentAssignmentsRouteWithChildren
  '/_layout/student/calendar': typeof LayoutStudentCalendarRoute
  '/_layout/student/dashboard': typeof LayoutStudentDashboardRoute
  '/_layout/student/reports': typeof LayoutStudentReportsRoute
  '/_layout/teacher/assignments': typeof LayoutTeacherAssignmentsRouteWithChildren
  '/_layout/teacher/books': typeof LayoutTeacherBooksRouteWithChildren
  '/_layout/teacher/calendar': typeof LayoutTeacherCalendarRoute
  '/_layout/teacher/classrooms': typeof LayoutTeacherClassroomsRoute
  '/_layout/teacher/dashboard': typeof LayoutTeacherDashboardRoute
  '/_layout/teacher/reports': typeof LayoutTeacherReportsRoute
  '/_layout/teacher/students': typeof LayoutTeacherStudentsRoute
  '/_layout/messaging/': typeof LayoutMessagingIndexRoute
  '/_layout/teacher/analytics/$studentId': typeof LayoutTeacherAnalyticsStudentIdRoute
  '/_layout/teacher/assignments/$assignmentId': typeof LayoutTeacherAssignmentsAssignmentIdRoute
  '/_layout/teacher/books/$bookId': typeof LayoutTeacherBooksBookIdRoute
  '/_layout/student/assignments/': typeof LayoutStudentAssignmentsIndexRoute
  '/_layout/teacher/analytics/': typeof LayoutTeacherAnalyticsIndexRoute
  '/_layout/teacher/assignments/': typeof LayoutTeacherAssignmentsIndexRoute
  '/_layout/teacher/books/': typeof LayoutTeacherBooksIndexRoute
  '/_layout/teacher/materials/': typeof LayoutTeacherMaterialsIndexRoute
  '/_layout/student/assignments/$assignmentId/play': typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/publisher'
    | '/settings'
    | '/student'
    | '/teacher'
    | '/'
    | '/admin/assignments'
    | '/admin/books'
    | '/admin/dashboard'
    | '/admin/publishers'
    | '/admin/schools'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/messaging/$conversationId'
    | '/publisher/dashboard'
    | '/publisher/library'
    | '/publisher/schools'
    | '/publisher/teachers'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/dashboard'
    | '/student/reports'
    | '/teacher/assignments'
    | '/teacher/books'
    | '/teacher/calendar'
    | '/teacher/classrooms'
    | '/teacher/dashboard'
    | '/teacher/reports'
    | '/teacher/students'
    | '/messaging'
    | '/teacher/analytics/$studentId'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/books/$bookId'
    | '/student/assignments/'
    | '/teacher/analytics'
    | '/teacher/assignments/'
    | '/teacher/books/'
    | '/teacher/materials'
    | '/student/assignments/$assignmentId/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/publisher'
    | '/settings'
    | '/student'
    | '/teacher'
    | '/'
    | '/admin/assignments'
    | '/admin/books'
    | '/admin/dashboard'
    | '/admin/publishers'
    | '/admin/schools'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/messaging/$conversationId'
    | '/publisher/dashboard'
    | '/publisher/library'
    | '/publisher/schools'
    | '/publisher/teachers'
    | '/student/calendar'
    | '/student/dashboard'
    | '/student/reports'
    | '/teacher/calendar'
    | '/teacher/classrooms'
    | '/teacher/dashboard'
    | '/teacher/reports'
    | '/teacher/students'
    | '/messaging'
    | '/teacher/analytics/$studentId'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/books/$bookId'
    | '/student/assignments'
    | '/teacher/analytics'
    | '/teacher/assignments'
    | '/teacher/books'
    | '/teacher/materials'
    | '/student/assignments/$assignmentId/play'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/publisher'
    | '/_layout/settings'
    | '/_layout/student'
    | '/_layout/teacher'
    | '/_layout/'
    | '/_layout/admin/assignments'
    | '/_layout/admin/books'
    | '/_layout/admin/dashboard'
    | '/_layout/admin/publishers'
    | '/_layout/admin/schools'
    | '/_layout/admin/students'
    | '/_layout/admin/teachers'
    | '/_layout/admin/users'
    | '/_layout/messaging/$conversationId'
    | '/_layout/publisher/dashboard'
    | '/_layout/publisher/library'
    | '/_layout/publisher/schools'
    | '/_layout/publisher/teachers'
    | '/_layout/student/assignments'
    | '/_layout/student/calendar'
    | '/_layout/student/dashboard'
    | '/_layout/student/reports'
    | '/_layout/teacher/assignments'
    | '/_layout/teacher/books'
    | '/_layout/teacher/calendar'
    | '/_layout/teacher/classrooms'
    | '/_layout/teacher/dashboard'
    | '/_layout/teacher/reports'
    | '/_layout/teacher/students'
    | '/_layout/messaging/'
    | '/_layout/teacher/analytics/$studentId'
    | '/_layout/teacher/assignments/$assignmentId'
    | '/_layout/teacher/books/$bookId'
    | '/_layout/student/assignments/'
    | '/_layout/teacher/analytics/'
    | '/_layout/teacher/assignments/'
    | '/_layout/teacher/books/'
    | '/_layout/teacher/materials/'
    | '/_layout/student/assignments/$assignmentId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teacher': {
      id: '/_layout/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof LayoutTeacherRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/student': {
      id: '/_layout/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof LayoutStudentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/publisher': {
      id: '/_layout/publisher'
      path: '/publisher'
      fullPath: '/publisher'
      preLoaderRoute: typeof LayoutPublisherRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/messaging/': {
      id: '/_layout/messaging/'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof LayoutMessagingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teacher/students': {
      id: '/_layout/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof LayoutTeacherStudentsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/reports': {
      id: '/_layout/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof LayoutTeacherReportsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/dashboard': {
      id: '/_layout/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof LayoutTeacherDashboardRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/classrooms': {
      id: '/_layout/teacher/classrooms'
      path: '/classrooms'
      fullPath: '/teacher/classrooms'
      preLoaderRoute: typeof LayoutTeacherClassroomsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/calendar': {
      id: '/_layout/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof LayoutTeacherCalendarRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/books': {
      id: '/_layout/teacher/books'
      path: '/books'
      fullPath: '/teacher/books'
      preLoaderRoute: typeof LayoutTeacherBooksRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/assignments': {
      id: '/_layout/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof LayoutTeacherAssignmentsRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/student/reports': {
      id: '/_layout/student/reports'
      path: '/reports'
      fullPath: '/student/reports'
      preLoaderRoute: typeof LayoutStudentReportsRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/dashboard': {
      id: '/_layout/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof LayoutStudentDashboardRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/calendar': {
      id: '/_layout/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof LayoutStudentCalendarRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/student/assignments': {
      id: '/_layout/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof LayoutStudentAssignmentsRouteImport
      parentRoute: typeof LayoutStudentRoute
    }
    '/_layout/publisher/teachers': {
      id: '/_layout/publisher/teachers'
      path: '/teachers'
      fullPath: '/publisher/teachers'
      preLoaderRoute: typeof LayoutPublisherTeachersRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/schools': {
      id: '/_layout/publisher/schools'
      path: '/schools'
      fullPath: '/publisher/schools'
      preLoaderRoute: typeof LayoutPublisherSchoolsRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/library': {
      id: '/_layout/publisher/library'
      path: '/library'
      fullPath: '/publisher/library'
      preLoaderRoute: typeof LayoutPublisherLibraryRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/publisher/dashboard': {
      id: '/_layout/publisher/dashboard'
      path: '/dashboard'
      fullPath: '/publisher/dashboard'
      preLoaderRoute: typeof LayoutPublisherDashboardRouteImport
      parentRoute: typeof LayoutPublisherRoute
    }
    '/_layout/messaging/$conversationId': {
      id: '/_layout/messaging/$conversationId'
      path: '/messaging/$conversationId'
      fullPath: '/messaging/$conversationId'
      preLoaderRoute: typeof LayoutMessagingConversationIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/teachers': {
      id: '/_layout/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof LayoutAdminTeachersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/students': {
      id: '/_layout/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof LayoutAdminStudentsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/schools': {
      id: '/_layout/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof LayoutAdminSchoolsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/publishers': {
      id: '/_layout/admin/publishers'
      path: '/publishers'
      fullPath: '/admin/publishers'
      preLoaderRoute: typeof LayoutAdminPublishersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/dashboard': {
      id: '/_layout/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof LayoutAdminDashboardRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/books': {
      id: '/_layout/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof LayoutAdminBooksRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/assignments': {
      id: '/_layout/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof LayoutAdminAssignmentsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/teacher/materials/': {
      id: '/_layout/teacher/materials/'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof LayoutTeacherMaterialsIndexRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/teacher/books/': {
      id: '/_layout/teacher/books/'
      path: '/'
      fullPath: '/teacher/books/'
      preLoaderRoute: typeof LayoutTeacherBooksIndexRouteImport
      parentRoute: typeof LayoutTeacherBooksRoute
    }
    '/_layout/teacher/assignments/': {
      id: '/_layout/teacher/assignments/'
      path: '/'
      fullPath: '/teacher/assignments/'
      preLoaderRoute: typeof LayoutTeacherAssignmentsIndexRouteImport
      parentRoute: typeof LayoutTeacherAssignmentsRoute
    }
    '/_layout/teacher/analytics/': {
      id: '/_layout/teacher/analytics/'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof LayoutTeacherAnalyticsIndexRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/student/assignments/': {
      id: '/_layout/student/assignments/'
      path: '/'
      fullPath: '/student/assignments/'
      preLoaderRoute: typeof LayoutStudentAssignmentsIndexRouteImport
      parentRoute: typeof LayoutStudentAssignmentsRoute
    }
    '/_layout/teacher/books/$bookId': {
      id: '/_layout/teacher/books/$bookId'
      path: '/$bookId'
      fullPath: '/teacher/books/$bookId'
      preLoaderRoute: typeof LayoutTeacherBooksBookIdRouteImport
      parentRoute: typeof LayoutTeacherBooksRoute
    }
    '/_layout/teacher/assignments/$assignmentId': {
      id: '/_layout/teacher/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/teacher/assignments/$assignmentId'
      preLoaderRoute: typeof LayoutTeacherAssignmentsAssignmentIdRouteImport
      parentRoute: typeof LayoutTeacherAssignmentsRoute
    }
    '/_layout/teacher/analytics/$studentId': {
      id: '/_layout/teacher/analytics/$studentId'
      path: '/analytics/$studentId'
      fullPath: '/teacher/analytics/$studentId'
      preLoaderRoute: typeof LayoutTeacherAnalyticsStudentIdRouteImport
      parentRoute: typeof LayoutTeacherRoute
    }
    '/_layout/student/assignments/$assignmentId/play': {
      id: '/_layout/student/assignments/$assignmentId/play'
      path: '/$assignmentId/play'
      fullPath: '/student/assignments/$assignmentId/play'
      preLoaderRoute: typeof LayoutStudentAssignmentsAssignmentIdPlayRouteImport
      parentRoute: typeof LayoutStudentAssignmentsRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAssignmentsRoute: typeof LayoutAdminAssignmentsRoute
  LayoutAdminBooksRoute: typeof LayoutAdminBooksRoute
  LayoutAdminDashboardRoute: typeof LayoutAdminDashboardRoute
  LayoutAdminPublishersRoute: typeof LayoutAdminPublishersRoute
  LayoutAdminSchoolsRoute: typeof LayoutAdminSchoolsRoute
  LayoutAdminStudentsRoute: typeof LayoutAdminStudentsRoute
  LayoutAdminTeachersRoute: typeof LayoutAdminTeachersRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAssignmentsRoute: LayoutAdminAssignmentsRoute,
  LayoutAdminBooksRoute: LayoutAdminBooksRoute,
  LayoutAdminDashboardRoute: LayoutAdminDashboardRoute,
  LayoutAdminPublishersRoute: LayoutAdminPublishersRoute,
  LayoutAdminSchoolsRoute: LayoutAdminSchoolsRoute,
  LayoutAdminStudentsRoute: LayoutAdminStudentsRoute,
  LayoutAdminTeachersRoute: LayoutAdminTeachersRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutPublisherRouteChildren {
  LayoutPublisherDashboardRoute: typeof LayoutPublisherDashboardRoute
  LayoutPublisherLibraryRoute: typeof LayoutPublisherLibraryRoute
  LayoutPublisherSchoolsRoute: typeof LayoutPublisherSchoolsRoute
  LayoutPublisherTeachersRoute: typeof LayoutPublisherTeachersRoute
}

const LayoutPublisherRouteChildren: LayoutPublisherRouteChildren = {
  LayoutPublisherDashboardRoute: LayoutPublisherDashboardRoute,
  LayoutPublisherLibraryRoute: LayoutPublisherLibraryRoute,
  LayoutPublisherSchoolsRoute: LayoutPublisherSchoolsRoute,
  LayoutPublisherTeachersRoute: LayoutPublisherTeachersRoute,
}

const LayoutPublisherRouteWithChildren = LayoutPublisherRoute._addFileChildren(
  LayoutPublisherRouteChildren,
)

interface LayoutStudentAssignmentsRouteChildren {
  LayoutStudentAssignmentsIndexRoute: typeof LayoutStudentAssignmentsIndexRoute
  LayoutStudentAssignmentsAssignmentIdPlayRoute: typeof LayoutStudentAssignmentsAssignmentIdPlayRoute
}

const LayoutStudentAssignmentsRouteChildren: LayoutStudentAssignmentsRouteChildren =
  {
    LayoutStudentAssignmentsIndexRoute: LayoutStudentAssignmentsIndexRoute,
    LayoutStudentAssignmentsAssignmentIdPlayRoute:
      LayoutStudentAssignmentsAssignmentIdPlayRoute,
  }

const LayoutStudentAssignmentsRouteWithChildren =
  LayoutStudentAssignmentsRoute._addFileChildren(
    LayoutStudentAssignmentsRouteChildren,
  )

interface LayoutStudentRouteChildren {
  LayoutStudentAssignmentsRoute: typeof LayoutStudentAssignmentsRouteWithChildren
  LayoutStudentCalendarRoute: typeof LayoutStudentCalendarRoute
  LayoutStudentDashboardRoute: typeof LayoutStudentDashboardRoute
  LayoutStudentReportsRoute: typeof LayoutStudentReportsRoute
}

const LayoutStudentRouteChildren: LayoutStudentRouteChildren = {
  LayoutStudentAssignmentsRoute: LayoutStudentAssignmentsRouteWithChildren,
  LayoutStudentCalendarRoute: LayoutStudentCalendarRoute,
  LayoutStudentDashboardRoute: LayoutStudentDashboardRoute,
  LayoutStudentReportsRoute: LayoutStudentReportsRoute,
}

const LayoutStudentRouteWithChildren = LayoutStudentRoute._addFileChildren(
  LayoutStudentRouteChildren,
)

interface LayoutTeacherAssignmentsRouteChildren {
  LayoutTeacherAssignmentsAssignmentIdRoute: typeof LayoutTeacherAssignmentsAssignmentIdRoute
  LayoutTeacherAssignmentsIndexRoute: typeof LayoutTeacherAssignmentsIndexRoute
}

const LayoutTeacherAssignmentsRouteChildren: LayoutTeacherAssignmentsRouteChildren =
  {
    LayoutTeacherAssignmentsAssignmentIdRoute:
      LayoutTeacherAssignmentsAssignmentIdRoute,
    LayoutTeacherAssignmentsIndexRoute: LayoutTeacherAssignmentsIndexRoute,
  }

const LayoutTeacherAssignmentsRouteWithChildren =
  LayoutTeacherAssignmentsRoute._addFileChildren(
    LayoutTeacherAssignmentsRouteChildren,
  )

interface LayoutTeacherBooksRouteChildren {
  LayoutTeacherBooksBookIdRoute: typeof LayoutTeacherBooksBookIdRoute
  LayoutTeacherBooksIndexRoute: typeof LayoutTeacherBooksIndexRoute
}

const LayoutTeacherBooksRouteChildren: LayoutTeacherBooksRouteChildren = {
  LayoutTeacherBooksBookIdRoute: LayoutTeacherBooksBookIdRoute,
  LayoutTeacherBooksIndexRoute: LayoutTeacherBooksIndexRoute,
}

const LayoutTeacherBooksRouteWithChildren =
  LayoutTeacherBooksRoute._addFileChildren(LayoutTeacherBooksRouteChildren)

interface LayoutTeacherRouteChildren {
  LayoutTeacherAssignmentsRoute: typeof LayoutTeacherAssignmentsRouteWithChildren
  LayoutTeacherBooksRoute: typeof LayoutTeacherBooksRouteWithChildren
  LayoutTeacherCalendarRoute: typeof LayoutTeacherCalendarRoute
  LayoutTeacherClassroomsRoute: typeof LayoutTeacherClassroomsRoute
  LayoutTeacherDashboardRoute: typeof LayoutTeacherDashboardRoute
  LayoutTeacherReportsRoute: typeof LayoutTeacherReportsRoute
  LayoutTeacherStudentsRoute: typeof LayoutTeacherStudentsRoute
  LayoutTeacherAnalyticsStudentIdRoute: typeof LayoutTeacherAnalyticsStudentIdRoute
  LayoutTeacherAnalyticsIndexRoute: typeof LayoutTeacherAnalyticsIndexRoute
  LayoutTeacherMaterialsIndexRoute: typeof LayoutTeacherMaterialsIndexRoute
}

const LayoutTeacherRouteChildren: LayoutTeacherRouteChildren = {
  LayoutTeacherAssignmentsRoute: LayoutTeacherAssignmentsRouteWithChildren,
  LayoutTeacherBooksRoute: LayoutTeacherBooksRouteWithChildren,
  LayoutTeacherCalendarRoute: LayoutTeacherCalendarRoute,
  LayoutTeacherClassroomsRoute: LayoutTeacherClassroomsRoute,
  LayoutTeacherDashboardRoute: LayoutTeacherDashboardRoute,
  LayoutTeacherReportsRoute: LayoutTeacherReportsRoute,
  LayoutTeacherStudentsRoute: LayoutTeacherStudentsRoute,
  LayoutTeacherAnalyticsStudentIdRoute: LayoutTeacherAnalyticsStudentIdRoute,
  LayoutTeacherAnalyticsIndexRoute: LayoutTeacherAnalyticsIndexRoute,
  LayoutTeacherMaterialsIndexRoute: LayoutTeacherMaterialsIndexRoute,
}

const LayoutTeacherRouteWithChildren = LayoutTeacherRoute._addFileChildren(
  LayoutTeacherRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutPublisherRoute: typeof LayoutPublisherRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStudentRoute: typeof LayoutStudentRouteWithChildren
  LayoutTeacherRoute: typeof LayoutTeacherRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMessagingConversationIdRoute: typeof LayoutMessagingConversationIdRoute
  LayoutMessagingIndexRoute: typeof LayoutMessagingIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutPublisherRoute: LayoutPublisherRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStudentRoute: LayoutStudentRouteWithChildren,
  LayoutTeacherRoute: LayoutTeacherRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMessagingConversationIdRoute: LayoutMessagingConversationIdRoute,
  LayoutMessagingIndexRoute: LayoutMessagingIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
